#!/usr/bin/env python3
"""Render first-party Buck2 lint and Clippy configuration policy from Cargo."""

from __future__ import annotations

import json
import pathlib
import tomllib


_LEVEL_FLAGS = {
    "allow": "--allow",
    "warn": "--warn",
    "deny": "--deny",
    "forbid": "--forbid",
}


def _literal(value: object) -> str:
    return json.dumps(value, sort_keys=True)


def _lint_flags(table: dict, namespace: str | None) -> list[str]:
    flags = []
    for name, specification in table.items():
        if isinstance(specification, str):
            level = specification
            check_cfg = []
        elif isinstance(specification, dict):
            level = specification.get("level")
            check_cfg = specification.get("check-cfg", [])
        else:
            raise ValueError(f"lint {name!r} has unsupported policy {specification!r}")
        option = _LEVEL_FLAGS.get(level)
        if option is None:
            raise ValueError(f"lint {name!r} has unsupported level {level!r}")
        qualified = f"{namespace}::{name}" if namespace else name
        flags.append(f"{option}={qualified}")
        if namespace is None:
            flags.extend(f"--check-cfg={value}" for value in check_cfg)
    return flags


def _workspace_packages(canonical: dict, root: pathlib.Path) -> list[pathlib.Path]:
    members = set(canonical.get("workspace_members", []))
    packages = [
        package
        for package in canonical.get("packages", [])
        if package.get("id") in members
    ]
    if not packages:
        raise ValueError("Cargo metadata contains no workspace packages")
    manifests = []
    for package in packages:
        manifest = pathlib.Path(package["manifest_path"]).resolve()
        try:
            manifest.relative_to(root.resolve())
        except ValueError as error:
            raise ValueError(f"workspace manifest escapes repository: {manifest}") from error
        content = tomllib.loads(manifest.read_text(encoding="utf-8"))
        if content.get("lints", {}).get("workspace") is not True:
            relative = manifest.relative_to(root.resolve())
            raise ValueError(f"{relative}: workspace package does not inherit [workspace.lints]")
        manifests.append(manifest)
    return sorted(manifests)


def _clippy_configs(manifests: list[pathlib.Path], root: pathlib.Path) -> list[pathlib.Path]:
    configs = [root / "clippy.toml"]
    for manifest in manifests:
        directory = manifest.parent
        while directory != root:
            candidate = directory / "clippy.toml"
            if candidate.is_file():
                configs.append(candidate)
            directory = directory.parent
    missing = [path for path in configs if not path.is_file()]
    if missing:
        raise ValueError(f"Clippy configuration is missing: {missing[0]}")
    return sorted(set(configs))


def _config_name(directory: str) -> str:
    if not directory:
        return "clippy_config_root"
    return "clippy_config_" + directory.replace("/", "_").replace("-", "_")


def render(canonical: dict, root: pathlib.Path) -> str:
    """Return deterministic Starlark policy for Cargo's workspace members."""

    root = root.resolve()
    workspace = tomllib.loads((root / "Cargo.toml").read_text(encoding="utf-8"))
    lint_tables = workspace.get("workspace", {}).get("lints", {})
    rust_flags = _lint_flags(lint_tables.get("rust", {}), None)
    clippy_flags = _lint_flags(lint_tables.get("clippy", {}), "clippy")
    if not rust_flags or not clippy_flags:
        raise ValueError("Cargo.toml must declare both Rust and Clippy workspace lints")

    manifests = _workspace_packages(canonical, root)
    configs = _clippy_configs(manifests, root)
    entries = []
    for config in configs:
        directory = config.parent.relative_to(root).as_posix()
        if directory == ".":
            directory = ""
        name = _config_name(directory)
        source = f"//{directory}:clippy.toml" if directory else "//:clippy.toml"
        entries.append((directory, name, source))

    lines = [
        "# @generated by tools/buck2/sync.py; do not edit.\n",
        'load(":clippy_configuration.bzl", '
        '_clippy_configuration = "first_party_clippy_configuration_rule")\n\n',
        f"WORKSPACE_PACKAGE_COUNT = {len(manifests)}\n\n",
        "FIRST_PARTY_RUST_LINT_FLAGS = " + _literal(rust_flags) + "\n\n",
        "FIRST_PARTY_CLIPPY_LINT_FLAGS = " + _literal(clippy_flags) + "\n\n",
        "_CLIPPY_CONFIGS = {\n",
    ]
    for directory, name, source in entries:
        lines.append(f"    {_literal(directory)}: ({_literal(name)}, {_literal(source)}),\n")
    lines.extend(
        [
            "}\n\n",
            "def declare_clippy_configurations():\n",
            "    for _directory, spec in _CLIPPY_CONFIGS.items():\n",
            "        _clippy_configuration(\n",
            "            name = spec[0],\n",
            "            clippy_toml = spec[1],\n",
            "            visibility = [\"PUBLIC\"],\n",
            "        )\n\n",
            "def first_party_clippy_configuration(manifest_dir):\n",
            "    best = \"\"\n",
            "    for directory in _CLIPPY_CONFIGS:\n",
            "        if directory and not (manifest_dir == directory "
            "or manifest_dir.startswith(directory + \"/\")):\n",
            "            continue\n",
            "        if len(directory) > len(best):\n",
            "            best = directory\n",
            "    return \"//tools/buck2:{}\".format(_CLIPPY_CONFIGS[best][0])\n",
        ]
    )
    return "".join(lines)
