# @generated by tools/buck2/sync.py; do not edit.
load(":clippy_configuration.bzl", _clippy_configuration = "first_party_clippy_configuration_rule")

WORKSPACE_PACKAGE_COUNT = 53

FIRST_PARTY_RUST_LINT_FLAGS = ["--deny=unsafe_code", "--deny=unexpected_cfgs", "--check-cfg=cfg(loom)", "--check-cfg=cfg(kani)", "--check-cfg=cfg(miri)", "--check-cfg=cfg(fuzzing)"]

FIRST_PARTY_CLIPPY_LINT_FLAGS = ["--deny=clippy::await_holding_lock", "--deny=clippy::disallowed_methods", "--deny=clippy::expect_used", "--deny=clippy::unwrap_used", "--deny=clippy::identity_op", "--deny=clippy::manual_clamp", "--deny=clippy::manual_filter", "--deny=clippy::manual_find", "--deny=clippy::manual_flatten", "--deny=clippy::manual_map", "--deny=clippy::manual_memcpy", "--deny=clippy::manual_non_exhaustive", "--deny=clippy::manual_ok_or", "--deny=clippy::manual_range_contains", "--deny=clippy::manual_retain", "--deny=clippy::manual_strip", "--deny=clippy::manual_try_fold", "--deny=clippy::manual_unwrap_or", "--deny=clippy::needless_borrow", "--deny=clippy::needless_borrowed_reference", "--deny=clippy::needless_late_init", "--deny=clippy::needless_option_as_deref", "--deny=clippy::needless_question_mark", "--deny=clippy::needless_update", "--deny=clippy::redundant_closure", "--deny=clippy::redundant_static_lifetimes", "--deny=clippy::unnecessary_filter_map", "--deny=clippy::unnecessary_lazy_evaluations", "--deny=clippy::unnecessary_sort_by", "--deny=clippy::unnecessary_to_owned", "--warn=clippy::large_enum_variant", "--warn=clippy::large_futures", "--warn=clippy::result_large_err"]

_CLIPPY_CONFIGS = {
    "": ("clippy_config_root", "//:clippy.toml"),
    "crates/lash-conformance": ("clippy_config_crates_lash_conformance", "//crates/lash-conformance:clippy.toml"),
    "crates/lash-core": ("clippy_config_crates_lash_core", "//crates/lash-core:clippy.toml"),
    "crates/lash-core-effect": ("clippy_config_crates_lash_core_effect", "//crates/lash-core-effect:clippy.toml"),
    "crates/lash-core-execution": ("clippy_config_crates_lash_core_execution", "//crates/lash-core-execution:clippy.toml"),
    "crates/lash-core-store": ("clippy_config_crates_lash_core_store", "//crates/lash-core-store:clippy.toml"),
    "crates/lash-core-worker": ("clippy_config_crates_lash_core_worker", "//crates/lash-core-worker:clippy.toml"),
    "crates/lash-e2e": ("clippy_config_crates_lash_e2e", "//crates/lash-e2e:clippy.toml"),
    "crates/lash-perf": ("clippy_config_crates_lash_perf", "//crates/lash-perf:clippy.toml"),
    "crates/lash-postgres-workers": ("clippy_config_crates_lash_postgres_workers", "//crates/lash-postgres-workers:clippy.toml"),
    "crates/lash-sim": ("clippy_config_crates_lash_sim", "//crates/lash-sim:clippy.toml"),
    "examples/agent-workbench": ("clippy_config_examples_agent_workbench", "//examples/agent-workbench:clippy.toml"),
    "examples/codex-host-auth": ("clippy_config_examples_codex_host_auth", "//examples/codex-host-auth:clippy.toml"),
    "examples/e2e-consumer": ("clippy_config_examples_e2e_consumer", "//examples/e2e-consumer:clippy.toml"),
    "examples/toolbench": ("clippy_config_examples_toolbench", "//examples/toolbench:clippy.toml"),
    "examples/workflow-graph-roundtrip": ("clippy_config_examples_workflow_graph_roundtrip", "//examples/workflow-graph-roundtrip:clippy.toml"),
    "runbooks/rlm-smoke": ("clippy_config_runbooks_rlm_smoke", "//runbooks/rlm-smoke:clippy.toml"),
}

def declare_clippy_configurations():
    for _directory, spec in _CLIPPY_CONFIGS.items():
        _clippy_configuration(
            name = spec[0],
            clippy_toml = spec[1],
            visibility = ["PUBLIC"],
        )

def first_party_clippy_configuration(manifest_dir):
    best = ""
    for directory in _CLIPPY_CONFIGS:
        if directory and not (manifest_dir == directory or manifest_dir.startswith(directory + "/")):
            continue
        if len(directory) > len(best):
            best = directory
    return "//tools/buck2:{}".format(_CLIPPY_CONFIGS[best][0])
