# @generated by tools/buck2/sync.py; do not edit.
PACKAGE_DEPS = {
    "agent-workbench": {
        "build": {},
        "dev": {
            "http": "//third-party/rust:p0147",
            "lash": "//crates/lash:lash",
            "lash_sim": "//crates/lash-sim:lash-sim",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "async_trait": "//third-party/rust:p0015",
            "axum": "//third-party/rust:p0021",
            "base64": "//third-party/rust:p0024",
            "bytes": "//third-party/rust:p0036",
            "chrono": "//third-party/rust:p0044",
            "chrono_tz": "//third-party/rust:p0045",
            "croner": "//third-party/rust:p0071",
            "delegation": "//examples/delegation:delegation",
            "dotenvy": "//third-party/rust:p0094",
            "futures_util": "//third-party/rust:p0127",
            "lash": "//crates/lash:lash",
            "percent_encoding": "//third-party/rust:p0230",
            "reqwest": "//third-party/rust:p0278",
            "rmcp": "//third-party/rust:p0280",
            "rusqlite": "//third-party/rust:p0284",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tokio_stream": "//third-party/rust:p0377",
            "tracing_subscriber": "//third-party/rust:p0392",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "codex-host-auth": {
        "build": {},
        "dev": {},
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0024",
            "form_urlencoded": "//third-party/rust:p0114",
            "lash": "//crates/lash:lash",
            "reqwest": "//third-party/rust:p0278",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "delegation": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "lash": "//crates/lash:lash",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "e2e-consumer": {
        "build": {},
        "dev": {
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "axum": "//third-party/rust:p0021",
            "chrono": "//third-party/rust:p0044",
            "futures_util": "//third-party/rust:p0127",
            "lash": "//crates/lash:lash",
            "opentelemetry_sdk": "//third-party/rust:p0224",
            "reqwest": "//third-party/rust:p0278",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "integrator-contract": {
        "build": {},
        "dev": {},
        "normal": {
            "lash": "//crates/lash:lash"
        }
    },
    "lash-dialect-typescript": {
        "build": {},
        "dev": {
            "lash_kernel_check": "//crates/lash-kernel-check:lash-kernel-check",
            "lash_kernel_edit": "//crates/lash-kernel-edit:lash-kernel-edit",
            "lash_kernel_lib": "//crates/lash-kernel-lib:lash-kernel-lib",
            "lash_kernel_vm": "//crates/lash-kernel-vm:lash-kernel-vm",
            "serde": "//third-party/rust:p0308",
            "serde_yaml": "//third-party/rust:p0318"
        },
        "normal": {
            "lash_kernel_dialect": "//crates/lash-kernel-dialect:lash-kernel-dialect",
            "lash_kernel_doc": "//crates/lash-kernel-doc:lash-kernel-doc",
            "ryu_js": "//third-party/rust:p0297",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "swc_common": "//third-party/rust:p0352",
            "swc_ecma_ast": "//third-party/rust:p0353",
            "swc_ecma_parser": "//third-party/rust:p0354",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-e2e": {
        "build": {},
        "dev": {
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "axum": "//third-party/rust:p0021",
            "futures_util": "//third-party/rust:p0127",
            "lash": "//crates/lash:lash",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "libc": "//third-party/rust:p0188",
            "reqwest": "//third-party/rust:p0278",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "lash-ext-regex-ecma": {
        "build": {},
        "dev": {},
        "normal": {
            "lash_kernel_doc": "//crates/lash-kernel-doc:lash-kernel-doc",
            "lash_regress": "//crates/lash-regress:lash-regress",
            "num_traits": "//third-party/rust:p0217",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-facade-failover": {
        "build": {},
        "dev": {
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash": "//crates/lash:lash",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sqlx": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0372",
            "tokio_util": "//third-party/rust:p0379"
        }
    },
    "lash-internal-conformance": {
        "build": {},
        "dev": {
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0044",
            "futures_util": "//third-party/rust:p0127",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "pretty_assertions": "//third-party/rust:p0246",
            "proptest": "//third-party/rust:p0249",
            "rmp_serde": "//third-party/rust:p0283",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "tokio": "//third-party/rust:p0372",
            "tokio_util": "//third-party/rust:p0379",
            "tracing": "//third-party/rust:p0388",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-internal-core": {
        "build": {},
        "dev": {
            "chrono": "//third-party/rust:p0044",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372",
            "tracing_subscriber": "//third-party/rust:p0392"
        },
        "normal": {
            "arc_swap": "//third-party/rust:p0012",
            "async_trait": "//third-party/rust:p0015",
            "futures_util": "//third-party/rust:p0127",
            "lash_core_effect": "//crates/lash-core-effect:lash-core-effect",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_llm": "//crates/lash-core-llm:lash-core-llm",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "libc": "//third-party/rust:p0188",
            "rmp_serde": "//third-party/rust:p0283",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tokio_util": "//third-party/rust:p0379",
            "tracing": "//third-party/rust:p0388",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-internal-core-effect": {
        "build": {},
        "dev": {},
        "normal": {
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-internal-core-execution": {
        "build": {},
        "dev": {
            "insta": "//third-party/rust:p0170",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "proptest": "//third-party/rust:p0249",
            "syn": "//third-party/rust:p0358",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0044",
            "futures_util": "//third-party/rust:p0127",
            "lash_core_effect": "//crates/lash-core-effect:lash-core-effect",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_llm": "//crates/lash-core-llm:lash-core-llm",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "rmp_serde": "//third-party/rust:p0283",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tokio_util": "//third-party/rust:p0379",
            "tracing": "//third-party/rust:p0388",
            "tracing_subscriber": "//third-party/rust:p0392",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-internal-core-ids": {
        "build": {},
        "dev": {},
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0044",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tracing": "//third-party/rust:p0388",
            "tracing_subscriber": "//third-party/rust:p0392"
        }
    },
    "lash-internal-core-llm": {
        "build": {},
        "dev": {
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0024",
            "chrono": "//third-party/rust:p0044",
            "futures_util": "//third-party/rust:p0127",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_http_transport": "//crates/lash-http-transport:lash-http-transport",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tracing": "//third-party/rust:p0388"
        }
    },
    "lash-internal-core-store": {
        "build": {},
        "dev": {
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_llm": "//crates/lash-core-llm:lash-core-llm",
            "lash_render": "//crates/lash-render:lash-render",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_llm": "//crates/lash-core-llm:lash-core-llm",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "rmp_serde": "//third-party/rust:p0283",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_bytes": "//third-party/rust:p0309",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tracing": "//third-party/rust:p0388",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-internal-core-worker": {
        "build": {},
        "dev": {},
        "normal": {
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "serde_json": "//third-party/rust:p0314",
            "tokio_util": "//third-party/rust:p0379",
            "tracing": "//third-party/rust:p0388"
        }
    },
    "lash-internal-durable": {
        "build": {},
        "dev": {},
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "futures_util": "//third-party/rust:p0127",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "lash-internal-durable-test": {
        "build": {},
        "dev": {
            "base64": "//third-party/rust:p0024",
            "delegation": "//examples/delegation:delegation",
            "flate2": "//third-party/rust:p0109",
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_llm_tools": "//crates/lash-llm-tools:lash-llm-tools",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_plugin_standard_compaction": "//crates/lash-plugin-standard-compaction:lash-plugin-standard-compaction",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lash_vm_runtime": "//crates/lash-vm-runtime:lash-vm-runtime",
            "serde_json": "//third-party/rust:p0314",
            "sqlx": "//third-party/rust:p0334",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372",
            "tokio_util": "//third-party/rust:p0379"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0044",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "lash-internal-http-transport": {
        "build": {},
        "dev": {
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "bytes": "//third-party/rust:p0036",
            "httpdate": "//third-party/rust:p0151",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "reqwest": "//third-party/rust:p0278",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "lash-internal-llm-tools": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-internal-llm-transport": {
        "build": {},
        "dev": {
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "proptest": "//third-party/rust:p0249",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "bytes": "//third-party/rust:p0036",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_http_transport": "//crates/lash-http-transport:lash-http-transport",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "proptest": "//third-party/rust:p0249",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "lash-internal-plugin-mcp": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372",
            "tracing_subscriber": "//third-party/rust:p0392"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0024",
            "blake3": "//third-party/rust:p0029",
            "fastrand": "//third-party/rust:p0107",
            "futures_util": "//third-party/rust:p0127",
            "http": "//third-party/rust:p0147",
            "jsonschema": "//third-party/rust:p0184",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "lash_vm_runtime": "//crates/lash-vm-runtime:lash-vm-runtime",
            "libc": "//third-party/rust:p0188",
            "rmcp": "//third-party/rust:p0280",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tokio_util": "//third-party/rust:p0379",
            "tracing": "//third-party/rust:p0388"
        }
    },
    "lash-internal-plugin-process-controls": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-internal-plugin-standard-compaction": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-internal-postgres-store": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_runtime": "//crates/lash-vm-runtime:lash-vm-runtime",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372",
            "tracing_subscriber": "//third-party/rust:p0392"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "futures_util": "//third-party/rust:p0127",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_store_sql": "//crates/lash-store-sql:lash-store-sql",
            "rmp_serde": "//third-party/rust:p0283",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sqlx": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0372",
            "tracing": "//third-party/rust:p0388",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-internal-postgres-workers": {
        "build": {},
        "dev": {
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "rusqlite": "//third-party/rust:p0284",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sqlx": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "lash-internal-protocol-rlm": {
        "build": {
            "syn": "//third-party/rust:p0358"
        },
        "dev": {
            "insta": "//third-party/rust:p0170",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "tempfile": "//third-party/rust:p0363"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_render": "//crates/lash-render:lash-render",
            "lash_rlm_types": "//crates/lash-rlm-types:lash-rlm-types",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lash_vm_runtime": "//crates/lash-vm-runtime:lash-vm-runtime",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "rmp_serde": "//third-party/rust:p0283",
            "serde": "//third-party/rust:p0308",
            "serde_bytes": "//third-party/rust:p0309",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "lash-internal-protocol-standard": {
        "build": {},
        "dev": {
            "insta": "//third-party/rust:p0170",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "mutants": "//third-party/rust:p0206",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_render": "//crates/lash-render:lash-render",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-internal-provider-anthropic": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0024",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "reqwest": "//third-party/rust:p0278",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-internal-provider-google": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_provider_google": "//crates/lash-provider-google:lash-provider-google",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0024",
            "chrono": "//third-party/rust:p0044",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "reqwest": "//third-party/rust:p0278",
            "serde_json": "//third-party/rust:p0314",
            "tokio": "//third-party/rust:p0372",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-internal-provider-openai": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0024",
            "bytes": "//third-party/rust:p0036",
            "futures_util": "//third-party/rust:p0127",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "reqwest": "//third-party/rust:p0278",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "tokio": "//third-party/rust:p0372",
            "tokio_tungstenite": "//third-party/rust:p0378",
            "tracing": "//third-party/rust:p0388"
        }
    },
    "lash-internal-render": {
        "build": {},
        "dev": {},
        "normal": {
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-internal-rlm-types": {
        "build": {},
        "dev": {},
        "normal": {
            "lash_render": "//crates/lash-render:lash-render",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-internal-s3-store": {
        "build": {},
        "dev": {
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "futures_util": "//third-party/rust:p0127",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "object_store": "//third-party/rust:p0218",
            "url": "//third-party/rust:p0408"
        }
    },
    "lash-internal-sansio": {
        "build": {},
        "dev": {
            "proptest": "//third-party/rust:p0249"
        },
        "normal": {
            "blake3": "//third-party/rust:p0029",
            "jsonschema": "//third-party/rust:p0184",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-internal-sqlite-store": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_runtime": "//crates/lash-vm-runtime:lash-vm-runtime",
            "rusqlite": "//third-party/rust:p0284",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "flate2": "//third-party/rust:p0109",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_store_sql": "//crates/lash-store-sql:lash-store-sql",
            "rmp_serde": "//third-party/rust:p0283",
            "rusqlite": "//third-party/rust:p0284",
            "serde": "//third-party/rust:p0308",
            "serde_bytes": "//third-party/rust:p0309",
            "serde_json": "//third-party/rust:p0314",
            "tokio": "//third-party/rust:p0372",
            "tokio_rusqlite": "//third-party/rust:p0375",
            "tracing": "//third-party/rust:p0388",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-internal-store-sql": {
        "build": {},
        "dev": {},
        "normal": {}
    },
    "lash-internal-tool-support": {
        "build": {},
        "dev": {},
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-internal-trace": {
        "build": {},
        "dev": {
            "jsonschema": "//third-party/rust:p0184",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "opentelemetry_sdk": "//third-party/rust:p0224"
        },
        "normal": {
            "chrono": "//third-party/rust:p0044",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "opentelemetry": "//third-party/rust:p0223",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "strum": "//third-party/rust:p0347",
            "thiserror": "//third-party/rust:p0365",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-internal-typescript": {
        "build": {},
        "dev": {
            "futures": "//third-party/rust:p0118",
            "jsonschema": "//third-party/rust:p0184",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "serde": "//third-party/rust:p0308",
            "serde_yaml": "//third-party/rust:p0318",
            "swc_common": "//third-party/rust:p0352",
            "swc_ecma_ast": "//third-party/rust:p0353",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "ryu_js": "//third-party/rust:p0297",
            "serde_json": "//third-party/rust:p0314",
            "swc_common": "//third-party/rust:p0352",
            "swc_ecma_ast": "//third-party/rust:p0353",
            "swc_ecma_parser": "//third-party/rust:p0354",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-internal-vm": {
        "build": {},
        "dev": {
            "criterion": "//third-party/rust:p0069",
            "futures": "//third-party/rust:p0118",
            "jsonschema": "//third-party/rust:p0184",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "proptest": "//third-party/rust:p0249",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "compact_str": "//third-party/rust:p0057",
            "futures_executor": "//third-party/rust:p0121",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_regress": "//crates/lash-regress:lash-regress",
            "lash_render": "//crates/lash-render:lash-render",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "num_bigint": "//third-party/rust:p0211",
            "num_traits": "//third-party/rust:p0217",
            "rmp_serde": "//third-party/rust:p0283",
            "rustc_hash": "//third-party/rust:p0285",
            "ryu_js": "//third-party/rust:p0297",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_bytes": "//third-party/rust:p0309",
            "serde_ignored": "//third-party/rust:p0313",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "smallvec": "//third-party/rust:p0331",
            "thiserror": "//third-party/rust:p0365",
            "url": "//third-party/rust:p0408"
        }
    },
    "lash-internal-vm-broker": {
        "build": {},
        "dev": {
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_durable_test": "//crates/lash-durable-test:lash-durable-test",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "blake3": "//third-party/rust:p0029",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_kernel_doc": "//crates/lash-kernel-doc:lash-kernel-doc",
            "lash_kernel_vm": "//crates/lash-kernel-vm:lash-kernel-vm",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "rmp_serde": "//third-party/rust:p0283",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tokio_util": "//third-party/rust:p0379",
            "tracing": "//third-party/rust:p0388"
        }
    },
    "lash-internal-vm-client": {
        "build": {},
        "dev": {
            "quote": "//third-party/rust:p0255",
            "syn": "//third-party/rust:p0358"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "libc": "//third-party/rust:p0188",
            "rmp_serde": "//third-party/rust:p0283",
            "serde": "//third-party/rust:p0308",
            "serde_bytes": "//third-party/rust:p0309",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "lash-internal-vm-protocol": {
        "build": {},
        "dev": {
            "serde_json": "//third-party/rust:p0314"
        },
        "normal": {
            "base64": "//third-party/rust:p0024",
            "blake3": "//third-party/rust:p0029",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "rmp_serde": "//third-party/rust:p0283",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_bytes": "//third-party/rust:p0309",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-internal-vm-runtime": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "tempfile": "//third-party/rust:p0363"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0044",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "rmp_serde": "//third-party/rust:p0283",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tokio_util": "//third-party/rust:p0379",
            "tracing": "//third-party/rust:p0388"
        }
    },
    "lash-internal-vm-worker": {
        "build": {},
        "dev": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "blake3": "//third-party/rust:p0029",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "libc": "//third-party/rust:p0188",
            "rmp_serde": "//third-party/rust:p0283",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-kernel-check": {
        "build": {},
        "dev": {},
        "normal": {
            "lash_kernel_doc": "//crates/lash-kernel-doc:lash-kernel-doc",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-kernel-dialect": {
        "build": {},
        "dev": {},
        "normal": {
            "lash_kernel_doc": "//crates/lash-kernel-doc:lash-kernel-doc",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-kernel-doc": {
        "build": {},
        "dev": {},
        "normal": {
            "num_bigint": "//third-party/rust:p0211",
            "num_traits": "//third-party/rust:p0217",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-kernel-edit": {
        "build": {},
        "dev": {
            "lash_kernel_vm": "//crates/lash-kernel-vm:lash-kernel-vm"
        },
        "normal": {
            "lash_kernel_check": "//crates/lash-kernel-check:lash-kernel-check",
            "lash_kernel_doc": "//crates/lash-kernel-doc:lash-kernel-doc",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-kernel-lib": {
        "build": {},
        "dev": {
            "lash_kernel_vm": "//crates/lash-kernel-vm:lash-kernel-vm"
        },
        "normal": {
            "lash_kernel_doc": "//crates/lash-kernel-doc:lash-kernel-doc",
            "libm": "//third-party/rust:p0189",
            "num_bigint": "//third-party/rust:p0211",
            "num_traits": "//third-party/rust:p0217",
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "lash-kernel-state": {
        "build": {},
        "dev": {},
        "normal": {
            "lash_kernel_doc": "//crates/lash-kernel-doc:lash-kernel-doc",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-kernel-vm": {
        "build": {},
        "dev": {
            "serde_json": "//third-party/rust:p0314"
        },
        "normal": {
            "lash_kernel_doc": "//crates/lash-kernel-doc:lash-kernel-doc",
            "lash_kernel_state": "//crates/lash-kernel-state:lash-kernel-state",
            "num_bigint": "//third-party/rust:p0211",
            "num_traits": "//third-party/rust:p0217",
            "thiserror": "//third-party/rust:p0365"
        }
    },
    "lash-perf": {
        "build": {},
        "dev": {
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0044",
            "clap": "//third-party/rust:p0049",
            "crc32fast": "//third-party/rust:p0068",
            "delegation": "//examples/delegation:delegation",
            "flate2": "//third-party/rust:p0109",
            "futures_util": "//third-party/rust:p0127",
            "jsonschema": "//third-party/rust:p0184",
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_http_transport": "//crates/lash-http-transport:lash-http-transport",
            "lash_llm_tools": "//crates/lash-llm-tools:lash-llm-tools",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_plugin_process_controls": "//crates/lash-plugin-process-controls:lash-plugin-process-controls",
            "lash_plugin_standard_compaction": "//crates/lash-plugin-standard-compaction:lash-plugin-standard-compaction",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_rlm_types": "//crates/lash-rlm-types:lash-rlm-types",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lash_vm_runtime": "//crates/lash-vm-runtime:lash-vm-runtime",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "libc": "//third-party/rust:p0188",
            "opentelemetry_sdk": "//third-party/rust:p0224",
            "rand_chacha": "//third-party/rust:p0262",
            "rmp_serde": "//third-party/rust:p0283",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "sqlx": "//third-party/rust:p0334",
            "stats_alloc": "//third-party/rust:p0342",
            "tokio": "//third-party/rust:p0372",
            "tokio_metrics": "//third-party/rust:p0374",
            "tokio_util": "//third-party/rust:p0379",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-regress": {
        "build": {},
        "dev": {},
        "normal": {
            "hashbrown": "//third-party/rust:p0137",
            "memchr": "//third-party/rust:p0201"
        }
    },
    "lash-runtime": {
        "build": {},
        "dev": {
            "insta": "//third-party/rust:p0170",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "opentelemetry_sdk": "//third-party/rust:p0224",
            "rmp_serde": "//third-party/rust:p0283",
            "rusqlite": "//third-party/rust:p0284",
            "serde_bytes": "//third-party/rust:p0309",
            "sqlx": "//third-party/rust:p0334",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372",
            "tracing_subscriber": "//third-party/rust:p0392",
            "trybuild": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "futures_util": "//third-party/rust:p0127",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_http_transport": "//crates/lash-http-transport:lash-http-transport",
            "lash_llm_tools": "//crates/lash-llm-tools:lash-llm-tools",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_plugin_mcp": "//crates/lash-plugin-mcp:lash-plugin-mcp",
            "lash_plugin_process_controls": "//crates/lash-plugin-process-controls:lash-plugin-process-controls",
            "lash_plugin_standard_compaction": "//crates/lash-plugin-standard-compaction:lash-plugin-standard-compaction",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_protocol_standard": "//crates/lash-protocol-standard:lash-protocol-standard",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_render": "//crates/lash-render:lash-render",
            "lash_rlm_types": "//crates/lash-rlm-types:lash-rlm-types",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_runtime": "//crates/lash-vm-runtime:lash-vm-runtime",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sqlx": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tokio_util": "//third-party/rust:p0379",
            "tracing": "//third-party/rust:p0388",
            "uuid": "//third-party/rust:p0411"
        }
    },
    "lash-sim": {
        "build": {},
        "dev": {
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "lash_provider_google": "//crates/lash-provider-google:lash-provider-google",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_s3_store": "//crates/lash-s3-store:lash-s3-store",
            "rmp_serde": "//third-party/rust:p0283",
            "rusqlite": "//third-party/rust:p0284"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "bytes": "//third-party/rust:p0036",
            "chrono": "//third-party/rust:p0044",
            "delegation": "//examples/delegation:delegation",
            "fastrand": "//third-party/rust:p0107",
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_durable": "//crates/lash-durable:lash-durable",
            "lash_durable_test": "//crates/lash-durable-test:lash-durable-test",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_plugin_process_controls": "//crates/lash-plugin-process-controls:lash-plugin-process-controls",
            "lash_plugin_standard_compaction": "//crates/lash-plugin-standard-compaction:lash-plugin-standard-compaction",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_protocol_standard": "//crates/lash-protocol-standard:lash-protocol-standard",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "lash_provider_google": "//crates/lash-provider-google:lash-provider-google",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_rlm_types": "//crates/lash-rlm-types:lash-rlm-types",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm": "//crates/lash-vm:lash-vm",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_runtime": "//crates/lash-vm-runtime:lash-vm-runtime",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "sqlx": "//third-party/rust:p0334",
            "tempfile": "//third-party/rust:p0363",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "lashctl": {
        "build": {},
        "dev": {
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "sqlx": "//third-party/rust:p0334",
            "uuid": "//third-party/rust:p0411"
        },
        "normal": {
            "lash": "//crates/lash:lash",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "rlm-smoke-host": {
        "build": {},
        "dev": {
            "tempfile": "//third-party/rust:p0363"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "async_trait": "//third-party/rust:p0015",
            "clap": "//third-party/rust:p0049",
            "lash": "//crates/lash:lash",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "tokio": "//third-party/rust:p0372"
        }
    },
    "toolbench": {
        "build": {},
        "dev": {},
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "axum": "//third-party/rust:p0021",
            "clap": "//third-party/rust:p0049",
            "dotenvy": "//third-party/rust:p0094",
            "futures_util": "//third-party/rust:p0127",
            "lash": "//crates/lash:lash",
            "reqwest": "//third-party/rust:p0278",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "sha2": "//third-party/rust:p0320",
            "tokio": "//third-party/rust:p0372",
            "tracing": "//third-party/rust:p0388",
            "tracing_subscriber": "//third-party/rust:p0392"
        }
    },
    "transcript-contract": {
        "build": {},
        "dev": {
            "insta": "//third-party/rust:p0170"
        },
        "normal": {
            "serde_json": "//third-party/rust:p0314"
        }
    },
    "workflow-graph-roundtrip": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "axum": "//third-party/rust:p0021",
            "chrono": "//third-party/rust:p0044",
            "lash": "//crates/lash:lash",
            "reqwest": "//third-party/rust:p0278",
            "schemars": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0308",
            "serde_json": "//third-party/rust:p0314",
            "thiserror": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0372",
            "tokio_stream": "//third-party/rust:p0377",
            "uuid": "//third-party/rust:p0411"
        }
    }
}
