# @generated by tools/buck2/sync.py; do not edit.
PACKAGE_DEPS = {
    "agent-workbench": {
        "build": {},
        "dev": {
            "http": "//third-party/rust:p0151",
            "http_body_util": "//third-party/rust:p0153",
            "lash": "//crates/lash:lash",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sim": "//crates/lash-sim:lash-sim",
            "sqlx": "//third-party/rust:p0357",
            "tempfile": "//third-party/rust:p0386"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "async_trait": "//third-party/rust:p0015",
            "axum": "//third-party/rust:p0021",
            "base64": "//third-party/rust:p0023",
            "bytes": "//third-party/rust:p0038",
            "chrono": "//third-party/rust:p0047",
            "chrono_tz": "//third-party/rust:p0048",
            "croner": "//third-party/rust:p0075",
            "dotenvy": "//third-party/rust:p0098",
            "futures_util": "//third-party/rust:p0131",
            "lash": "//crates/lash:lash",
            "percent_encoding": "//third-party/rust:p0239",
            "reqwest": "//third-party/rust:p0293",
            "rusqlite": "//third-party/rust:p0301",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tokio_stream": "//third-party/rust:p0399",
            "tracing_subscriber": "//third-party/rust:p0414",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "e2e-consumer": {
        "build": {},
        "dev": {},
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "axum": "//third-party/rust:p0021",
            "lash": "//crates/lash:lash",
            "opentelemetry_sdk": "//third-party/rust:p0233",
            "reqwest": "//third-party/rust:p0293",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "integrator-contract": {
        "build": {},
        "dev": {},
        "normal": {
            "lash": "//crates/lash:lash"
        }
    },
    "lash-internal-conformance": {
        "build": {},
        "dev": {
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "tempfile": "//third-party/rust:p0386"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0047",
            "futures_util": "//third-party/rust:p0131",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_plugin_standard_compaction": "//crates/lash-plugin-standard-compaction:lash-plugin-standard-compaction",
            "lash_remote_protocol": "//crates/lash-remote-protocol:lash-remote-protocol",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lashlang": "//crates/lashlang:lashlang",
            "pretty_assertions": "//third-party/rust:p0256",
            "proptest": "//third-party/rust:p0260",
            "rmp_serde": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-core": {
        "build": {},
        "dev": {
            "chrono": "//third-party/rust:p0047",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "opentelemetry_sdk": "//third-party/rust:p0233",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395",
            "tracing_subscriber": "//third-party/rust:p0414"
        },
        "normal": {
            "arc_swap": "//third-party/rust:p0012",
            "async_trait": "//third-party/rust:p0015",
            "futures_util": "//third-party/rust:p0131",
            "lash_core_effect": "//crates/lash-core-effect:lash-core-effect",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_llm": "//crates/lash-core-llm:lash-core-llm",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "libc": "//third-party/rust:p0198",
            "rmp_serde": "//third-party/rust:p0300",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-core-effect": {
        "build": {},
        "dev": {
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "tokio_util": "//third-party/rust:p0401"
        }
    },
    "lash-internal-core-execution": {
        "build": {},
        "dev": {
            "insta": "//third-party/rust:p0174",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "proptest": "//third-party/rust:p0260",
            "syn": "//third-party/rust:p0381",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0047",
            "futures_util": "//third-party/rust:p0131",
            "lash_core_effect": "//crates/lash-core-effect:lash-core-effect",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_llm": "//crates/lash-core-llm:lash-core-llm",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "rmp_serde": "//third-party/rust:p0300",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410",
            "tracing_subscriber": "//third-party/rust:p0414",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-core-ids": {
        "build": {},
        "dev": {},
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0047",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "tokio": "//third-party/rust:p0395",
            "tracing": "//third-party/rust:p0410",
            "tracing_subscriber": "//third-party/rust:p0414"
        }
    },
    "lash-internal-core-llm": {
        "build": {},
        "dev": {
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0047",
            "futures_util": "//third-party/rust:p0131",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_http_transport": "//crates/lash-http-transport:lash-http-transport",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tracing": "//third-party/rust:p0410"
        }
    },
    "lash-internal-core-store": {
        "build": {},
        "dev": {
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_llm": "//crates/lash-core-llm:lash-core-llm",
            "lash_render": "//crates/lash-render:lash-render",
            "proptest": "//third-party/rust:p0260",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "lash_core_llm": "//crates/lash-core-llm:lash-core-llm",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "rmp_serde": "//third-party/rust:p0300",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_bytes": "//third-party/rust:p0328",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tracing": "//third-party/rust:p0410",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-core-worker": {
        "build": {},
        "dev": {},
        "normal": {
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_ids": "//crates/lash-core-ids:lash-core-ids",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410"
        }
    },
    "lash-internal-http-transport": {
        "build": {},
        "dev": {
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "bytes": "//third-party/rust:p0038",
            "httpdate": "//third-party/rust:p0155",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "reqwest": "//third-party/rust:p0293",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "lash-internal-lashlang": {
        "build": {},
        "dev": {
            "criterion": "//third-party/rust:p0073",
            "futures": "//third-party/rust:p0122",
            "jsonschema": "//third-party/rust:p0193",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "proptest": "//third-party/rust:p0260",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "compact_str": "//third-party/rust:p0060",
            "futures_executor": "//third-party/rust:p0125",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_regress": "//crates/lash-regress:lash-regress",
            "lash_render": "//crates/lash-render:lash-render",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "num_bigint": "//third-party/rust:p0220",
            "num_traits": "//third-party/rust:p0226",
            "rmp_serde": "//third-party/rust:p0300",
            "rustc_hash": "//third-party/rust:p0302",
            "ryu_js": "//third-party/rust:p0314",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_bytes": "//third-party/rust:p0328",
            "serde_ignored": "//third-party/rust:p0333",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "smallvec": "//third-party/rust:p0354",
            "thiserror": "//third-party/rust:p0388",
            "url": "//third-party/rust:p0433"
        }
    },
    "lash-internal-lashlang-runtime": {
        "build": {},
        "dev": {
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lashlang": "//crates/lashlang:lashlang",
            "tempfile": "//third-party/rust:p0386"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "chrono": "//third-party/rust:p0047",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_remote_protocol": "//crates/lash-remote-protocol:lash-remote-protocol",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "lashlang": "//crates/lashlang:lashlang",
            "rmp_serde": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410"
        }
    },
    "lash-internal-llm-tools": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "lash-internal-llm-transport": {
        "build": {},
        "dev": {
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "proptest": "//third-party/rust:p0260",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "bytes": "//third-party/rust:p0038",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_http_transport": "//crates/lash-http-transport:lash-http-transport",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "proptest": "//third-party/rust:p0260",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "lash-internal-plugin-mcp": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lashlang": "//crates/lashlang:lashlang",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395",
            "tracing_subscriber": "//third-party/rust:p0414"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0023",
            "blake3": "//third-party/rust:p0030",
            "fastrand": "//third-party/rust:p0111",
            "futures_util": "//third-party/rust:p0131",
            "http": "//third-party/rust:p0151",
            "jsonschema": "//third-party/rust:p0193",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "libc": "//third-party/rust:p0198",
            "rmcp": "//third-party/rust:p0298",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410"
        }
    },
    "lash-internal-plugin-process-controls": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "lash-internal-plugin-standard-compaction": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "lash-internal-postgres-store": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lashlang": "//crates/lashlang:lashlang",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395",
            "tracing_subscriber": "//third-party/rust:p0414"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_store_sql": "//crates/lash-store-sql:lash-store-sql",
            "rmp_serde": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sqlx": "//third-party/rust:p0357",
            "tokio": "//third-party/rust:p0395",
            "tracing": "//third-party/rust:p0410",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-protocol-rlm": {
        "build": {
            "syn": "//third-party/rust:p0381"
        },
        "dev": {
            "insta": "//third-party/rust:p0174",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_plugin_process_controls": "//crates/lash-plugin-process-controls:lash-plugin-process-controls",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_remote_protocol": "//crates/lash-remote-protocol:lash-remote-protocol",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lashlang": "//crates/lashlang:lashlang",
            "tempfile": "//third-party/rust:p0386",
            "tokio_util": "//third-party/rust:p0401"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_render": "//crates/lash-render:lash-render",
            "lash_rlm_types": "//crates/lash-rlm-types:lash-rlm-types",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "lashlang": "//crates/lashlang:lashlang",
            "rmp_serde": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0327",
            "serde_bytes": "//third-party/rust:p0328",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "lash-internal-protocol-standard": {
        "build": {},
        "dev": {
            "insta": "//third-party/rust:p0174",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "mutants": "//third-party/rust:p0215",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_render": "//crates/lash-render:lash-render",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "lash-internal-provider-anthropic": {
        "build": {},
        "dev": {
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0023",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "reqwest": "//third-party/rust:p0293",
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "lash-internal-provider-auth": {
        "build": {},
        "dev": {
            "chrono": "//third-party/rust:p0047",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0023",
            "form_urlencoded": "//third-party/rust:p0118",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "reqwest": "//third-party/rust:p0293",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-provider-google": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_provider_google": "//crates/lash-provider-google:lash-provider-google",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0023",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_provider_auth": "//crates/lash-provider-auth:lash-provider-auth",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "reqwest": "//third-party/rust:p0293",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0395",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-provider-openai": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0023",
            "bytes": "//third-party/rust:p0038",
            "futures_util": "//third-party/rust:p0131",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_provider_auth": "//crates/lash-provider-auth:lash-provider-auth",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "reqwest": "//third-party/rust:p0293",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0395",
            "tokio_tungstenite": "//third-party/rust:p0400",
            "tracing": "//third-party/rust:p0410"
        }
    },
    "lash-internal-remote-protocol": {
        "build": {},
        "dev": {
            "jsonschema": "//third-party/rust:p0193",
            "lash_core": "//crates/lash-core:lash-core",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "base64": "//third-party/rust:p0023",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388"
        }
    },
    "lash-internal-render": {
        "build": {},
        "dev": {},
        "normal": {
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "lash-internal-restate": {
        "build": {},
        "dev": {
            "chrono": "//third-party/rust:p0047",
            "http": "//third-party/rust:p0151",
            "http_body": "//third-party/rust:p0152",
            "http_body_util": "//third-party/rust:p0153",
            "lash": "//crates/lash:lash",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_llm_tools": "//crates/lash-llm-tools:lash-llm-tools",
            "lash_plugin_process_controls": "//crates/lash-plugin-process-controls:lash-plugin-process-controls",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_protocol_standard": "//crates/lash-protocol-standard:lash-protocol-standard",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_subagents": "//crates/lash-subagents:lash-subagents",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lashlang": "//crates/lashlang:lashlang",
            "opentelemetry_sdk": "//third-party/rust:p0233",
            "reqwest": "//third-party/rust:p0293",
            "rusqlite": "//third-party/rust:p0301",
            "sqlx": "//third-party/rust:p0357",
            "tempfile": "//third-party/rust:p0386"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "bytes": "//third-party/rust:p0038",
            "hyper": "//third-party/rust:p0158",
            "hyper_util": "//third-party/rust:p0160",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_http_transport": "//crates/lash-http-transport:lash-http-transport",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "restate_sdk": "//third-party/rust:p0294",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-restate-test": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lashlang": "//crates/lashlang:lashlang",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0023",
            "bytes": "//third-party/rust:p0038",
            "chrono": "//third-party/rust:p0047",
            "http": "//third-party/rust:p0151",
            "http_body": "//third-party/rust:p0152",
            "http_body_util": "//third-party/rust:p0153",
            "hyper": "//third-party/rust:p0158",
            "hyper_util": "//third-party/rust:p0160",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_http_transport": "//crates/lash-http-transport:lash-http-transport",
            "lash_restate": "//crates/lash-restate:lash-restate",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "prost": "//third-party/rust:p0261",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "lash-internal-rlm-types": {
        "build": {},
        "dev": {},
        "normal": {
            "lash_render": "//crates/lash-render:lash-render",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "lash-internal-s3-store": {
        "build": {},
        "dev": {
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "futures_util": "//third-party/rust:p0131",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "object_store": "//third-party/rust:p0227",
            "url": "//third-party/rust:p0433"
        }
    },
    "lash-internal-sansio": {
        "build": {},
        "dev": {
            "proptest": "//third-party/rust:p0260"
        },
        "normal": {
            "blake3": "//third-party/rust:p0030",
            "jsonschema": "//third-party/rust:p0193",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388"
        }
    },
    "lash-internal-sqlite-store": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lashlang": "//crates/lashlang:lashlang",
            "rusqlite": "//third-party/rust:p0301",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395",
            "tracing_subscriber": "//third-party/rust:p0414"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "flate2": "//third-party/rust:p0113",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_store_sql": "//crates/lash-store-sql:lash-store-sql",
            "rmp_serde": "//third-party/rust:p0300",
            "rusqlite": "//third-party/rust:p0301",
            "serde": "//third-party/rust:p0327",
            "serde_bytes": "//third-party/rust:p0328",
            "serde_json": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0395",
            "tokio_rusqlite": "//third-party/rust:p0397",
            "tracing": "//third-party/rust:p0410",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-store-sql": {
        "build": {},
        "dev": {},
        "normal": {}
    },
    "lash-internal-subagents": {
        "build": {},
        "dev": {
            "jsonschema": "//third-party/rust:p0193",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_plugin_process_controls": "//crates/lash-plugin-process-controls:lash-plugin-process-controls",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "tokio_util": "//third-party/rust:p0401"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_rlm_types": "//crates/lash-rlm-types:lash-rlm-types",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "lash-internal-tool-support": {
        "build": {},
        "dev": {},
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core": "//crates/lash-core:lash-core",
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "lash-internal-trace": {
        "build": {},
        "dev": {
            "jsonschema": "//third-party/rust:p0193",
            "opentelemetry_sdk": "//third-party/rust:p0233"
        },
        "normal": {
            "chrono": "//third-party/rust:p0047",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "opentelemetry": "//third-party/rust:p0232",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "thiserror": "//third-party/rust:p0388",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-typescript": {
        "build": {},
        "dev": {
            "futures": "//third-party/rust:p0122",
            "jsonschema": "//third-party/rust:p0193",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lashlang": "//crates/lashlang:lashlang",
            "serde": "//third-party/rust:p0327",
            "serde_yaml": "//third-party/rust:p0339",
            "swc_common": "//third-party/rust:p0375",
            "swc_ecma_ast": "//third-party/rust:p0376",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lashlang": "//crates/lashlang:lashlang",
            "ryu_js": "//third-party/rust:p0314",
            "serde_json": "//third-party/rust:p0334",
            "swc_common": "//third-party/rust:p0375",
            "swc_ecma_ast": "//third-party/rust:p0376",
            "swc_ecma_parser": "//third-party/rust:p0377",
            "thiserror": "//third-party/rust:p0388"
        }
    },
    "lash-internal-vm-broker": {
        "build": {},
        "dev": {
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "blake3": "//third-party/rust:p0030",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lashlang": "//crates/lashlang:lashlang",
            "rmp_serde": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410"
        }
    },
    "lash-internal-vm-client": {
        "build": {},
        "dev": {
            "quote": "//third-party/rust:p0268",
            "syn": "//third-party/rust:p0381"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lashlang": "//crates/lashlang:lashlang",
            "libc": "//third-party/rust:p0198",
            "rmp_serde": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0327",
            "serde_bytes": "//third-party/rust:p0328",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-internal-vm-protocol": {
        "build": {},
        "dev": {
            "serde_json": "//third-party/rust:p0334"
        },
        "normal": {
            "base64": "//third-party/rust:p0023",
            "blake3": "//third-party/rust:p0030",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "rmp_serde": "//third-party/rust:p0300",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_bytes": "//third-party/rust:p0328",
            "thiserror": "//third-party/rust:p0388"
        }
    },
    "lash-internal-vm-worker": {
        "build": {},
        "dev": {
            "async_trait": "//third-party/rust:p0015",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_vm_broker": "//crates/lash-vm-broker:lash-vm-broker",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "lashlang": "//crates/lashlang:lashlang",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401"
        },
        "normal": {
            "blake3": "//third-party/rust:p0030",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lashlang": "//crates/lashlang:lashlang",
            "libc": "//third-party/rust:p0198",
            "rmp_serde": "//third-party/rust:p0300",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "lash-perf": {
        "build": {},
        "dev": {
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "async_trait": "//third-party/rust:p0015",
            "base64": "//third-party/rust:p0023",
            "chrono": "//third-party/rust:p0047",
            "clap": "//third-party/rust:p0052",
            "crc32fast": "//third-party/rust:p0072",
            "flate2": "//third-party/rust:p0113",
            "futures_util": "//third-party/rust:p0131",
            "jsonschema": "//third-party/rust:p0193",
            "lash": "//crates/lash:lash",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_llm_tools": "//crates/lash-llm-tools:lash-llm-tools",
            "lash_plugin_process_controls": "//crates/lash-plugin-process-controls:lash-plugin-process-controls",
            "lash_plugin_standard_compaction": "//crates/lash-plugin-standard-compaction:lash-plugin-standard-compaction",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_restate": "//crates/lash-restate:lash-restate",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_rlm_types": "//crates/lash-rlm-types:lash-rlm-types",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_subagents": "//crates/lash-subagents:lash-subagents",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_protocol": "//crates/lash-vm-protocol:lash-vm-protocol",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "lashlang": "//crates/lashlang:lashlang",
            "libc": "//third-party/rust:p0198",
            "rand_chacha": "//third-party/rust:p0275",
            "reqwest": "//third-party/rust:p0293",
            "rmp_serde": "//third-party/rust:p0300",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "stats_alloc": "//third-party/rust:p0365",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-regress": {
        "build": {},
        "dev": {},
        "normal": {
            "hashbrown": "//third-party/rust:p0141",
            "memchr": "//third-party/rust:p0210"
        }
    },
    "lash-restate-postgres-workers-e2e": {
        "build": {},
        "dev": {
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "async_trait": "//third-party/rust:p0015",
            "axum": "//third-party/rust:p0021",
            "chrono": "//third-party/rust:p0047",
            "lash": "//crates/lash:lash",
            "lash_perf": "//crates/lash-perf:lash-perf",
            "lash_plugin_standard_compaction": "//crates/lash-plugin-standard-compaction:lash-plugin-standard-compaction",
            "reqwest": "//third-party/rust:p0293",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "sqlx": "//third-party/rust:p0357",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410",
            "tracing_subscriber": "//third-party/rust:p0414",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-runtime": {
        "build": {},
        "dev": {
            "insta": "//third-party/rust:p0174",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_plugin_standard_compaction": "//crates/lash-plugin-standard-compaction:lash-plugin-standard-compaction",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "lash_restate": "//crates/lash-restate:lash-restate",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_subagents": "//crates/lash-subagents:lash-subagents",
            "lashlang": "//crates/lashlang:lashlang",
            "rmp_serde": "//third-party/rust:p0300",
            "rusqlite": "//third-party/rust:p0301",
            "serde_bytes": "//third-party/rust:p0328",
            "sqlx": "//third-party/rust:p0357",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395",
            "tracing_subscriber": "//third-party/rust:p0414",
            "trybuild": "//third-party/rust:p0417"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "futures_util": "//third-party/rust:p0131",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_core_worker": "//crates/lash-core-worker:lash-core-worker",
            "lash_http_transport": "//crates/lash-http-transport:lash-http-transport",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_llm_tools": "//crates/lash-llm-tools:lash-llm-tools",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_plugin_mcp": "//crates/lash-plugin-mcp:lash-plugin-mcp",
            "lash_plugin_process_controls": "//crates/lash-plugin-process-controls:lash-plugin-process-controls",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_protocol_standard": "//crates/lash-protocol-standard:lash-protocol-standard",
            "lash_provider_auth": "//crates/lash-provider-auth:lash-provider-auth",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_remote_protocol": "//crates/lash-remote-protocol:lash-remote-protocol",
            "lash_render": "//crates/lash-render:lash-render",
            "lash_restate": "//crates/lash-restate:lash-restate",
            "lash_rlm_types": "//crates/lash-rlm-types:lash-rlm-types",
            "lash_s3_store": "//crates/lash-s3-store:lash-s3-store",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_subagents": "//crates/lash-subagents:lash-subagents",
            "lash_tool_support": "//crates/lash-tool-support:lash-tool-support",
            "lash_trace": "//crates/lash-trace:lash-trace",
            "lash_typescript": "//crates/lash-typescript:lash-typescript",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lash_vm_worker": "//crates/lash-vm-worker:lash-vm-worker",
            "lashlang": "//crates/lashlang:lashlang",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tokio_util": "//third-party/rust:p0401",
            "tracing": "//third-party/rust:p0410",
            "uuid": "//third-party/rust:p0436"
        }
    },
    "lash-sim": {
        "build": {},
        "dev": {
            "insta": "//third-party/rust:p0174",
            "lash_conformance": "//crates/lash-conformance:lash-conformance",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "lash_provider_auth": "//crates/lash-provider-auth:lash-provider-auth",
            "lash_provider_google": "//crates/lash-provider-google:lash-provider-google",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_s3_store": "//crates/lash-s3-store:lash-s3-store",
            "rmp_serde": "//third-party/rust:p0300",
            "rusqlite": "//third-party/rust:p0301",
            "sqlx": "//third-party/rust:p0357"
        },
        "normal": {
            "async_trait": "//third-party/rust:p0015",
            "bytes": "//third-party/rust:p0038",
            "chrono": "//third-party/rust:p0047",
            "fastrand": "//third-party/rust:p0111",
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_llm_transport": "//crates/lash-llm-transport:lash-llm-transport",
            "lash_plugin_process_controls": "//crates/lash-plugin-process-controls:lash-plugin-process-controls",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_protocol_rlm": "//crates/lash-protocol-rlm:lash-protocol-rlm",
            "lash_protocol_standard": "//crates/lash-protocol-standard:lash-protocol-standard",
            "lash_provider_anthropic": "//crates/lash-provider-anthropic:lash-provider-anthropic",
            "lash_provider_google": "//crates/lash-provider-google:lash-provider-google",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_restate": "//crates/lash-restate:lash-restate",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_rlm_types": "//crates/lash-rlm-types:lash-rlm-types",
            "lash_sansio": "//crates/lash-sansio:lash-sansio",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "lash_subagents": "//crates/lash-subagents:lash-subagents",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lashlang": "//crates/lashlang:lashlang",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "tempfile": "//third-party/rust:p0386",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "lash-upgrade-harness": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_sqlite_store": "//crates/lash-sqlite-store:lash-sqlite-store",
            "opentelemetry_sdk": "//third-party/rust:p0233",
            "rusqlite": "//third-party/rust:p0301",
            "tempfile": "//third-party/rust:p0386"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "async_trait": "//third-party/rust:p0015",
            "clap": "//third-party/rust:p0052",
            "lash": "//crates/lash:lash",
            "lash_core": "//crates/lash-core:lash-core",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_lashlang_runtime": "//crates/lash-lashlang-runtime:lash-lashlang-runtime",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_provider_openai": "//crates/lash-provider-openai:lash-provider-openai",
            "lash_remote_protocol": "//crates/lash-remote-protocol:lash-remote-protocol",
            "lash_restate": "//crates/lash-restate:lash-restate",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test",
            "lash_vm_client": "//crates/lash-vm-client:lash-vm-client",
            "lashlang": "//crates/lashlang:lashlang",
            "prost": "//third-party/rust:p0261",
            "reqwest": "//third-party/rust:p0293",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sqlx": "//third-party/rust:p0357",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "lashctl": {
        "build": {},
        "dev": {
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "sqlx": "//third-party/rust:p0357",
            "uuid": "//third-party/rust:p0436"
        },
        "normal": {
            "lash": "//crates/lash:lash",
            "lash_core_execution": "//crates/lash-core-execution:lash-core-execution",
            "lash_core_store": "//crates/lash-core-store:lash-core-store",
            "lash_postgres_store": "//crates/lash-postgres-store:lash-postgres-store",
            "lash_remote_protocol": "//crates/lash-remote-protocol:lash-remote-protocol",
            "lash_restate": "//crates/lash-restate:lash-restate",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "rlm-smoke-host": {
        "build": {},
        "dev": {
            "tempfile": "//third-party/rust:p0386"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "async_trait": "//third-party/rust:p0015",
            "clap": "//third-party/rust:p0052",
            "lash": "//crates/lash:lash",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "tokio": "//third-party/rust:p0395"
        }
    },
    "toolbench": {
        "build": {},
        "dev": {
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "axum": "//third-party/rust:p0021",
            "clap": "//third-party/rust:p0052",
            "dotenvy": "//third-party/rust:p0098",
            "futures_util": "//third-party/rust:p0131",
            "lash": "//crates/lash:lash",
            "reqwest": "//third-party/rust:p0293",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "sha2": "//third-party/rust:p0341",
            "tokio": "//third-party/rust:p0395",
            "tracing": "//third-party/rust:p0410",
            "tracing_subscriber": "//third-party/rust:p0414"
        }
    },
    "transcript-contract": {
        "build": {},
        "dev": {
            "insta": "//third-party/rust:p0174"
        },
        "normal": {
            "serde_json": "//third-party/rust:p0334"
        }
    },
    "workflow-graph-roundtrip": {
        "build": {},
        "dev": {
            "lash": "//crates/lash:lash",
            "lash_restate_test": "//crates/lash-restate-test:lash-restate-test"
        },
        "normal": {
            "anyhow": "//third-party/rust:p0011",
            "axum": "//third-party/rust:p0021",
            "lash": "//crates/lash:lash",
            "reqwest": "//third-party/rust:p0293",
            "schemars": "//third-party/rust:p0318",
            "serde": "//third-party/rust:p0327",
            "serde_json": "//third-party/rust:p0334",
            "thiserror": "//third-party/rust:p0388",
            "tokio": "//third-party/rust:p0395",
            "tokio_stream": "//third-party/rust:p0399",
            "uuid": "//third-party/rust:p0436"
        }
    }
}
