#!/usr/bin/env python3
"""Synchronize Cargo's locked Lash graph into checked-in Buck2 files.

The source Cargo manifests and lockfile remain authoritative.  This command
derives a standalone external-crate manifest for Reindeer, the generated
first-party BUCK files, dependency tables, sizing tables, and the caller
inventory.  ``--check`` computes all expected text without modifying the
checkout.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from collections import defaultdict

import bootstrap_store
import clippy_policy
import generate_model


ROOT = pathlib.Path(__file__).resolve().parents[2]
BUCK2 = ROOT / "tools/buck2"
SYNTHETIC = ROOT / "third-party"
TARGET = "x86_64-unknown-linux-gnu"
GENERATED_HEADER = "# @generated by tools/buck2/sync.py; do not edit.\n"
RECEIPT = ROOT / ".buck2/sync-receipt.json"
EXTRA_LOCKED_CRATES = {"dhat": "0.3.3"}
EXTRA_LOCKED_CLOSURE = {
    "addr2line",
    "backtrace",
    "dhat",
    "gimli",
    "mintex",
    "object",
    "rustc-demangle",
    "rustc-hash",
    "thousands",
}


def cargo() -> str:
    value = os.environ.get("KILN_REAL_CARGO")
    if not value:
        raise SystemExit("tools/buck2/sync.py: source ./env.sh first (KILN_REAL_CARGO is unset)")
    return value


def run(argv: list[str], *, cwd: pathlib.Path = ROOT) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    for key in (
        "RUSTC_WRAPPER",
        "RUSTC_WORKSPACE_WRAPPER",
        "CARGO_BUILD_RUSTC_WRAPPER",
        "CARGO_BUILD_RUSTC_WORKSPACE_WRAPPER",
    ):
        env[key] = ""
    return subprocess.run(argv, cwd=cwd, env=env, check=True, capture_output=True, text=True)


def digest_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def digest_path(path: pathlib.Path) -> str:
    if path.is_symlink():
        return digest_bytes(("symlink\0" + os.readlink(path)).encode())
    return digest_bytes(path.read_bytes())


def repository_files(excluded: set[str]) -> list[str]:
    """Return every version-controlled or visible untracked input.

    A new Rust source file can change Cargo target discovery and source
    ownership without changing a manifest.  Asking Git for both tracked and
    non-ignored untracked files makes that path-set part of the receipt while
    naturally excluding private tool trees, vendor, and Buck outputs.
    """
    result = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT,
        check=True,
        capture_output=True,
    )
    return sorted(
        raw.decode()
        for raw in result.stdout.split(b"\0")
        if raw and raw.decode() not in excluded
    )


def index_blobs() -> dict[str, str]:
    result = subprocess.run(
        ["git", "ls-files", "-s", "-z"], cwd=ROOT, check=True, capture_output=True
    )
    blobs = {}
    for raw in result.stdout.split(b"\0"):
        if not raw:
            continue
        metadata, relative = raw.split(b"\t", 1)
        _mode, object_id, stage = metadata.decode().split()
        if stage == "0":
            blobs[relative.decode()] = f"git:{object_id}"
    return blobs


def worktree_changes() -> set[str]:
    result = subprocess.run(
        ["git", "diff-files", "--name-only", "-z"],
        cwd=ROOT,
        check=True,
        capture_output=True,
    )
    return {raw.decode() for raw in result.stdout.split(b"\0") if raw}


def git_blob_identity(path: pathlib.Path) -> str:
    content = os.readlink(path).encode() if path.is_symlink() else path.read_bytes()
    header = f"blob {len(content)}\0".encode()
    return "git:" + hashlib.sha1(header + content).hexdigest()


def rust_generation_identity(path: pathlib.Path) -> str:
    # Cargo discovers targets from paths, not Rust bodies. The generator reads
    # bodies only to supply CARGO_BIN_EXE_* inputs to target entry points.
    markers = sorted(set(re.findall(r"CARGO_BIN_EXE_[A-Za-z0-9_-]+", path.read_text())))
    return "cargo-bin-env:" + digest_bytes("\0".join(markers).encode())


def is_content_input(relative: str) -> bool:
    return (
        relative.rsplit("/", 1)[-1] in {"Cargo.toml", "Cargo.lock", "clippy.toml"}
        or relative.endswith(".rs")
        or relative
        in {
            ".cargo/config",
            ".cargo/config.toml",
            "rust-toolchain.toml",
            "scripts/feature-coverage.toml",
            "tools/buck2/action-sizes.json",
            "tools/buck2/clippy-sizes.json",
            "tools/buck2/clippy_policy.py",
            "tools/buck2/feature_variants.py",
            "tools/buck2/generate_model.py",
            "tools/buck2/optimized-sizes.json",
            "tools/buck2/package-policy.toml",
            "tools/buck2/reindeer-lock.json",
            "tools/buck2/reindeer.toml",
            "tools/buck2/source-ownership.json",
            "tools/buck2/sync.py",
            "tools/buck2/target-kind-sizes.json",
            "tools/buck2/test-run-sizes.json",
        }
        or relative.startswith("tools/buck2/fixups/")
    )


def is_graph_path_input(relative: str) -> bool:
    """Whether adding or removing this path can change generated ownership."""
    return (
        is_content_input(relative)
        or relative.endswith((".html", ".js", ".json", ".sql", ".stderr", ".txt"))
        or "/provider-scripts/" in relative
    )


def input_identity(generated_paths: set[str]) -> dict[str, str]:
    excluded = set(generated_paths) | {RECEIPT.relative_to(ROOT).as_posix()}
    relatives = repository_files(excluded)
    indexed = index_blobs()
    changed = worktree_changes()
    result = {
        relative: rust_generation_identity(ROOT / relative)
        if relative.endswith(".rs")
        else indexed[relative]
        if relative in indexed and relative not in changed
        else git_blob_identity(ROOT / relative)
        for relative in relatives
        if is_content_input(relative)
    }
    # Generator ownership globs and Cargo's implicit target discovery depend
    # on names as well as contents. Include every graph-sensitive visible
    # path, but do not invalidate for unrelated docs or repository tests.
    graph_paths = [relative for relative in relatives if is_graph_path_input(relative)]
    result["@graph-paths"] = digest_bytes("\0".join(graph_paths).encode())
    return result


def receipt_payload(outputs: dict[pathlib.Path, str]) -> dict:
    relative_outputs = {
        path.relative_to(ROOT).as_posix(): digest_bytes(content.encode())
        for path, content in sorted(outputs.items())
    }
    return {
        "schema": 1,
        "inputs": input_identity(set(relative_outputs)),
        "outputs": relative_outputs,
    }


def receipt_is_current() -> bool:
    """Accept only unchanged generator inputs and byte-exact outputs."""
    try:
        receipt = json.loads(RECEIPT.read_text(encoding="utf-8"))
        if receipt.get("schema") != 1:
            return False
        inputs = receipt["inputs"]
        outputs = receipt["outputs"]
        if not isinstance(inputs, dict) or not isinstance(outputs, dict) or not outputs:
            return False
        if inputs != input_identity(set(outputs)):
            return False
        for relative, wanted in outputs.items():
            path = ROOT / relative
            if not path.is_file() or path.is_symlink() or digest_path(path) != wanted:
                return False
    except (KeyError, OSError, json.JSONDecodeError, UnicodeDecodeError):
        return False
    return True


def write_receipt(outputs: dict[pathlib.Path, str]) -> None:
    RECEIPT.parent.mkdir(parents=True, exist_ok=True)
    temporary = RECEIPT.with_suffix(".json.tmp")
    temporary.write_text(
        json.dumps(receipt_payload(outputs), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary.replace(RECEIPT)
    share_receipt()


def shared_receipt(directory: pathlib.Path, inputs: dict) -> pathlib.Path:
    return directory / (digest_bytes(json.dumps(inputs, sort_keys=True).encode()) + ".json")


def share_receipt() -> None:
    """Offer this receipt to other checkouts with the same inputs; never fail over it."""
    directory = bootstrap_store.receipts()
    if directory is None:
        return
    try:
        shared = shared_receipt(directory, json.loads(RECEIPT.read_text(encoding="utf-8"))["inputs"])
        temporary = shared.with_suffix(f".{os.getpid()}.tmp")
        shutil.copyfile(RECEIPT, temporary)
        temporary.replace(shared)
    except (OSError, KeyError, json.JSONDecodeError):
        pass


def adopt_shared_receipt() -> bool:
    """Reuse the receipt another checkout wrote for exactly these inputs.

    A receipt is a claim this checkout re-verifies in full, so a wrong or
    damaged one costs a regeneration and is never trusted. A receipt is filed
    under its inputs, which depend on the generated path set it excludes;
    recent receipts supply the path sets worth trying.
    """
    directory = bootstrap_store.receipts()
    if directory is None:
        return False
    try:
        recent = sorted(directory.glob("*.json"), key=lambda path: path.stat().st_mtime, reverse=True)
    except OSError:
        return False
    tried: set[frozenset[str]] = set()
    for candidate in recent[:16]:
        try:
            generated = frozenset(json.loads(candidate.read_text(encoding="utf-8"))["outputs"])
        except (OSError, KeyError, TypeError, json.JSONDecodeError):
            continue
        if not generated or generated in tried:
            continue
        if len(tried) == 3:
            break
        tried.add(generated)
        shared = shared_receipt(directory, input_identity(set(generated)))
        try:
            RECEIPT.parent.mkdir(parents=True, exist_ok=True)
            temporary = RECEIPT.with_suffix(".json.tmp")
            shutil.copyfile(shared, temporary)
            temporary.replace(RECEIPT)
        except OSError:
            continue
        if receipt_is_current():
            os.utime(shared)
            return True
    return False


def metadata(manifest: pathlib.Path = ROOT / "Cargo.toml", *, locked: bool = True) -> dict:
    argv = [cargo(), "metadata", "--format-version", "1", "--manifest-path", str(manifest)]
    if locked:
        argv.append("--locked")
    return json.loads(run(argv).stdout)


def toml_string(value: str) -> str:
    return json.dumps(value)


def synthetic_manifest(canonical: dict) -> str:
    """Render the exact existing external feature union as direct deps."""
    members = set(canonical["workspace_members"])
    nodes = {node["id"]: node for node in canonical["resolve"]["nodes"]}
    packages = sorted(
        (package for package in canonical["packages"] if package["id"] not in members),
        key=lambda package: (package["name"], package["version"], package["id"]),
    )
    lines = [
        GENERATED_HEADER,
        "[package]\n",
        'name = "lash-buck2-third-party"\n',
        'version = "0.0.0"\n',
        'edition = "2024"\n',
        'publish = false\n\n',
        "[workspace]\n",
        'resolver = "2"\n\n',
    ]
    seen_names: set[str] = set()
    for index, package in enumerate(packages):
        alias = f"p{index:04d}"
        seen_names.add(package["name"])
        features = sorted(nodes[package["id"]]["features"])
        source_lines = []
        source = package.get("source") or ""
        if source.startswith("git+"):
            repository, _, revision = source.removeprefix("git+").rpartition("#")
            if not repository or not re.fullmatch(r"[0-9a-f]{40}", revision):
                raise ValueError(f"missing full resolved git revision: {source}")
            repository = repository.partition("?")[0]
            source_lines = [
                f"git = {toml_string(repository)}\n",
                f"rev = {toml_string(revision)}\n",
            ]
        lines.extend(
            [
                f"[dependencies.{alias}]\n",
                f"package = {toml_string(package['name'])}\n",
                f"version = {toml_string('=' + package['version'])}\n",
                *source_lines,
                "default-features = false\n",
                "features = " + json.dumps(features) + "\n\n",
            ]
        )
    for name, version in sorted(EXTRA_LOCKED_CRATES.items()):
        if name in seen_names:
            continue
        alias = f"extra_{name.replace('-', '_')}"
        lines.extend(
            [
                f"[dependencies.{alias}]\n",
                f"package = {toml_string(name)}\n",
                f"version = {toml_string('=' + version)}\n",
                "default-features = false\n\n",
            ]
        )
    return "".join(lines).rstrip() + "\n"


def synthetic_source() -> str:
    return GENERATED_HEADER + "// Reindeer's synthetic manifest needs one Cargo target.\n"


def package_identity(package: dict) -> tuple[str, str, str]:
    return package["name"], package["version"], package.get("source") or "path"


def validate_synthetic(canonical: dict, derived: dict) -> None:
    members = set(canonical["workspace_members"])
    expected = {
        package_identity(package)
        for package in canonical["packages"]
        if package["id"] not in members
    }
    actual = {
        package_identity(package)
        for package in derived["packages"]
        if package["name"] != "lash-buck2-third-party"
    }
    missing = sorted(expected - actual)
    extras = sorted(actual - expected)
    unexpected = [identity for identity in extras if identity[0] not in EXTRA_LOCKED_CLOSURE]
    if missing or unexpected:
        raise SystemExit(
            "synthetic third-party resolution changed Cargo identities:\n"
            + (f"  missing: {missing}\n" if missing else "")
            + (f"  unexpected: {unexpected}\n" if unexpected else "")
        )


def validate_buildscript_fixups(canonical: dict) -> None:
    members = set(canonical["workspace_members"])
    required = {
        package["name"]
        for package in canonical["packages"]
        if package["id"] not in members
        and any("custom-build" in target["kind"] for target in package["targets"])
    }
    enabled = set()
    for path in (BUCK2 / "fixups").glob("*/fixups.toml"):
        content = tomllib.loads(path.read_text(encoding="utf-8"))
        run = content.get("buildscript", {}).get("run")
        if run is True or isinstance(run, dict):
            enabled.add(path.parent.name)
    missing = sorted(required - enabled)
    if missing:
        raise SystemExit(
            "external Cargo build scripts lack explicit Reindeer execution fixups:\n  "
            + "\n  ".join(missing)
        )


# Cargo hands every build script's `rustc-link-lib` and `rustc-link-search`
# output to rustc.  Reindeer translates them only when a crate's fixups set
# `rustc_link_lib`/`rustc_link_search`, and it has no global default, so the
# generator enables both on every generated build-script run.  A crate opts
# out in its fixups.toml with `rustc_link_lib = false` (or
# `rustc_link_search = false`) directly beneath a comment giving the reason.
# `rustc-link-arg*` needs no projection: Cargo applies it only to the emitting
# package's own linked targets, and third-party packages contribute libraries.
BUILDSCRIPT_LINK_DIRECTIVES = ("rustc_link_lib", "rustc_link_search")


def buildscript_link_opt_outs() -> dict[str, frozenset[str]]:
    opt_outs = {}
    for path in sorted((BUCK2 / "fixups").glob("*/fixups.toml")):
        text = path.read_text(encoding="utf-8")
        run = tomllib.loads(text).get("buildscript", {}).get("run")
        if not isinstance(run, dict):
            continue
        relative = path.relative_to(ROOT)
        disabled = set()
        for directive in BUILDSCRIPT_LINK_DIRECTIVES:
            value = run.get(directive)
            if value is None:
                continue
            if value is not False:
                raise SystemExit(
                    f"{relative}: {directive} is enabled for every build script by "
                    "tools/buck2/sync.py; remove the redundant fixup"
                )
            if not re.search(rf"^[ \t]*#.*\n[ \t]*{directive}[ \t]*=[ \t]*false\b", text, re.M):
                raise SystemExit(
                    f"{relative}: the {directive} opt-out needs a comment on the line "
                    "above explaining why the directive must not apply"
                )
            disabled.add(directive)
        if disabled:
            opt_outs[path.parent.name] = frozenset(disabled)
    return opt_outs


def enable_buildscript_link_directives(
    content: str, opt_outs: dict[str, frozenset[str]]
) -> str:
    """Forward build-script native link output unless a fixup opts out."""
    seen = set()

    def inject(match: re.Match[str]) -> str:
        block = match.group(1)
        package = re.search(r'^    package_name = "([^"]+)",$', block, re.M)
        version = re.search(r'^    version = "[^"]+",$', block, re.M)
        if package is None or version is None:
            raise SystemExit("generated build-script rule lacks package_name/version")
        name = package.group(1)
        if "rustc_link_" in block:
            raise SystemExit(
                f"Reindeer emitted link directive settings for {name}; "
                "tools/buck2/sync.py owns them"
            )
        seen.add(name)
        rendered = "".join(
            f"    {directive} = True,\n"
            for directive in BUILDSCRIPT_LINK_DIRECTIVES
            if directive not in opt_outs.get(name, ())
        )
        block = block[: version.start()] + rendered + block[version.start() :]
        return "third_party_buildscript_run(\n" + block + "\n)\n"

    output = re.sub(r"third_party_buildscript_run\(\n(.*?)\n\)\n", inject, content, flags=re.S)
    stale = sorted(opt_outs.keys() - seen)
    if stale:
        raise SystemExit(
            "build-script link opt-outs name packages without a generated build script:\n  "
            + "\n  ".join(stale)
        )
    return output


def reindeer() -> pathlib.Path:
    path = BUCK2 / "bin/reindeer"
    if not path.is_file():
        raise SystemExit("tools/buck2/sync.py: run tools/buck2/bootstrap.py first")
    return path


def buckify_stdout() -> str:
    result = run(
        [
            str(reindeer()),
            "--cargo-path",
            cargo(),
            "-c",
            str(BUCK2 / "reindeer.toml"),
            "buckify",
            "--stdout",
        ]
    )
    return result.stdout


def vendored_git_rules(content: str, resolved: dict) -> tuple[str, dict]:
    """Use Cargo's pinned vendor tree instead of local-only git fetch actions."""
    packages = {
        (package["name"], package["version"]): package
        for package in resolved["packages"]
        if (package.get("source") or "").startswith("git+")
    }
    sources = []

    def replace(match: re.Match[str]) -> str:
        block = match.group(1)
        name = re.search(r'^\s*name = "([^"]+)"', block, re.M).group(1)
        root = name.removesuffix(".git")
        members = {}
        for library in re.findall(r"third_party_rust_library\(\n(.*?)\n\)\n", content, re.S):
            if f'":{name}"' not in library:
                continue
            package_name = re.search(r'"CARGO_PKG_NAME": "([^"]+)"', library).group(1)
            version = re.search(r'"CARGO_PKG_VERSION": "([^"]+)"', library).group(1)
            package = packages[(package_name, version)]
            crate_root = re.search(r'^\s*crate_root = "([^"]+)"', library, re.M).group(1)
            for target in package["targets"]:
                relative = pathlib.Path(target["src_path"]).relative_to(
                    pathlib.Path(package["manifest_path"]).parent
                ).as_posix()
                if crate_root.endswith("/" + relative):
                    directory = crate_root.removeprefix(root + "/")[:-len(relative)].rstrip("/")
                    members[directory] = {
                        "directory": directory,
                        "vendor": f"{package_name}-{version}",
                        "source": package["source"],
                    }
                    break
            else:
                raise ValueError(f"git crate root does not match Cargo targets: {crate_root}")
        if not members:
            raise ValueError(f"git fetch has no Cargo packages: {name}")
        sources.append({"root": root, "packages": list(members.values())})
        prefix = f".git-sources/{root}/"
        return (
            "filegroup(\n"
            f"    name = {toml_string(name)},\n"
            f"    srcs = {{path[{len(prefix)}:]: path for path in glob([{toml_string(prefix + '**')}])}},\n"
            f"    out = {toml_string(root)},\n"
            "    copy = False,\n"
            "    visibility = [],\n"
            ")\n"
        )

    rendered = re.sub(r"git_fetch\(\n(.*?)\n\)\n", replace, content, flags=re.S)
    return rendered, {"sources": sources}


def materialize_git_sources() -> None:
    recipe = SYNTHETIC / "rust/git-sources.json"
    if not recipe.is_file():
        return
    destination = SYNTHETIC / "rust/.git-sources"
    for source in json.loads(recipe.read_text())["sources"]:
        root = destination / source["root"]
        if destination.is_symlink() or root.is_symlink():
            raise ValueError(f"refusing symlinked git source tree: {root}")
        expected = {}
        for package in source["packages"]:
            vendor = ROOT / "vendor" / package["vendor"]
            checksum = vendor / ".cargo-checksum.json"
            hashes = json.loads(checksum.read_text())["files"]
            hashes[checksum.name] = digest_path(checksum)
            for path, digest in hashes.items():
                relative = (pathlib.Path(package["directory"]) / path).as_posix()
                if relative in expected and expected[relative] != digest:
                    raise ValueError(f"conflicting vendored git file: {relative}")
                expected[relative] = digest
        actual = {
            path.relative_to(root).as_posix(): digest_path(path)
            for path in root.rglob("*") if path.is_file()
        } if root.is_dir() and not root.is_symlink() else {}
        if actual == expected:
            continue
        destination.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(dir=destination) as temporary:
            staging = pathlib.Path(temporary) / "tree"
            for package in source["packages"]:
                vendor = ROOT / "vendor" / package["vendor"]
                for path in vendor.rglob("*"):
                    if path.is_file():
                        target = staging / package["directory"] / path.relative_to(vendor)
                        target.parent.mkdir(parents=True, exist_ok=True)
                        if not target.exists():
                            shutil.copy2(path, target)
            copied = {
                path.relative_to(staging).as_posix(): digest_path(path)
                for path in staging.rglob("*") if path.is_file()
            }
            if copied != expected:
                raise ValueError(f"vendored git sources do not match Cargo checksums: {root}")
            if root.exists():
                shutil.rmtree(root)
            staging.rename(root)


def parse_third_party_targets(content: str) -> dict[tuple[str, str], str]:
    implementations: dict[str, tuple[str, str]] = {}
    # Dependency edges always name the package library/proc-macro.  Reindeer
    # also emits a build-script binary carrying the same Cargo package env;
    # accepting binaries here would silently redirect dependants to build.rs.
    for block in re.findall(r"third_party_rust_library\(\n(.*?)\n\)\n", content, re.S):
        name = re.search(r'^\s*name = "([^"]+)",', block, re.M)
        pkg = re.search(r'^\s*"CARGO_PKG_NAME": "([^"]+)",', block, re.M)
        version = re.search(r'^\s*"CARGO_PKG_VERSION": "([^"]+)",', block, re.M)
        if name and pkg and version:
            implementations[name.group(1)] = (pkg.group(1), version.group(1))
    aliases: dict[str, str] = {}
    for block in re.findall(r"alias\(\n(.*?)\n\)\n", content, re.S):
        name = re.search(r'^\s*name = "([^"]+)",', block, re.M)
        actual = re.search(r'^\s*actual = ":([^"]+)",', block, re.M)
        visibility = re.search(r'^\s*visibility = \["PUBLIC"\],', block, re.M)
        if name and actual and visibility:
            aliases.setdefault(actual.group(1), name.group(1))
    mapping = {
        identity: f"//third-party/rust:{aliases[target]}"
        for target, identity in implementations.items()
        if target in aliases
    }
    if not mapping:
        raise SystemExit("Reindeer output contained no public Rust package aliases")
    return mapping


def inject_buildscript_metadata(content: str, resolved: dict) -> str:
    """Wire Cargo `links` metadata between dependent build scripts."""
    run_targets: dict[tuple[str, str], str] = {}
    for block in re.findall(r"third_party_buildscript_run\(\n(.*?)\n\)\n", content, re.S):
        name = re.search(r'^\s*name = "([^"]+)"', block, re.M)
        package = re.search(r'^\s*package_name = "([^"]+)"', block, re.M)
        version = re.search(r'^\s*version = "([^"]+)"', block, re.M)
        if not (name and package and version):
            raise SystemExit("generated build-script rule lacks name/package/version")
        run_targets[(package.group(1), version.group(1))] = ":" + name.group(1)

    packages = {package["id"]: package for package in resolved["packages"]}
    nodes = {node["id"]: node for node in resolved["resolve"]["nodes"]}
    sources: dict[tuple[str, str], list[str]] = {}
    for owner_id, node in nodes.items():
        owner = packages[owner_id]
        identity = (owner["name"], owner["version"])
        if identity not in run_targets:
            continue
        labels = []
        for dependency in node["deps"]:
            linked = packages[dependency["pkg"]]
            if not linked.get("links"):
                continue
            normal = [kind for kind in dependency["dep_kinds"] if kind["kind"] is None]
            if not normal:
                continue
            targeted = [kind["target"] for kind in normal if kind["target"] is not None]
            if targeted:
                raise SystemExit(
                    f"target-specific Cargo links metadata needs an explicit platform projection: "
                    f"{owner['name']} -> {linked['name']}: {targeted}"
                )
            linked_identity = (linked["name"], linked["version"])
            target = run_targets.get(linked_identity)
            if target is None:
                raise SystemExit(
                    f"Cargo links dependency has no build-script metadata producer: "
                    f"{owner['name']} -> {linked['name']} {linked['version']}"
                )
            labels.append(target + "[metadata]")
        if labels:
            sources[identity] = sorted(set(labels))

    def inject(match: re.Match[str]) -> str:
        block = match.group(1)
        package = re.search(r'^\s*package_name = "([^"]+)"', block, re.M)
        version = re.search(r'^\s*version = "([^"]+)"', block, re.M)
        assert package and version
        labels = sources.get((package.group(1), version.group(1)), [])
        if not labels:
            return match.group(0)
        anchor = re.search(r'^    buildscript_rule = "[^"]+",\n', block, re.M)
        if anchor is None:
            raise SystemExit(f"build-script rule lacks buildscript_rule: {package.group(1)}")
        rendered = "    env_srcs = " + json.dumps(labels) + ",\n"
        block = block[: anchor.end()] + rendered + block[anchor.end() :]
        return "third_party_buildscript_run(\n" + block + "\n)\n"

    output = re.sub(r"third_party_buildscript_run\(\n(.*?)\n\)\n", inject, content, flags=re.S)
    if output.count("env_srcs =") != len(sources):
        raise SystemExit("Cargo links metadata projection did not cover every consumer")
    return output


def package_labels(canonical: dict) -> dict[str, str]:
    members = set(canonical["workspace_members"])
    result = {}
    for package in canonical["packages"]:
        if package["id"] not in members:
            continue
        directory = pathlib.Path(package["manifest_path"]).resolve().parent.relative_to(ROOT).as_posix()
        result[package["id"]] = f"//{directory}:{pathlib.PurePosixPath(directory).name}"
    return result


def dependency_table(canonical: dict, third_party: dict[tuple[str, str], str]) -> dict:
    members = set(canonical["workspace_members"])
    labels = package_labels(canonical)
    packages = {package["id"]: package for package in canonical["packages"]}
    nodes = {node["id"]: node for node in canonical["resolve"]["nodes"]}
    table = {}
    for owner in sorted(members, key=lambda package_id: packages[package_id]["name"]):
        groups: dict[str, dict[str, str]] = {"normal": {}, "dev": {}, "build": {}}
        for dependency in nodes[owner]["deps"]:
            target = packages[dependency["pkg"]]
            label = labels.get(dependency["pkg"])
            if label is None:
                label = third_party.get((target["name"], target["version"]))
            if label is None:
                raise SystemExit(f"no Reindeer target for {target['name']} {target['version']}")
            for kind in dependency["dep_kinds"]:
                group = kind["kind"] or "normal"
                if group in groups:
                    groups[group][dependency["name"].replace("-", "_")] = label
        table[packages[owner]["name"]] = groups
    return table


def deps_bzl(table: dict) -> str:
    return GENERATED_HEADER + "PACKAGE_DEPS = " + json.dumps(table, indent=4, sort_keys=True) + "\n"


def profile_bzl(canonical: dict) -> str:
    manifest = tomllib.loads((ROOT / "Cargo.toml").read_text())
    overrides = manifest.get("profile", {}).get("dev", {}).get("package", {})
    members = set(canonical["workspace_members"])
    member_names = {
        package["name"] for package in canonical["packages"] if package["id"] in members
    }
    # Cargo's host-side proc-macro support crates already compile in the exec
    # configuration. Preserve the existing graph policy by leaving them on the
    # ordinary execution profile rather than applying target-package overrides.
    host_only = {"proc-macro2", "quote", "syn"}
    first_party: dict[str, int] = {}
    third_party: dict[str, int] = {}
    for name, values in sorted(overrides.items()):
        if name == "*":
            continue
        if set(values) != {"opt-level"}:
            raise SystemExit(f"unsupported dev profile keys for {name}: {sorted(values)}")
        if name in member_names:
            first_party[name] = int(values["opt-level"])
        elif name not in host_only:
            third_party[name] = int(values["opt-level"])
    return (
        GENERATED_HEADER
        + "FIRST_PARTY_OPT_LEVELS = "
        + json.dumps(first_party, indent=4, sort_keys=True)
        + "\n\nTHIRD_PARTY_OPT_LEVELS = "
        + json.dumps(third_party, indent=4, sort_keys=True)
        + "\n"
    )


def inventory_payload(model_payload: dict, workspace_bzl: str, feature_bzl: str) -> dict:
    def list_value(name: str, text: str) -> list[str]:
        match = re.search(rf"{name} = (\[.*?\])\n", text, re.S)
        if not match:
            raise SystemExit(f"generated table lacks {name}")
        return ast.literal_eval(match.group(1))

    lanes_match = re.search(r"FEATURE_LANES = (\{.*\})\n$", feature_bzl, re.S)
    if not lanes_match:
        raise SystemExit("generated table lacks FEATURE_LANES")
    floors_match = re.search(
        r"FEATURE_LANE_TEST_FLOORS = (\{.*?\})\n\nFEATURE_LANES", feature_bzl, re.S
    )
    if not floors_match:
        raise SystemExit("generated table lacks FEATURE_LANE_TEST_FLOORS")
    args_match = re.search(
        r"FEATURE_LANE_TEST_ARGS = (\{.*?\})\n\nFEATURE_LANE_TEST_FLOORS", feature_bzl, re.S
    )
    if not args_match:
        raise SystemExit("generated table lacks FEATURE_LANE_TEST_ARGS")

    result = dict(model_payload)
    result.update(
        {
            "workspace_compile_targets": list_value("WORKSPACE_COMPILE_TARGETS", workspace_bzl),
            "workspace_test_targets": list_value("WORKSPACE_TEST_TARGETS", workspace_bzl),
            "workspace_dev_test_targets": list_value("WORKSPACE_DEV_TEST_TARGETS", workspace_bzl),
            "workspace_deferred_test_targets": list_value("WORKSPACE_DEFERRED_TEST_TARGETS", workspace_bzl),
            "workspace_test_suite_labels": list_value("WORKSPACE_TEST_SUITE_LABELS", workspace_bzl),
            "workspace_dev_suite_labels": list_value("WORKSPACE_DEV_SUITE_LABELS", workspace_bzl),
            "workspace_tail_suite_labels": list_value("WORKSPACE_TAIL_SUITE_LABELS", workspace_bzl),
            "workspace_test_batches": {
                package["test_batch"]["label"]: package["test_batch"]["members"]
                for package in model_payload["packages"]
                if package["test_batch"]["label"]
            },
            "workspace_doc_targets": list_value("WORKSPACE_DOC_TARGETS", workspace_bzl),
            "workspace_clippy_targets": list_value("WORKSPACE_CLIPPY_TARGETS", workspace_bzl),
            "workspace_rust_source_targets": list_value(
                "WORKSPACE_RUST_SOURCE_TARGETS", workspace_bzl
            ),
            "feature_lane_compile_targets": list_value("FEATURE_LANE_COMPILE_TARGETS", feature_bzl),
            "feature_lane_test_targets": list_value("FEATURE_LANE_TEST_TARGETS", feature_bzl),
            "feature_lanes": ast.literal_eval(lanes_match.group(1)),
            "feature_lane_test_args": ast.literal_eval(args_match.group(1)),
            "feature_lane_test_floors": ast.literal_eval(floors_match.group(1)),
            "service_test_targets": {},
        }
    )
    timeout_names = {None: 300, "short": 60, "moderate": 300, "long": 900, "eternal": 3600}
    timeouts: dict[str, int] = {}
    ordinary: list[tuple[str, int]] = []
    for package in result["packages"]:
        for target in package["targets"]:
            label = target.get("label")
            if label is None or target["kind"] not in {"unit-test", "bin-unit-test", "test"}:
                continue
            policy = generate_model.target_policy(
                package["package"], target["kind"], target["cargo"]
            )
            seconds = timeout_names[policy.timeout]
            timeouts[label] = seconds
            ordinary.append((label, seconds))
        batch = package["test_batch"]["label"]
        if batch:
            timeouts[batch] = 300
    for unit in result["feature_lane_units"]:
        if unit["kind"] not in {"unit-test", "bin-unit-test", "test"}:
            continue
        base = unit["label"].split("__fv_", 1)[0]
        timeouts[unit["label"]] = next(
            (seconds for label, seconds in ordinary if label == base), 300
        )
    result["test_timeout_seconds"] = dict(sorted(timeouts.items()))
    result["workspace_core_suite_labels"] = sorted(
        set(result["workspace_test_suite_labels"]) - set(result["workspace_tail_suite_labels"])
    )

    def output_label(label: str, kind: str) -> str:
        return label + "[static]" if kind == "lib" else label

    def clippy_label(label: str) -> str:
        # The Clippy twin lash_rust.bzl declares beside every Rust target: the
        # same rule on its own execution platform, sized for Clippy.
        return label + "__clippy[clippy.txt]"

    kinds: dict[str, str] = {}
    for package in result["packages"]:
        for target in package["targets"]:
            if target.get("label"):
                target["build_label"] = output_label(target["label"], target["kind"])
                if target["kind"] == "lib":
                    target["doc_label"] = target["label"] + "[doc]"
                if target["kind"] != "custom-build":
                    target["clippy_label"] = clippy_label(target["label"])
                if target["kind"] != "custom-build":
                    target["check_label"] = target["label"] + "[check]"
                kinds[target["label"]] = target["kind"]
    for unit in result["feature_lane_units"]:
        unit["build_label"] = output_label(unit["label"], unit["kind"])
        if unit["kind"] == "lib":
            unit["doc_label"] = unit["label"] + "[doc]"
        unit["check_label"] = unit["label"] + "[check]"
        unit["clippy_label"] = clippy_label(unit["label"])
        kinds[unit["label"]] = unit["kind"]
    result["workspace_build_targets"] = [
        output_label(label, kinds.get(label, ""))
        for label in result["workspace_compile_targets"]
    ]
    checks = {
        target["label"]: target["check_label"]
        for package in result["packages"]
        for target in package["targets"]
        if "check_label" in target
    }
    result["workspace_check_targets"] = [
        checks[label]
        for label in result["workspace_compile_targets"]
        if label in checks
    ]
    result["feature_lane_build_targets"] = [
        output_label(label, kinds.get(label, ""))
        for label in result["feature_lane_compile_targets"]
    ]
    result["feature_lane_check_targets"] = [
        label + "[check]" for label in result["feature_lane_compile_targets"]
    ]
    result["workspace_clippy_build_targets"] = [
        clippy_label(label) for label in result["workspace_clippy_targets"]
    ]
    return result


WORKFLOW_GRAPH_SCHEMA_DIRECTORY = "schemas/host/workflow-graph"


def workflow_graph_schema() -> str:
    """The one committed workflow-graph schema document, whatever its version.

    The Rust version constant is feature-gated, so the generator follows the
    file the schema generator wrote. Any other count is a half-applied version
    change, which must fail here instead of selecting a document silently.
    """
    pattern = f"{WORKFLOW_GRAPH_SCHEMA_DIRECTORY}/v*.schema.json"
    found = sorted(path.relative_to(ROOT).as_posix() for path in ROOT.glob(pattern))
    if len(found) != 1:
        raise SystemExit(
            f"tools/buck2/sync.py: //:workflow_graph_schema needs exactly one {pattern}, "
            f"found {', '.join(found) if found else 'none'}"
        )
    return found[0]


def root_buck(inventory: dict) -> str:
    def suite(name: str, labels: list[str]) -> str:
        return (
            "test_suite(\n"
            f"    name = {json.dumps(name)},\n"
            "    tests = " + json.dumps(labels, indent=8) + ",\n"
            '    visibility = ["PUBLIC"],\n'
            ")\n\n"
        )

    aggregates = "".join(
        [
            GENERATED_HEADER,
            'load("//tools/buck2:schema_checks.bzl", "schema_check", "schema_check_group", "schema_documents")\n\n',
            'load("//tools/buck2:source_tree.bzl", "lash_workspace_sources")\n\n',
            suite("workspace_compile", inventory["workspace_build_targets"]),
            suite("workspace_check", inventory["workspace_check_targets"]),
            suite("workspace_tests", inventory["workspace_test_suite_labels"]),
            suite("dev_tests", inventory["workspace_dev_suite_labels"]),
            suite("deferred_tests", inventory["workspace_deferred_test_targets"]),
            suite("workspace_core_tests", inventory["workspace_core_suite_labels"]),
            suite("workspace_tail_tests", inventory["workspace_tail_suite_labels"]),
            suite("workspace_clippy", inventory["workspace_clippy_build_targets"]),
            suite("workspace_docs", inventory["workspace_doc_targets"]),
            # These generated variants represent Cargo `check` commands. The
            # native check subtarget is metadata-only and consumes rmeta
            # dependencies, preserving Cargo check's no-codegen/no-link
            # behavior for all lane libraries, binaries, and tests.
            suite("feature_lanes", inventory["feature_lane_check_targets"]),
            suite("feature_lane_compile", inventory["feature_lane_check_targets"]),
            suite("feature_lane_tests", inventory["feature_lane_test_targets"]),
        ]
    )
    return aggregates + (
        "filegroup(\n"
        '    name = "workflow_graph_schema",\n'
        f"    srcs = [{json.dumps(workflow_graph_schema())}],\n"
        "    copy = False,\n"
        '    visibility = ["PUBLIC"],\n'
        ")\n"
    ) + '''
filegroup(
    name = "dialect_deviation_register",
    srcs = ["docs/adr/0062-the-typescript-dialect-is-an-exact-ecma-262-subset.md"],
    copy = False,
    visibility = ["PUBLIC"],
)

filegroup(
    name = "host_schemas",
    srcs = glob(["schemas/host/*/*.schema.json"]),
    copy = False,
    visibility = ["PUBLIC"],
)

filegroup(
    name = "cargo_metadata",
    srcs = ["Cargo.lock", "Cargo.toml"],
    copy = False,
    visibility = ["PUBLIC"],
)

lash_workspace_sources(
    name = "workspace_rust_sources",
    deps = ''' + json.dumps(inventory["workspace_rust_source_targets"], indent=8) + ''',
    visibility = ["PUBLIC"],
)

filegroup(
    name = "workspace_test_scripts",
    srcs = [
    ],
    copy = False,
    visibility = ["PUBLIC"],
)

filegroup(
    name = "confidence_gate_scripts",
    srcs = [
        "scripts/ci/confidence-stage.sh",
        "scripts/ci/pg-service.sh",
        "scripts/confidence-gate.sh",
        "scripts/worktree-gate-env.sh",
    ],
    copy = False,
    visibility = ["PUBLIC"],
)

filegroup(
    name = "perf_guard_budgets",
    srcs = ["scripts/perf_guard_budgets.json"],
    copy = False,
    visibility = ["PUBLIC"],
)

filegroup(
    name = "perf_duration_level_shifts",
    srcs = ["scripts/perf_duration_level_shifts.json"],
    copy = False,
    visibility = ["PUBLIC"],
)

export_file(
    name = "clippy.toml",
    src = "clippy.toml",
    visibility = ["PUBLIC"],
)

export_file(
    name = "Cargo.toml",
    src = "Cargo.toml",
    mode = "reference",
    visibility = ["PUBLIC"],
)

export_file(
    name = "Cargo.lock",
    src = "Cargo.lock",
    mode = "reference",
    visibility = ["PUBLIC"],
)

export_file(
    name = "rust-toolchain.toml",
    src = "rust-toolchain.toml",
    visibility = ["PUBLIC"],
)

export_file(
    name = "scripts/facade_completeness.py",
    src = "scripts/facade_completeness.py",
    mode = "reference",
    visibility = ["PUBLIC"],
)

schema_documents(
    name = "host_schema_documents",
    generators = [
        "//crates/lashlang:workflow_schema_generator__bin",
        "//crates/lash-trace:trace_schema_generator__bin",
        "//crates/lash-remote-protocol:remote_schema_generator__bin",
        "//crates/lash-core-execution:process_event_schema_generator__bin",
    ],
    script = "scripts/generate-workflow-schemas.py",
)

schema_check(
    name = "host_schema_check",
    documents = ":host_schema_documents",
    checked = glob(["schemas/host/*/*.schema.json"]),
    script = "scripts/generate-workflow-schemas.py",
)

schema_documents(
    name = "example_schema_documents",
    generators = ["//examples/workflow-graph-roundtrip:workflow_contract_schema__bin"],
    script = "//examples/workflow-graph-roundtrip:scripts/generate-contract-schema.py",
)

schema_check(
    name = "example_schema_check",
    documents = ":example_schema_documents",
    checked = [
        "//examples/workflow-graph-roundtrip:frontend/src/generated/error-response.schema.json",
        "//examples/workflow-graph-roundtrip:frontend/src/generated/workflow-document.schema.json",
    ],
    script = "//examples/workflow-graph-roundtrip:scripts/generate-contract-schema.py",
)

schema_check_group(
    name = "schema_checks",
    checks = [":host_schema_check", ":example_schema_check"],
)
'''


def examples_buck() -> str:
    return GENERATED_HEADER + '''filegroup(
    name = "shared_rust_sources",
    srcs = glob(["shared/**/*.rs"]),
    copy = False,
    visibility = ["PUBLIC"],
)

filegroup(
    name = "typescript_host_flow_cells",
    srcs = glob(["typescript-host-flows/*.ts"]),
    copy = False,
    visibility = ["PUBLIC"],
)
'''


def model_outputs(canonical: dict, third_party: dict[tuple[str, str], str]) -> dict[pathlib.Path, str]:
    raw, _ = generate_model.generated(canonical, third_party)
    outputs = dict(raw)
    workspace = raw[BUCK2 / "workspace_targets.bzl"]
    feature = raw[BUCK2 / "feature_lanes.bzl"]
    payload = json.loads(raw[BUCK2 / "target-inventory.json"])
    inventory = inventory_payload(payload, workspace, feature)
    for service in ("postgres", "s3"):
        path = BUCK2 / f"{service}_test_labels.txt"
        labels = raw.get(path, "").splitlines()
        inventory["service_test_targets"][service] = labels
        outputs[BUCK2 / f"{service}_test_labels.txt"] = "".join(label + "\n" for label in labels)
    outputs[BUCK2 / "target-inventory.json"] = json.dumps(inventory, indent=2, sort_keys=True) + "\n"
    outputs[BUCK2 / "clippy_policy.bzl"] = clippy_policy.render(canonical, ROOT)
    outputs[ROOT / "BUCK"] = root_buck(inventory)
    outputs[ROOT / "examples/BUCK"] = examples_buck()
    lash_buck = ROOT / "crates/lash/BUCK"
    outputs[lash_buck] += '''
export_file(
    name = "tests/ui/core_builder_plugin_host_is_removed.rs",
    src = "tests/ui/core_builder_plugin_host_is_removed.rs",
    visibility = ["PUBLIC"],
)

export_file(
    name = "tests/ui/core_builder_plugin_host_is_removed.stderr",
    src = "tests/ui/core_builder_plugin_host_is_removed.stderr",
    visibility = ["PUBLIC"],
)
'''
    empty_feature_ui_harnesses = {
        unit["label"]
        for unit in payload["feature_lane_units"]
        if unit["package"] == "lash-runtime"
        and unit["kind"] == "test"
        and unit["features"] == []
        and ":ui__test__fv_" in unit["label"]
    }
    if len(empty_feature_ui_harnesses) != 1:
        raise ValueError(
            "expected exactly one no-feature lash-runtime UI harness, got "
            + repr(sorted(empty_feature_ui_harnesses))
        )
    empty_feature_ui_harness = next(iter(empty_feature_ui_harnesses))
    rlm_ui_harnesses = {
        unit["label"]
        for unit in payload["feature_lane_units"]
        if unit["package"] == "lash-runtime"
        and unit["kind"] == "test"
        and unit["features"] == ["rlm"]
        and ":ui__test__fv_" in unit["label"]
    }
    if len(rlm_ui_harnesses) != 1:
        raise ValueError(
            "expected exactly one rlm-only lash-runtime UI harness, got "
            + repr(sorted(rlm_ui_harnesses))
        )
    rlm_ui_harness = next(iter(rlm_ui_harnesses))
    store_seam = generate_model.PACKAGE_POLICY["ui_fixtures"]["lash-runtime"]["store_seam"]
    outputs[lash_buck] += f'''
ui_fixtures_test(
    name = "ui_store_seam",
    harness = "{rlm_ui_harness}",
    package = "crates/lash",
    fixtures = {generate_model.string_list([f"tests/ui/{name}.rs" for name in store_seam])},
    expected = {generate_model.string_list([f"tests/ui/{name}.stderr" for name in store_seam])},
    tags = ["manual"],
)
'''
    outputs[ROOT / "crates/lash/tests/builder_contract/BUCK"] = GENERATED_HEADER + f'''load("//tools/buck2:ui_fixtures.bzl", "ui_fixtures_test")

ui_fixtures_test(
    name = "builder_plugin_host_is_removed_without_testing",
    harness = "{empty_feature_ui_harness}",
    package = "crates/lash",
    fixtures = ["//crates/lash:tests/ui/core_builder_plugin_host_is_removed.rs"],
    expected = ["//crates/lash:tests/ui/core_builder_plugin_host_is_removed.stderr"],
    tags = ["manual"],
)
'''
    return outputs


def generate_lock(manifest_text: str, source_text: str) -> str:
    with tempfile.TemporaryDirectory(prefix="lash-buck2-lock-") as directory:
        root = pathlib.Path(directory)
        (root / "src").mkdir()
        (root / "Cargo.toml").write_text(manifest_text)
        (root / "src/lib.rs").write_text(source_text)
        run([cargo(), "generate-lockfile", "--offline", "--manifest-path", str(root / "Cargo.toml")])
        return (root / "Cargo.lock").read_text()


def write_or_check(outputs: dict[pathlib.Path, str], check: bool) -> int:
    stale = []
    for path, content in sorted(outputs.items()):
        if not path.exists() or path.read_text() != content:
            stale.append(path.relative_to(ROOT).as_posix())
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    if stale and check:
        print("stale Buck2 build inventory:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    if not check:
        print(f"synchronized {len(outputs)} Buck2 graph files")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--verify-resolution", action="store_true")
    args = parser.parse_args()
    subprocess.run(
        [sys.executable, str(BUCK2 / "bootstrap_native_tools.py"), "--check"],
        cwd=ROOT,
        check=True,
    )
    if args.check:
        subprocess.run(
            [
                sys.executable,
                str(BUCK2 / "prelude_overlay.py"),
                "--buck2",
                str(ROOT / ".buck2/bin/buck2"),
                "--prelude-dir",
                str(ROOT / ".buck2/prelude"),
                "--check",
            ],
            cwd=ROOT,
            check=True,
        )
    subprocess.run(
        [
            sys.executable,
            str(BUCK2 / "bootstrap_vendor.py"),
            *(["--check"] if args.check else []),
        ],
        cwd=ROOT,
        check=True,
    )
    if args.check:
        materialize_git_sources()
    if args.check and not args.verify_resolution and (receipt_is_current() or adopt_shared_receipt()):
        print("Buck2 graph receipt is current")
        return 0

    canonical = metadata()
    validate_buildscript_fixups(canonical)
    if args.verify_resolution:
        return generate_model.verify_resolution(canonical)

    manifest_text = synthetic_manifest(canonical)
    source_text = synthetic_source()
    outputs: dict[pathlib.Path, str] = {
        SYNTHETIC / "Cargo.toml": manifest_text,
        SYNTHETIC / "src/lib.rs": source_text,
    }
    if args.check:
        lock_path = SYNTHETIC / "Cargo.lock"
        if not lock_path.is_file():
            return write_or_check({**outputs, lock_path: ""}, True)
        outputs[lock_path] = lock_path.read_text()
    else:
        outputs[SYNTHETIC / "Cargo.lock"] = generate_lock(manifest_text, source_text)
        write_or_check(outputs, False)

    derived = metadata(SYNTHETIC / "Cargo.toml")
    validate_synthetic(canonical, derived)
    validate_buildscript_fixups(derived)
    third_party_buck = inject_buildscript_metadata(
        enable_buildscript_link_directives(buckify_stdout(), buildscript_link_opt_outs()),
        derived,
    )
    third_party_buck, git_sources = vendored_git_rules(third_party_buck, derived)
    outputs[SYNTHETIC / "rust/git-sources.json"] = json.dumps(git_sources, indent=2) + "\n"
    targets = parse_third_party_targets(third_party_buck)
    outputs[ROOT / "third-party/rust/BUCK"] = third_party_buck
    outputs[BUCK2 / "deps.bzl"] = deps_bzl(dependency_table(canonical, targets))
    outputs[BUCK2 / "profile.bzl"] = profile_bzl(canonical)
    outputs.update(model_outputs(canonical, targets))
    failures = generate_model.reconcile_lane_units(
        canonical, json.loads(outputs[BUCK2 / "target-inventory.json"])["feature_lane_units"]
    )
    if failures:
        for failure in failures:
            print(f"feature-lane graph differs from Cargo: {failure}", file=sys.stderr)
        return 1
    result = write_or_check(outputs, args.check)
    if result == 0:
        if not args.check:
            subprocess.run([sys.executable, str(BUCK2 / "bootstrap_vendor.py")], cwd=ROOT, check=True)
            materialize_git_sources()
        write_receipt(outputs)
    return result


if __name__ == "__main__":
    raise SystemExit(main())
