// @generated by tools/bazel/generate_build_files.py; do not edit.
pub fn build_identity() -> lash_vm_protocol::BuildIdentity {
    lash_vm_protocol::BuildIdentity::new(format!(
        "lash-worker/ca29b88ba84f99977a8d1bd109cdcec42bffcf341b1177f0d23df22a65bf741b/{}/{}/debug-{}/testing-{}",
        std::env::consts::ARCH,
        std::env::consts::OS,
        cfg!(debug_assertions),
        cfg!(feature = "testing")
    ))
}
