// @generated by tools/bazel/generate_build_files.py; do not edit.
pub fn build_identity() -> lash_vm_protocol::BuildIdentity {
    lash_vm_protocol::BuildIdentity::new(format!(
        "lash-worker/d9dd371187d20f76db4161a352238c3db0190e07ef0ba26fffcee1d531ed5f52/{}/{}/debug-{}/testing-{}",
        std::env::consts::ARCH,
        std::env::consts::OS,
        cfg!(debug_assertions),
        cfg!(feature = "testing")
    ))
}
