// @generated by tools/bazel/generate_build_files.py; do not edit.
pub fn build_identity() -> lash_vm_protocol::BuildIdentity {
    lash_vm_protocol::BuildIdentity::new(format!(
        "lash-worker/4e3dd88d8484538b670a57b733cbf392c9e5f319d64add2358d3463ea3c3b5be/{}/{}/debug-{}/testing-{}",
        std::env::consts::ARCH,
        std::env::consts::OS,
        cfg!(debug_assertions),
        cfg!(feature = "testing")
    ))
}
