#!/usr/bin/env python3
"""Generate first-party Bazel targets from Cargo's locked workspace metadata."""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parents[2]
GENERATED_HEADER = "# @generated by tools/bazel/generate_build_files.py; do not edit.\n"
# `//crates/lash-sim:lash-sim__unit_test` packs the whole simulation suite into
# one libtest binary, and a libtest binary is a single Bazel test action. On CI
# run 34791314196 it ran 313 s and was the last action of a 926 s job: from
# 11:15 to 16:26 it was the only thing running while every other executor slot
# sat idle. Eight shards were measured at 97/16/249/27/18/7/178/41 s.
LASH_SIM_UNIT_TEST_SHARDS = 8
LOAD = """load(
    "//tools/bazel:lash_rust.bzl",
    "lash_rust_binary",
    "lash_rust_build_script",
    "lash_rust_integration_test",
    "lash_rust_library",
    "lash_rust_unit_test",
)

"""


def quote(value: str) -> str:
    return json.dumps(value)


def string_list(values: list[str], indent: int = 8) -> str:
    if not values:
        return "[]"
    spaces = " " * indent
    return "[\n" + "".join(f"{spaces}{quote(value)},\n" for value in values) + " " * (indent - 4) + "]"


def cargo_metadata() -> dict:
    metadata_env = os.environ.copy()
    for variable in (
        "RUSTC_WRAPPER",
        "RUSTC_WORKSPACE_WRAPPER",
        "CARGO_BUILD_RUSTC_WRAPPER",
        "CARGO_BUILD_RUSTC_WORKSPACE_WRAPPER",
    ):
        metadata_env[variable] = ""
    result = subprocess.run(
        [os.environ.get("KILN_REAL_CARGO", "cargo"), "metadata", "--locked", "--format-version", "1"],
        cwd=ROOT,
        env=metadata_env,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def package_features(metadata: dict) -> dict[str, list[str]]:
    nodes = {node["id"]: sorted(node["features"]) for node in metadata["resolve"]["nodes"]}
    return {package["id"]: nodes.get(package["id"], []) for package in metadata["packages"]}


def relative(path: str) -> str:
    return pathlib.Path(path).resolve().relative_to(ROOT).as_posix()


def label_name(target: dict, primary: bool) -> str:
    kind = target["kind"][0]
    if primary:
        return pathlib.Path(target["src_path"]).resolve().parents[1].name
    suffix = {
        "bin": "bin",
        "example": "example",
        "test": "test",
        "bench": "bench",
    }[kind]
    return f"{target['name']}__{suffix}"


def cargo_bin_env(source: pathlib.Path, labels: dict[str, str]) -> tuple[dict[str, str], list[str]]:
    text = source.read_text()
    env = {}
    deps = []
    for cargo_name, label in labels.items():
        key = f"CARGO_BIN_EXE_{cargo_name}"
        if key in text:
            env[key] = f"$(rootpath :{label})"
            deps.append(f":{label}")
    return env, deps


# The agent-workbench cases that shell out to `node --test` to drive
# `examples/agent-workbench/tests/browser_projection.mjs`. The Bazel action has
# no Node.js toolchain and no Cargo-relative asset tree, so the partition label
# skips them by name (`args`, below) and the `Test Cargo workspace partition`
# job selects exactly them out of the same binary
# (`tools/bazel/workbench_nextest_filter.txt`). Every other workbench case is
# partition-owned and runs on the pool. Keep the two derived from this one list
# so a new Node-gated case can never be skipped by Bazel without also being
# picked up by Cargo, or the reverse.
NODE_GATED_WORKBENCH_TESTS = (
    "tests::recoverable_chat_tests::"
    "workbench_browser_recovery_projection_preserves_rows_and_scopes_session_cursors",
)


def cargo_test_policy(
    package_name: str, kind: str, target_name: str
) -> tuple[list[str], str | None]:
    """Classify one executable test label as partition-owned or Cargo-owned.

    `manual` keeps a label out of `//:workspace_tests` and out of `bazel test
    //...`. It is reserved for labels the cacheable partition genuinely cannot
    execute as proof: a live service, a nested Cargo invocation, a Cargo-relative
    asset tree, or a toolchain the Bazel job does not install. Service-gated
    labels are still *built* by Bazel; the PostgreSQL and MinIO jobs execute
    them with `--nocache_test_results` so a cached result can never stand in for
    a run against a real service, and so an unconfigured service is never proof.
    """
    tags = []
    reasons = []
    if package_name in ("lash-internal-postgres-store", "lash-internal-s3-store"):
        tags.extend(["manual", "cargo-service-gate"])
        reasons.append(
            "proves nothing without a live PostgreSQL or MinIO; the service jobs"
            " execute this label uncached against a real service"
        )
    if package_name == "lash-runtime" and target_name == "ui":
        tags.extend(["manual", "cargo-trybuild"])
        reasons.append("uses trybuild and its Cargo-managed compiler fixture cache")
    if package_name == "workflow-graph-roundtrip" and kind == "test":
        tags.extend(["manual", "cargo-frontend-assets"])
        reasons.append("uses the Cargo-owned generated frontend asset workflow")
    if package_name == "lash-sim" and target_name.startswith("cross_backend"):
        tags.extend(["manual", "cargo-service-gate"])
        reasons.append(
            "proves nothing without a live PostgreSQL or MinIO; the service jobs"
            " execute this label uncached against a real service"
        )
    if package_name == "lash-internal-typescript" and kind == "test":
        # Partition-owned, but not remotely executable: the no-abort guarantee
        # forks a dozen children that each parse deliberately deep sources
        # right up to the stack bound, and their combined footprint exceeds any
        # single-action memory budget the pool grants -- re-measured against
        # the raised floor, `the_abort_corpus_survives_without_the_preflight`
        # and `fuzzed_sources_survive_without_the_preflight` still die of
        # `signal: 9 (SIGKILL)`. The same label passes locally in 43 s. Pin the
        # placement rather than soften what the test proves.
        tags.append("no-remote-exec")
    if package_name == "lash-regress" and target_name == "unicodesets":
        tags.append("pr-deferred")
        reasons.append(
            "RGI Unicode suites are too slow for the PR Bazel partition; they"
            " run on lash-regress diffs and on trunk"
        )
    reason = "; ".join(reasons) if reasons else None
    return sorted(set(tags)), reason


def bazel_test_shard_count(package_name: str, kind: str, target_name: str) -> int:
    """How many parallel Bazel test actions one libtest binary is split into.

    A libtest binary is a single test action, so a crate that packs hundreds of
    cases into one binary sets the partition's critical path no matter how many
    executor slots are free. `rust_test`'s sharding wrapper lists the binary,
    assigns each case to a shard by a stable name hash and runs only that
    subset, so the shards execute disjoint subsets whose union is every case the
    unsharded binary runs. Sharding is opt-in: each shard pays its own `--list`
    execution and runfiles tree, so only a binary whose wall time dominates the
    job earns one.
    """
    if package_name == "lash-sim" and kind == "unit-test":
        return LASH_SIM_UNIT_TEST_SHARDS
    return 0


def nextest_filter_term(package_name: str, target: dict) -> str:
    """Select exactly one Cargo test binary in nextest's filter language."""
    kind = target["kind"]
    if kind == "unit-test":
        target_filter = "kind(lib)"
    elif kind == "bin-unit-test":
        target_filter = f"kind(bin) & binary({target['cargo']})"
    elif kind == "test":
        target_filter = f"kind(test) & binary({target['cargo']})"
    else:
        raise ValueError(f"unsupported nextest target kind: {kind}")
    return f"(package({package_name}) & {target_filter})"


def render_package(package: dict, features: list[str]) -> tuple[str, dict]:
    manifest = relative(package["manifest_path"])
    package_dir = pathlib.PurePosixPath(manifest).parent.as_posix()
    version = package["version"]
    declared_features = sorted(package["features"])
    targets = [target for target in package["targets"] if "custom-build" not in target["kind"]]
    resolved_feature_set = set(features)

    def enabled_by_resolved_features(target: dict) -> bool:
        return set(target.get("required-features", [])) <= resolved_feature_set

    library = next((target for target in targets if "lib" in target["kind"]), None)
    binaries = [target for target in targets if "bin" in target["kind"]]
    binary_labels = {
        target["name"]: label_name(target, library is None and len(binaries) == 1)
        for target in binaries
        if enabled_by_resolved_features(target)
    }
    primary_target = pathlib.PurePosixPath(package_dir).name
    library_label = f":{primary_target}" if library else None
    library_crate = library["name"] if library else None
    chunks = [GENERATED_HEADER, LOAD, "package(default_visibility = [\"//visibility:public\"])\n\n"]
    inventory_targets = []

    has_build_script = any("custom-build" in target["kind"] for target in package["targets"])
    if has_build_script:
        chunks.append(
            "lash_rust_build_script(\n"
            "    name = \"build_script\",\n"
            f"    crate_features = {string_list(features)},\n"
            f"    declared_features = {string_list(declared_features)},\n"
            f"    data = [\"{relative(next(target for target in package['targets'] if 'custom-build' in target['kind'])['src_path']).replace(package_dir + '/', '')}\"] + glob([\"src/**/*.rs\"]),\n"
            f"    manifest_dir = {quote(package_dir)},\n"
            f"    package_name = {quote(package['name'])},\n"
            f"    version = {quote(version)},\n"
            ")\n\n"
        )
        inventory_targets.append({
            # `cargo_build_script` wraps its binary and exposes no `CrateInfo`,
            # so the clippy aspect cannot attach to this label. Cargo lints
            # `build.rs` under `--all-targets`; keep that coverage with the
            # Cargo command on untrusted events and record the gap here rather
            # than dropping it silently.
            "clippy_exempt": "cargo_build_script exposes no CrateInfo for the clippy aspect",
            "kind": "custom-build",
            "label": f"//{package_dir}:build_script",
        })

    if library:
        extra_compile_data = []
        if package["name"] == "slack-clone":
            extra_compile_data.append("//examples:shared_rust_sources")
        if package["name"] == "lash-perf":
            extra_compile_data.append("//:perf_guard_budgets")
        chunks.append(
            "lash_rust_library(\n"
            f"    name = {quote(primary_target)},\n"
            f"    build_script = {quote(':build_script') if has_build_script else 'None'},\n"
            f"    crate_features = {string_list(features)},\n"
            f"    crate_name = {quote(library['name'])},\n"
            f"    declared_features = {string_list(declared_features)},\n"
            f"    extra_compile_data = {string_list(extra_compile_data)},\n"
            f"    manifest_dir = {quote(package_dir)},\n"
            f"    package_name = {quote(package['name'])},\n"
            f"    version = {quote(version)},\n"
            ")\n\n"
        )
        inventory_targets.append({"kind": "lib", "cargo": library["name"], "label": f"//{package_dir}:{primary_target}"})
        if library.get("test", False):
            unit_compile_data = []
            if package["name"] == "slack-clone":
                unit_compile_data.append("//examples:shared_rust_sources")
            if package["name"] == "lash-internal-sansio":
                unit_compile_data.append("//:workspace_rust_sources")
            if package["name"] == "slack-clone":
                unit_compile_data.append("//:workspace_test_scripts")
            if package["name"] == "lash-perf":
                unit_compile_data.append("//:perf_guard_budgets")
            if package["name"] in (
                "lash-runtime",
                "lash-internal-sqlite-store",
            ):
                unit_compile_data.append("//crates/lashlang:old_module_fixture")
            unit_tags, unit_cargo_reason = cargo_test_policy(
                package["name"], "unit-test", library["name"]
            )
            unit_extra_data = []
            unit_args = []
            unit_timeout = None
            if package["name"] == "lash-sim":
                # The Postgres effect-history consistency case reads the gate
                # script and the repository-root documents it must agree with.
                unit_extra_data.append("//:confidence_gate_corpus")
                # This binary carries the generated-simulation and minimizer
                # fixture replays (measured 182-418 s each under Cargo). The
                # whole binary ran 227-300 s on the pool, which straddles
                # Bazel's default `medium` 300 s bound; `long` is 900 s.
                unit_timeout = "long"
            unit_shards = bazel_test_shard_count(
                package["name"], "unit-test", library["name"]
            )
            unit_test_env = {}
            if package["name"] == "lash-perf":
                # This instrumentation binary shares process-global counters.
                # Cargo nextest isolates cases by process; serialize libtest so
                # Bazel observes the same one-at-a-time measurement contract.
                unit_test_env["RUST_TEST_THREADS"] = "1"
            chunks.append(
                "lash_rust_unit_test(\n"
                f"    name = {quote(primary_target + '__unit_test')},\n"
                + (f"    args = {string_list(unit_args)},\n" if unit_args else "")
                + f"    build_script = {quote(':build_script') if has_build_script else 'None'},\n"
                f"    crate_features = {string_list(features)},\n"
                f"    crate_name = {quote(library['name'])},\n"
                f"    crate_root = {quote(relative(library['src_path']).replace(package_dir + '/', ''))},\n"
                f"    declared_features = {string_list(declared_features)},\n"
                f"    extra_compile_data = {string_list(unit_compile_data)},\n"
                + (
                    f"    extra_data = {string_list(unit_extra_data)},\n"
                    if unit_extra_data
                    else ""
                )
                + f"    manifest_dir = {quote(package_dir)},\n"
                + f"    package_name = {quote(package['name'])},\n"
                + (f"    shard_count = {unit_shards},\n" if unit_shards else "")
                + (
                    f"    test_env = {json.dumps(unit_test_env, sort_keys=True)},\n"
                    if unit_test_env
                    else ""
                )
                + f"    tags = {string_list(unit_tags)},\n"
                + (f"    timeout = {quote(unit_timeout)},\n" if unit_timeout else "")
                + f"    version = {quote(version)},\n"
                + ")\n\n"
            )
            unit_inventory = {
                "cargo": library["name"],
                "kind": "unit-test",
                "label": f"//{package_dir}:{primary_target}__unit_test",
                "tags": unit_tags,
            }
            if unit_shards:
                unit_inventory["shard_count"] = unit_shards
            if unit_cargo_reason:
                unit_inventory["cargo_only"] = unit_cargo_reason
            inventory_targets.append(unit_inventory)
    for target in targets:
        kind = target["kind"][0]
        if kind == "lib":
            continue
        required_features = sorted(target.get("required-features", []))
        if not enabled_by_resolved_features(target):
            inventory_targets.append({
                "cargo": target["name"],
                "cargo_only": "required features are outside the resolved default workspace graph",
                "kind": kind,
                "label": None,
                "required_features": required_features,
                "tags": ["cargo-feature-gate", "manual"],
            })
            continue
        primary = not library and kind == "bin" and len(binaries) == 1
        name = label_name(target, primary)
        crate_root = relative(target["src_path"]).replace(package_dir + "/", "")
        target_features = sorted(set(features) | set(target.get("required-features", [])))
        source = pathlib.Path(target["src_path"])
        rustc_env, binary_data = cargo_bin_env(source, binary_labels)
        test_env = {}
        test_env.update(rustc_env)
        extra_data = []
        if (
            package["name"] == "lash-internal-core"
            and target["name"] == "integration_boundary"
        ):
            # The checked-in workspace fact that replaces a nested
            # `cargo metadata` call in the dependency-direction test.
            extra_data.append("//tools/bazel:target_inventory")
        if package["name"] == "lash-internal-core" and target["name"] in (
            "runtime_turns",
            "runtime_observability",
        ):
            # These carry the relocated suites that assert over captured
            # `tracing` events. Capture installs a scoped default subscriber,
            # so other cases in the same libtest process must not emit
            # concurrently; Cargo nextest isolates by process, Bazel does not.
            test_env["RUST_TEST_THREADS"] = "1"
        if package["name"] == "lash-internal-sqlite-store" and target["name"] == "integration":
            # The warning-capture contract installs a scoped tracing subscriber.
            # Other tests in this libtest process must not emit concurrently.
            test_env["RUST_TEST_THREADS"] = "1"
        if package["name"] == "lash-internal-lashlang" and target["name"] in (
            "append_cost",
            "dialect_cost",
        ):
            # These cost laws read a process-global counting allocator. Cargo
            # nextest isolates cases by process; serialize libtest so Bazel
            # observes the same one-at-a-time measurement contract.
            test_env["RUST_TEST_THREADS"] = "1"
        extra_compile_data = []
        if package["name"] in (
            "agent-service",
            "agent-workbench",
            "slack-clone",
            "toolbench",
        ):
            extra_compile_data.append("//examples:shared_rust_sources")
        if package["name"] == "lash-internal-lashlang" and target["name"] == "dialect_cost":
            # It holds the dialect to the corpus's own checked-in budget by
            # reading the budget file with `include_str!`, the way lash-perf
            # does, so the file is a compile input of this test.
            extra_compile_data.append("//:perf_guard_budgets")
        if package["name"] in (
            "lash-internal-postgres-store",
            "lash-internal-sqlite-store",
        ):
            if target["name"] == "conformance":
                helper_name = (
                    "postgres-await-event-helper"
                    if package["name"] == "lash-internal-postgres-store"
                    else "sqlite-await-event-helper"
                )
                helper_target = next(
                    candidate for candidate in targets if candidate["name"] == helper_name
                )
                helper_label = f":{label_name(helper_target, False)}"
                test_env["LASH_CONFORMANCE_HELPER_EXE"] = (
                    f"$(rootpath {helper_label})"
                )
                extra_data.append(helper_label)
            if target["name"] in (
                "postgres-await-event-helper",
                "sqlite-await-event-helper",
            ):
                extra_compile_data.append("//crates/lash-core:cold_process_drivers")
            if target["name"] == "conformance":
                extra_compile_data.extend([
                    "//crates/lash-core:queued_claim_atomicity",
                ])
            if target["name"] == "durable_read_fixture":
                extra_compile_data.append("//crates/lash-core:durable_read_fixture_source")
        if (
            package["name"] == "lash-internal-postgres-store"
            and target["name"] == "preflight_durable_walk"
        ):
            extra_compile_data.append("//crates/lashlang:old_module_fixture")
        if package["name"] in (
            "lash-internal-postgres-store",
            "lash-internal-sqlite-store",
        ) and target["name"] == "durable_read_fixture":
            extra_compile_data.append("//:durable_fixtures")
        target_args = []
        if (
            package["name"] == "lash-internal-core"
            and target["name"] == "runtime_scenarios"
        ):
            # The fault-matrix routing probes execute the real
            # scripts/confidence-gate.sh against a recording `cargo`.
            extra_data.append("//:confidence_gate_scripts")
            # The five `..._real_cargo_filters_chunk_*` cases each fork a real
            # `cargo test ... -- --list` against the workspace to prove the
            # gate's name filters still select tests. That is a claim about
            # Cargo's own selection, so it cannot be proved inside a hermetic
            # action without Cargo; the trunk-only `Test heavy suites` job
            # (profile.ci-heavy) owns them and is the only place they run.
            # Excluded by name here so the label is honest about what it
            # executed.
            target_args.append(
                "--skip=runtime::tests::runtime_scenarios::fault_matrix"
                "::durable_fault_matrix_real_cargo_filters_chunk_"
            )
        if package["name"] == "lash-sim" and kind == "test":
            extra_compile_data.extend([
                "//crates/lash-postgres-store:package_files",
                "//crates/lash-sqlite-store:package_files",
            ])
            if target["name"] == "cross_backend_store_differential":
                # Its completeness gates read the real store trait definitions
                # with `include_str!`, so the lash-core sources are compile
                # inputs of this test and of no other lash-sim test.
                extra_compile_data.append("//crates/lash-core:package_files")
        if (
            package["name"] == "lash-sim"
            and target["name"] == "signal_replay_key_constructor"
        ):
            # The gate scans every first-party Rust source, runbooks and
            # examples included, so under Bazel it needs them all in the sandbox
            # or it would pass by seeing nothing.
            extra_compile_data.append("//:workspace_rust_sources")
        macro = (
            "lash_rust_binary"
            if kind in ("bin", "example", "bench")
            else "lash_rust_integration_test"
        )
        crate_name = target["name"].replace("-", "_")
        target_tags, target_cargo_reason = cargo_test_policy(
            package["name"], kind, target["name"]
        )
        target_shards = bazel_test_shard_count(package["name"], kind, target["name"])
        if kind == "bench":
            target_tags.append("manual")
        args = [
            f"    name = {quote(name)},",
            f"    crate_features = {string_list(target_features)},",
            f"    crate_name = {quote(crate_name)},",
            f"    crate_root = {quote(crate_root)},",
            f"    declared_features = {string_list(declared_features)},",
            f"    extra_compile_data = {string_list(extra_compile_data + binary_data)},",
        ]
        if kind in ("bin", "example", "bench"):
            args.append(f"    include_dev_deps = {str(kind in ('example', 'bench'))},")
        else:
            if target_args:
                args.append(f"    args = {string_list(target_args)},")
            if extra_data:
                args.append(f"    extra_data = {string_list(extra_data)},")
            if target_shards:
                args.append(f"    shard_count = {target_shards},")
            if test_env:
                args.append(f"    test_env = {json.dumps(test_env, sort_keys=True)},")
        args.extend([
            f"    library = {quote(library_label) if library_label else 'None'},",
            f"    library_crate_name = {quote(library_crate) if library_crate else 'None'},",
            f"    manifest_dir = {quote(package_dir)},",
            f"    package_name = {quote(package['name'])},",
            f"    rustc_env = {json.dumps(rustc_env, sort_keys=True)},",
            f"    tags = {string_list(sorted(set(target_tags)))},",
            f"    version = {quote(version)},",
        ])
        chunks.append(macro + "(\n" + "\n".join(args) + "\n)\n\n")
        target_inventory = {
            "cargo": target["name"],
            "kind": kind,
            "label": f"//{package_dir}:{name}",
            "tags": sorted(set(target_tags)),
        }
        if target_shards:
            target_inventory["shard_count"] = target_shards
        if target_cargo_reason:
            target_inventory["cargo_only"] = target_cargo_reason
        inventory_targets.append(target_inventory)

        if kind == "bin" and target.get("test", False):
            bin_unit_tags, bin_unit_cargo_reason = cargo_test_policy(
                package["name"], "bin-unit-test", target["name"]
            )
            bin_unit_skips = (
                list(NODE_GATED_WORKBENCH_TESTS)
                if package["name"] == "agent-workbench"
                else []
            )
            unit_args = [
                "lash_rust_unit_test(\n",
                f"    name = {quote(name + '__unit_test')},\n",
            ]
            if bin_unit_skips:
                unit_args.append(
                    "    args = "
                    + string_list([f"--skip={test}" for test in bin_unit_skips])
                    + ",\n"
                )
            unit_args += [
                f"    crate_features = {string_list(target_features)},\n",
                f"    crate_name = {quote(crate_name)},\n",
                f"    crate_root = {quote(crate_root)},\n",
                f"    declared_features = {string_list(declared_features)},\n",
            ]
            if extra_compile_data or binary_data:
                unit_args.append(
                    f"    extra_compile_data = {string_list(extra_compile_data + binary_data)},\n"
                )
            unit_args.extend([
                f"    library = {quote(library_label) if library_label else 'None'},\n"
                f"    library_crate_name = {quote(library_crate) if library_crate else 'None'},\n"
                f"    manifest_dir = {quote(package_dir)},\n"
                f"    package_name = {quote(package['name'])},\n"
                f"    tags = {string_list(bin_unit_tags)},\n"
                f"    version = {quote(version)},\n"
                ")\n\n"
            ])
            chunks.append("".join(unit_args))
            bin_unit_inventory = {
                "cargo": target["name"],
                "kind": "bin-unit-test",
                "label": f"//{package_dir}:{name}__unit_test",
                "tags": bin_unit_tags,
            }
            if bin_unit_skips:
                bin_unit_inventory["bazel_skipped"] = sorted(bin_unit_skips)
            if bin_unit_cargo_reason:
                bin_unit_inventory["cargo_only"] = bin_unit_cargo_reason
            inventory_targets.append(bin_unit_inventory)

    if package["name"] == "lash-internal-core":
        chunks.append(
            "filegroup(\n"
            "    name = \"cold_process_drivers\",\n"
            "    srcs = [\n"
            "        \"tests/support/cold_process_effect_driver.rs\",\n"
            "    ],\n"
            ")\n\n"
            "filegroup(\n"
            "    name = \"durable_read_fixture_source\",\n"
            "    srcs = [\"tests/support/durable_read_fixture.rs\"],\n"
            ")\n\n"
            "filegroup(\n"
            "    name = \"queued_claim_atomicity\",\n"
            "    srcs = [\"tests/support/queued_claim_atomicity.rs\"],\n"
            ")\n\n"
        )

    if package["name"] == "lash-internal-lashlang":
        chunks.append(
            "filegroup(\n"
            "    name = \"old_module_fixture\",\n"
            "    srcs = [\"tests/fixtures/module-artifact-old.json\"],\n"
            ")\n\n"
        )

    chunks.append(
        "filegroup(\n"
        "    name = \"rust_sources\",\n"
        "    srcs = glob([\"**/*.rs\"]),\n"
        ")\n\n"
        "filegroup(\n"
        "    name = \"package_files\",\n"
        "    srcs = glob([\"**\"], exclude = [\"BUILD\", \"BUILD.bazel\"]),\n"
        ")\n"
    )
    return "".join(chunks), {
        "declared_features": declared_features,
        # Every declared dependency name of this package, normal, dev and build
        # alike — exactly what `cargo metadata --no-deps` reports for it.
        # Checked in so an architecture test can assert dependency direction
        # without shelling out to Cargo from inside a hermetic test action.
        "dependencies": sorted(
            {dependency["name"] for dependency in package["dependencies"]}
        ),
        "manifest": manifest,
        "package": package["name"],
        "resolved_features": features,
        "targets": inventory_targets,
    }


def generated(metadata: dict) -> tuple[dict[pathlib.Path, str], list[dict]]:
    features = package_features(metadata)
    outputs = {}
    inventory = []
    workspace_members = set(metadata["workspace_members"])
    for package in metadata["packages"]:
        manifest = pathlib.Path(package["manifest_path"]).resolve()
        if package["id"] not in workspace_members:
            continue
        content, item = render_package(package, features[package["id"]])
        outputs[manifest.parent / "BUILD.bazel"] = content
        inventory.append(item)
    inventory.sort(key=lambda item: item["manifest"])
    inventory_payload = {
        "cargo_package_count": len(inventory),
        "cargo_target_count": sum(
            1
            for package in metadata["packages"]
            if package["id"] in workspace_members
            for _target in package["targets"]
        ),
        "generated_label_count": sum(
            1
            for item in inventory
            for target in item["targets"]
            if target["label"] is not None
        ),
        "cargo_only_target_count": sum(
            1
            for item in inventory
            for target in item["targets"]
            if target["label"] is None
        ),
        "packages": inventory,
    }
    outputs[ROOT / "tools/bazel/target-inventory.json"] = (
        json.dumps(inventory_payload, indent=2, sort_keys=True) + "\n"
    )
    labels = [target for package in inventory for target in package["targets"]]
    executable_tests = [
        target
        for target in labels
        if target["label"] is not None
        and target["kind"] in ("bin-unit-test", "test", "unit-test")
    ]
    groups = {
        "WORKSPACE_COMPILE_TARGETS": sorted(
            target["label"] for target in labels if target["label"] is not None
        ),
        # Cargo lints libs, bins, examples, benches and test crates under
        # `clippy --workspace --all-targets`. Build scripts are excluded here
        # because `cargo_build_script` exposes no `CrateInfo` for the clippy
        # aspect to consume; their `cargo-build-script-clippy` exception is
        # recorded per label in `tools/bazel/target-inventory.json`.
        "WORKSPACE_CLIPPY_TARGETS": sorted(
            target["label"]
            for target in labels
            if target["label"] is not None
            and target["kind"] != "custom-build"
        ),
        "WORKSPACE_RUST_SOURCE_TARGETS": sorted(
            f"//{pathlib.PurePosixPath(package['manifest']).parent.as_posix()}:rust_sources"
            for package in inventory
        ),
        "WORKSPACE_BAZEL_TEST_TARGETS": sorted(
            target["label"]
            for target in executable_tests
            if "manual" not in target["tags"] and "pr-deferred" not in target["tags"]
        ),
        "WORKSPACE_DEFERRED_TEST_TARGETS": sorted(
            target["label"]
            for target in executable_tests
            if "pr-deferred" in target["tags"]
        ),
        "WORKSPACE_CARGO_TEST_TARGETS": sorted(
            target["label"] for target in executable_tests if "manual" in target["tags"]
        ),
        "WORKSPACE_TEST_TARGETS": sorted(
            target["label"] for target in executable_tests
        ),
    }
    bzl = [GENERATED_HEADER]
    for name, values in groups.items():
        bzl.append(f"{name} = {string_list(values, indent=4)}\n\n")
    outputs[ROOT / "tools/bazel/workspace_targets.bzl"] = "".join(bzl).rstrip() + "\n"
    def cargo_owned_terms(*exclude_tags: str) -> list[str]:
        excluded = set(exclude_tags)
        return sorted(
            nextest_filter_term(package["package"], target)
            for package in inventory
            for target in package["targets"]
            if target.get("label") is not None
            and target["kind"] in ("bin-unit-test", "test", "unit-test")
            and "manual" in target["tags"]
            and not excluded.intersection(target["tags"])
        )

    cargo_nextest_terms = cargo_owned_terms(
        "cargo-service-gate",
        "cargo-trybuild",
        "cargo-frontend-assets",
    )
    # `none()` rather than an empty expression: every Cargo-owned deterministic
    # binary has moved to the Bazel partition, and an empty string would be a
    # nextest syntax error at the call site rather than an empty selection.
    outputs[ROOT / "tools/bazel/cargo_owned_nextest_filter.txt"] = (
        " + ".join(cargo_nextest_terms) + "\n" if cargo_nextest_terms else "none()\n"
    )
    # The workbench partition is now exactly the Node-gated cases the Bazel
    # label skipped, selected by name out of the same binary. Derived from the
    # same `bazel_skipped` records the label's `--skip` args come from, so the
    # two halves of the split cannot drift into a gap or an overlap.
    workbench_terms = sorted(
        f"({nextest_filter_term(package['package'], target)} & test(={test}))"
        for package in inventory
        if package["package"] == "agent-workbench"
        for target in package["targets"]
        if target.get("label") is not None
        and target["kind"] in ("bin-unit-test", "test", "unit-test")
        for test in target.get("bazel_skipped", ())
    )
    outputs[ROOT / "tools/bazel/workbench_nextest_filter.txt"] = (
        " + ".join(workbench_terms) + "\n" if workbench_terms else "none()\n"
    )
    # The service jobs build these labels from the shared cache and execute
    # them uncached against the service they stand up. Generated, so a new
    # service-gated binary reaches the service job without a hand edit.
    service_packages = {
        "postgres": ("lash-internal-postgres-store",),
        "minio": ("lash-internal-s3-store",),
    }
    for service, package_names in service_packages.items():
        labels = sorted(
            target["label"]
            for package in inventory
            if package["package"] in package_names
            for target in package["targets"]
            if target["label"] is not None
            and target["kind"] in ("bin-unit-test", "test", "unit-test")
        )
        outputs[ROOT / f"tools/bazel/{service}_test_labels.txt"] = (
            "".join(f"{label}\n" for label in labels)
        )
    return outputs, inventory


def check(outputs: dict[pathlib.Path, str]) -> int:
    stale = []
    for path, expected in outputs.items():
        if not path.exists() or path.read_text() != expected:
            stale.append(path.relative_to(ROOT).as_posix())
    if stale:
        print("stale Bazel build inventory:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs, _inventory = generated(cargo_metadata())
    if args.check:
        return check(outputs)
    for path, content in outputs.items():
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
