#!/usr/bin/env python3
"""Generate first-party Bazel targets from Cargo's locked workspace metadata."""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parents[2]
GENERATED_HEADER = "# @generated by tools/bazel/generate_build_files.py; do not edit.\n"
LOAD = """load(
    "//tools/bazel:lash_rust.bzl",
    "lash_rust_binary",
    "lash_rust_build_script",
    "lash_rust_doc_test",
    "lash_rust_integration_test",
    "lash_rust_library",
    "lash_rust_unit_test",
)

"""


def quote(value: str) -> str:
    return json.dumps(value)


def string_list(values: list[str], indent: int = 8) -> str:
    if not values:
        return "[]"
    spaces = " " * indent
    return "[\n" + "".join(f"{spaces}{quote(value)},\n" for value in values) + " " * (indent - 4) + "]"


def cargo_metadata() -> dict:
    metadata_env = os.environ.copy()
    for variable in (
        "RUSTC_WRAPPER",
        "RUSTC_WORKSPACE_WRAPPER",
        "CARGO_BUILD_RUSTC_WRAPPER",
        "CARGO_BUILD_RUSTC_WORKSPACE_WRAPPER",
    ):
        metadata_env[variable] = ""
    result = subprocess.run(
        [os.environ.get("ORB_REAL_CARGO", "cargo"), "metadata", "--locked", "--format-version", "1"],
        cwd=ROOT,
        env=metadata_env,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def package_features(metadata: dict) -> dict[str, list[str]]:
    nodes = {node["id"]: sorted(node["features"]) for node in metadata["resolve"]["nodes"]}
    return {package["id"]: nodes.get(package["id"], []) for package in metadata["packages"]}


def relative(path: str) -> str:
    return pathlib.Path(path).resolve().relative_to(ROOT).as_posix()


def label_name(target: dict, primary: bool) -> str:
    kind = target["kind"][0]
    if primary:
        return pathlib.Path(target["src_path"]).resolve().parents[1].name
    suffix = {
        "bin": "bin",
        "example": "example",
        "test": "test",
        "bench": "bench",
    }[kind]
    return f"{target['name']}__{suffix}"


def cargo_bin_env(source: pathlib.Path, labels: dict[str, str]) -> tuple[dict[str, str], list[str]]:
    text = source.read_text()
    env = {}
    deps = []
    for cargo_name, label in labels.items():
        key = f"CARGO_BIN_EXE_{cargo_name}"
        if key in text:
            env[key] = f"$(rootpath :{label})"
            deps.append(f":{label}")
    return env, deps


def cargo_test_policy(
    package_name: str, kind: str, target_name: str
) -> tuple[list[str], str | None]:
    tags = []
    reasons = []
    if package_name in ("lash-internal-postgres-store", "lash-internal-s3-store"):
        tags.extend(["manual", "cargo-service-gate"])
        reasons.append("requires the Cargo-owned PostgreSQL or MinIO service gate")
    if kind == "unit-test" and package_name in ("lash-internal-restate", "lash-runtime"):
        tags.extend(["manual", "cargo-service-gate"])
        reasons.append("shares a unit-test binary with Cargo-owned live-service tests")
    if package_name == "lash-internal-core" and kind == "unit-test":
        tags.extend(["manual", "cargo-nested-suite"])
        reasons.append("shares a unit-test binary with nested-Cargo fault-matrix tests")
    if package_name == "lash-sim" and kind == "unit-test":
        tags.extend(["manual", "cargo-heavy-suite"])
        reasons.append("shares a unit-test binary with specially scheduled heavy simulation tests")
    if package_name == "lash-internal-core" and target_name == "integration_boundary":
        tags.extend(["manual", "cargo-nested-suite"])
        reasons.append("invokes Cargo metadata against the workspace")
    if package_name == "lash-runtime" and target_name == "ui":
        tags.extend(["manual", "cargo-trybuild"])
        reasons.append("uses trybuild and its Cargo-managed compiler fixture cache")
    if package_name == "lash-internal-typescript" and kind == "test":
        tags.extend(["manual", "cargo-path-assets"])
        reasons.append("uses Cargo-relative Test262 and WPT asset trees")
    if package_name == "workflow-graph-roundtrip" and kind == "test":
        tags.extend(["manual", "cargo-frontend-assets"])
        reasons.append("uses the Cargo-owned generated frontend asset workflow")
    if package_name == "agent-workbench" and kind in ("bin-unit-test", "unit-test"):
        tags.extend(["manual", "cargo-frontend-assets"])
        reasons.append("shares a unit-test binary with a Node.js browser projection gate")
    if package_name == "lash-sim" and target_name.startswith("cross_backend"):
        tags.extend(["manual", "cargo-service-gate"])
        reasons.append("requires explicitly scheduled durable backend services")
    reason = "; ".join(reasons) if reasons else None
    return sorted(set(tags)), reason


def nextest_filter_term(package_name: str, target: dict) -> str:
    """Select exactly one Cargo test binary in nextest's filter language."""
    kind = target["kind"]
    if kind == "unit-test":
        target_filter = "kind(lib)"
    elif kind == "bin-unit-test":
        target_filter = f"kind(bin) & binary({target['cargo']})"
    elif kind == "test":
        target_filter = f"kind(test) & binary({target['cargo']})"
    else:
        raise ValueError(f"unsupported nextest target kind: {kind}")
    return f"(package({package_name}) & {target_filter})"


def render_package(package: dict, features: list[str]) -> tuple[str, dict]:
    manifest = relative(package["manifest_path"])
    package_dir = pathlib.PurePosixPath(manifest).parent.as_posix()
    version = package["version"]
    declared_features = sorted(package["features"])
    targets = [target for target in package["targets"] if "custom-build" not in target["kind"]]
    resolved_feature_set = set(features)

    def enabled_by_resolved_features(target: dict) -> bool:
        return set(target.get("required-features", [])) <= resolved_feature_set

    library = next((target for target in targets if "lib" in target["kind"]), None)
    binaries = [target for target in targets if "bin" in target["kind"]]
    binary_labels = {
        target["name"]: label_name(target, library is None and len(binaries) == 1)
        for target in binaries
        if enabled_by_resolved_features(target)
    }
    primary_target = pathlib.PurePosixPath(package_dir).name
    library_label = f":{primary_target}" if library else None
    library_crate = library["name"] if library else None
    chunks = [GENERATED_HEADER, LOAD, "package(default_visibility = [\"//visibility:public\"])\n\n"]
    inventory_targets = []

    has_build_script = any("custom-build" in target["kind"] for target in package["targets"])
    if has_build_script:
        chunks.append(
            "lash_rust_build_script(\n"
            "    name = \"build_script\",\n"
            f"    crate_features = {string_list(features)},\n"
            f"    declared_features = {string_list(declared_features)},\n"
            f"    data = [\"{relative(next(target for target in package['targets'] if 'custom-build' in target['kind'])['src_path']).replace(package_dir + '/', '')}\"] + glob([\"src/**/*.rs\"]),\n"
            f"    manifest_dir = {quote(package_dir)},\n"
            f"    package_name = {quote(package['name'])},\n"
            f"    version = {quote(version)},\n"
            ")\n\n"
        )
        inventory_targets.append({"kind": "custom-build", "label": f"//{package_dir}:build_script"})

    if library:
        extra_compile_data = []
        if package["name"] == "slack-clone":
            extra_compile_data.append("//examples:shared_rust_sources")
        if package["name"] == "lash-perf":
            extra_compile_data.append("//:perf_guard_budgets")
        chunks.append(
            "lash_rust_library(\n"
            f"    name = {quote(primary_target)},\n"
            f"    build_script = {quote(':build_script') if has_build_script else 'None'},\n"
            f"    crate_features = {string_list(features)},\n"
            f"    crate_name = {quote(library['name'])},\n"
            f"    declared_features = {string_list(declared_features)},\n"
            f"    extra_compile_data = {string_list(extra_compile_data)},\n"
            f"    manifest_dir = {quote(package_dir)},\n"
            f"    package_name = {quote(package['name'])},\n"
            f"    version = {quote(version)},\n"
            ")\n\n"
        )
        inventory_targets.append({"kind": "lib", "cargo": library["name"], "label": f"//{package_dir}:{primary_target}"})
        if library.get("test", False):
            unit_compile_data = []
            if package["name"] == "slack-clone":
                unit_compile_data.append("//examples:shared_rust_sources")
            if package["name"] == "lash-internal-sansio":
                unit_compile_data.append("//:workspace_rust_sources")
            if package["name"] == "slack-clone":
                unit_compile_data.append("//:workspace_test_scripts")
            if package["name"] == "lash-perf":
                unit_compile_data.append("//:perf_guard_budgets")
            if package["name"] in (
                "lash-runtime",
                "lash-internal-sqlite-store",
            ):
                unit_compile_data.append("//crates/lashlang:old_module_fixture")
            unit_tags, unit_cargo_reason = cargo_test_policy(
                package["name"], "unit-test", library["name"]
            )
            unit_test_env = {}
            if package["name"] == "lash-perf":
                # This instrumentation binary shares process-global counters.
                # Cargo nextest isolates cases by process; serialize libtest so
                # Bazel observes the same one-at-a-time measurement contract.
                unit_test_env["RUST_TEST_THREADS"] = "1"
            chunks.append(
                "lash_rust_unit_test(\n"
                f"    name = {quote(primary_target + '__unit_test')},\n"
                f"    build_script = {quote(':build_script') if has_build_script else 'None'},\n"
                f"    crate_features = {string_list(features)},\n"
                f"    crate_name = {quote(library['name'])},\n"
                f"    crate_root = {quote(relative(library['src_path']).replace(package_dir + '/', ''))},\n"
                f"    declared_features = {string_list(declared_features)},\n"
                f"    extra_compile_data = {string_list(unit_compile_data)},\n"
                f"    manifest_dir = {quote(package_dir)},\n"
                f"    package_name = {quote(package['name'])},\n"
                + (
                    f"    test_env = {json.dumps(unit_test_env, sort_keys=True)},\n"
                    if unit_test_env
                    else ""
                )
                + f"    tags = {string_list(unit_tags)},\n"
                + f"    version = {quote(version)},\n"
                + ")\n\n"
            )
            unit_inventory = {
                "cargo": library["name"],
                "kind": "unit-test",
                "label": f"//{package_dir}:{primary_target}__unit_test",
                "tags": unit_tags,
            }
            if unit_cargo_reason:
                unit_inventory["cargo_only"] = unit_cargo_reason
            inventory_targets.append(unit_inventory)
        if library.get("doctest", False):
            chunks.append(
                "lash_rust_doc_test(\n"
                f"    name = {quote(primary_target + '__doc_test')},\n"
                f"    crate = {quote(':' + primary_target)},\n"
                ")\n\n"
            )
            inventory_targets.append({
                "kind": "doc-test",
                "label": f"//{package_dir}:{primary_target}__doc_test",
                "tags": ["cargo-authoritative-doctest", "manual"],
            })

    for target in targets:
        kind = target["kind"][0]
        if kind == "lib":
            continue
        required_features = sorted(target.get("required-features", []))
        if not enabled_by_resolved_features(target):
            inventory_targets.append({
                "cargo": target["name"],
                "cargo_only": "required features are outside the resolved default workspace graph",
                "kind": kind,
                "label": None,
                "required_features": required_features,
                "tags": ["cargo-feature-gate", "manual"],
            })
            continue
        primary = not library and kind == "bin" and len(binaries) == 1
        name = label_name(target, primary)
        crate_root = relative(target["src_path"]).replace(package_dir + "/", "")
        target_features = sorted(set(features) | set(target.get("required-features", [])))
        source = pathlib.Path(target["src_path"])
        rustc_env, binary_data = cargo_bin_env(source, binary_labels)
        test_env = {}
        test_env.update(rustc_env)
        extra_data = []
        if package["name"] == "lash-internal-sqlite-store" and target["name"] == "integration":
            # The warning-capture contract installs a scoped tracing subscriber.
            # Other tests in this libtest process must not emit concurrently.
            test_env["RUST_TEST_THREADS"] = "1"
        extra_compile_data = []
        if package["name"] in (
            "agent-service",
            "agent-workbench",
            "slack-clone",
            "toolbench",
        ):
            extra_compile_data.append("//examples:shared_rust_sources")
        if package["name"] in (
            "lash-internal-postgres-store",
            "lash-internal-sqlite-store",
        ):
            if target["name"] == "conformance":
                helper_name = (
                    "postgres-await-event-helper"
                    if package["name"] == "lash-internal-postgres-store"
                    else "sqlite-await-event-helper"
                )
                helper_target = next(
                    candidate for candidate in targets if candidate["name"] == helper_name
                )
                helper_label = f":{label_name(helper_target, False)}"
                test_env["LASH_CONFORMANCE_HELPER_EXE"] = (
                    f"$(rootpath {helper_label})"
                )
                extra_data.append(helper_label)
            if target["name"] in (
                "postgres-await-event-helper",
                "sqlite-await-event-helper",
            ):
                extra_compile_data.append("//crates/lash-core:cold_process_drivers")
            if target["name"] == "conformance":
                extra_compile_data.extend([
                    "//crates/lash-core:cold_process_turn_parent",
                    "//crates/lash-core:queued_claim_atomicity",
                ])
            if target["name"] == "durable_read_fixture":
                extra_compile_data.append("//crates/lash-core:durable_read_fixture_source")
        if (
            package["name"] == "lash-internal-postgres-store"
            and target["name"] == "preflight_durable_walk"
        ):
            extra_compile_data.append("//crates/lashlang:old_module_fixture")
        if package["name"] in (
            "lash-internal-postgres-store",
            "lash-internal-sqlite-store",
        ) and target["name"] == "durable_read_fixture":
            extra_compile_data.append("//:durable_fixtures")
        if package["name"] == "lash-sim" and kind == "test":
            extra_compile_data.extend([
                "//crates/lash-postgres-store:package_files",
                "//crates/lash-sqlite-store:package_files",
            ])
        macro = (
            "lash_rust_binary"
            if kind in ("bin", "example", "bench")
            else "lash_rust_integration_test"
        )
        crate_name = target["name"].replace("-", "_")
        target_tags, target_cargo_reason = cargo_test_policy(
            package["name"], kind, target["name"]
        )
        if kind == "bench":
            target_tags.append("manual")
        args = [
            f"    name = {quote(name)},",
            f"    crate_features = {string_list(target_features)},",
            f"    crate_name = {quote(crate_name)},",
            f"    crate_root = {quote(crate_root)},",
            f"    declared_features = {string_list(declared_features)},",
            f"    extra_compile_data = {string_list(extra_compile_data + binary_data)},",
        ]
        if kind in ("bin", "example", "bench"):
            args.append(f"    include_dev_deps = {str(kind in ('example', 'bench'))},")
        else:
            if extra_data:
                args.append(f"    extra_data = {string_list(extra_data)},")
            if test_env:
                args.append(f"    test_env = {json.dumps(test_env, sort_keys=True)},")
        args.extend([
            f"    library = {quote(library_label) if library_label else 'None'},",
            f"    library_crate_name = {quote(library_crate) if library_crate else 'None'},",
            f"    manifest_dir = {quote(package_dir)},",
            f"    package_name = {quote(package['name'])},",
            f"    rustc_env = {json.dumps(rustc_env, sort_keys=True)},",
            f"    tags = {string_list(sorted(set(target_tags)))},",
            f"    version = {quote(version)},",
        ])
        chunks.append(macro + "(\n" + "\n".join(args) + "\n)\n\n")
        target_inventory = {
            "cargo": target["name"],
            "kind": kind,
            "label": f"//{package_dir}:{name}",
            "tags": sorted(set(target_tags)),
        }
        if target_cargo_reason:
            target_inventory["cargo_only"] = target_cargo_reason
        inventory_targets.append(target_inventory)

        if kind == "bin" and target.get("test", False):
            bin_unit_tags, bin_unit_cargo_reason = cargo_test_policy(
                package["name"], "bin-unit-test", target["name"]
            )
            unit_args = [
                "lash_rust_unit_test(\n",
                f"    name = {quote(name + '__unit_test')},\n",
                f"    crate_features = {string_list(target_features)},\n",
                f"    crate_name = {quote(crate_name)},\n",
                f"    crate_root = {quote(crate_root)},\n",
                f"    declared_features = {string_list(declared_features)},\n",
            ]
            if extra_compile_data or binary_data:
                unit_args.append(
                    f"    extra_compile_data = {string_list(extra_compile_data + binary_data)},\n"
                )
            unit_args.extend([
                f"    library = {quote(library_label) if library_label else 'None'},\n"
                f"    library_crate_name = {quote(library_crate) if library_crate else 'None'},\n"
                f"    manifest_dir = {quote(package_dir)},\n"
                f"    package_name = {quote(package['name'])},\n"
                f"    tags = {string_list(bin_unit_tags)},\n"
                f"    version = {quote(version)},\n"
                ")\n\n"
            ])
            chunks.append("".join(unit_args))
            bin_unit_inventory = {
                "cargo": target["name"],
                "kind": "bin-unit-test",
                "label": f"//{package_dir}:{name}__unit_test",
                "tags": bin_unit_tags,
            }
            if bin_unit_cargo_reason:
                bin_unit_inventory["cargo_only"] = bin_unit_cargo_reason
            inventory_targets.append(bin_unit_inventory)

    if package["name"] == "lash-internal-core":
        chunks.append(
            "filegroup(\n"
            "    name = \"cold_process_drivers\",\n"
            "    srcs = [\n"
            "        \"tests/support/cold_process_effect_driver.rs\",\n"
            "        \"tests/support/cold_process_turn_driver.rs\",\n"
            "    ],\n"
            ")\n\n"
            "filegroup(\n"
            "    name = \"cold_process_turn_parent\",\n"
            "    srcs = [\"tests/support/cold_process_turn_parent.rs\"],\n"
            ")\n\n"
            "filegroup(\n"
            "    name = \"durable_read_fixture_source\",\n"
            "    srcs = [\"tests/support/durable_read_fixture.rs\"],\n"
            ")\n\n"
            "filegroup(\n"
            "    name = \"queued_claim_atomicity\",\n"
            "    srcs = [\"tests/support/queued_claim_atomicity.rs\"],\n"
            ")\n\n"
        )

    if package["name"] == "lash-internal-lashlang":
        chunks.append(
            "filegroup(\n"
            "    name = \"old_module_fixture\",\n"
            "    srcs = [\"tests/fixtures/module-artifact-old.json\"],\n"
            ")\n\n"
        )

    chunks.append(
        "filegroup(\n"
        "    name = \"rust_sources\",\n"
        "    srcs = glob([\"**/*.rs\"]),\n"
        ")\n\n"
        "filegroup(\n"
        "    name = \"package_files\",\n"
        "    srcs = glob([\"**\"], exclude = [\"BUILD\", \"BUILD.bazel\"]),\n"
        ")\n"
    )
    return "".join(chunks), {
        "declared_features": declared_features,
        "manifest": manifest,
        "package": package["name"],
        "resolved_features": features,
        "targets": inventory_targets,
    }


def generated(metadata: dict) -> tuple[dict[pathlib.Path, str], list[dict]]:
    features = package_features(metadata)
    outputs = {}
    inventory = []
    workspace_members = set(metadata["workspace_members"])
    for package in metadata["packages"]:
        manifest = pathlib.Path(package["manifest_path"]).resolve()
        if package["id"] not in workspace_members:
            continue
        content, item = render_package(package, features[package["id"]])
        outputs[manifest.parent / "BUILD.bazel"] = content
        inventory.append(item)
    inventory.sort(key=lambda item: item["manifest"])
    inventory_payload = {
        "cargo_package_count": len(inventory),
        "cargo_target_count": sum(
            1
            for package in metadata["packages"]
            if package["id"] in workspace_members
            for _target in package["targets"]
        ),
        "generated_label_count": sum(
            1
            for item in inventory
            for target in item["targets"]
            if target["label"] is not None
        ),
        "cargo_only_target_count": sum(
            1
            for item in inventory
            for target in item["targets"]
            if target["label"] is None
        ),
        "packages": inventory,
    }
    outputs[ROOT / "tools/bazel/target-inventory.json"] = (
        json.dumps(inventory_payload, indent=2, sort_keys=True) + "\n"
    )
    labels = [target for package in inventory for target in package["targets"]]
    executable_tests = [
        target
        for target in labels
        if target["label"] is not None
        and target["kind"] in ("bin-unit-test", "test", "unit-test")
    ]
    groups = {
        "WORKSPACE_COMPILE_TARGETS": sorted(
            target["label"]
            for target in labels
            if target["label"] is not None and target["kind"] != "doc-test"
        ),
        "WORKSPACE_DOCTEST_TARGETS": sorted(
            target["label"]
            for target in labels
            if target["label"] is not None and target["kind"] == "doc-test"
        ),
        "WORKSPACE_RUST_SOURCE_TARGETS": sorted(
            f"//{pathlib.PurePosixPath(package['manifest']).parent.as_posix()}:rust_sources"
            for package in inventory
        ),
        "WORKSPACE_BAZEL_TEST_TARGETS": sorted(
            target["label"]
            for target in executable_tests
            if "manual" not in target["tags"]
        ),
        "WORKSPACE_CARGO_TEST_TARGETS": sorted(
            target["label"] for target in executable_tests if "manual" in target["tags"]
        ),
        "WORKSPACE_TEST_TARGETS": sorted(
            target["label"] for target in executable_tests
        ),
    }
    bzl = [GENERATED_HEADER]
    for name, values in groups.items():
        bzl.append(f"{name} = {string_list(values, indent=4)}\n\n")
    outputs[ROOT / "tools/bazel/workspace_targets.bzl"] = "".join(bzl).rstrip() + "\n"
    cargo_nextest_terms = sorted(
        nextest_filter_term(package["package"], target)
        for package in inventory
        for target in package["targets"]
        if target.get("label") is not None
        and target["kind"] in ("bin-unit-test", "test", "unit-test")
        and "manual" in target["tags"]
    )
    outputs[ROOT / "tools/bazel/cargo_owned_nextest_filter.txt"] = (
        " + ".join(cargo_nextest_terms) + "\n"
    )
    return outputs, inventory


def check(outputs: dict[pathlib.Path, str]) -> int:
    stale = []
    for path, expected in outputs.items():
        if not path.exists() or path.read_text() != expected:
            stale.append(path.relative_to(ROOT).as_posix())
    if stale:
        print("stale Bazel build inventory:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs, _inventory = generated(cargo_metadata())
    if args.check:
        return check(outputs)
    for path, content in outputs.items():
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
