# @generated by tools/bazel/generate_build_files.py; do not edit.
# See the header of tools/bazel/generate_build_files.py: pool exec
# groups are how an aspect action carries a crate's measured request.

POOL_EXEC_GROUPS = {
    "pool_1_2097152": exec_group(),
    "pool_2_1572864": exec_group(),
    "pool_2_2097152": exec_group(),
    "pool_2_2621440": exec_group(),
    "pool_2_3145728": exec_group(),
    "pool_2_3670016": exec_group(),
    "pool_2_4194304": exec_group(),
    "pool_2_4718592": exec_group(),
    "pool_2_5242880": exec_group(),
}

POOL_EXEC_PROPERTIES = {
    "cpu_count": "1",
    "memory_kb": "1572864",
    "pool_1_2097152.cpu_count": "1",
    "pool_1_2097152.memory_kb": "2097152",
    "pool_2_1572864.cpu_count": "2",
    "pool_2_1572864.memory_kb": "1572864",
    "pool_2_2097152.cpu_count": "2",
    "pool_2_2097152.memory_kb": "2097152",
    "pool_2_2621440.cpu_count": "2",
    "pool_2_2621440.memory_kb": "2621440",
    "pool_2_3145728.cpu_count": "2",
    "pool_2_3145728.memory_kb": "3145728",
    "pool_2_3670016.cpu_count": "2",
    "pool_2_3670016.memory_kb": "3670016",
    "pool_2_4194304.cpu_count": "2",
    "pool_2_4194304.memory_kb": "4194304",
    "pool_2_4718592.cpu_count": "2",
    "pool_2_4718592.memory_kb": "4718592",
    "pool_2_5242880.cpu_count": "2",
    "pool_2_5242880.memory_kb": "5242880",
}
