#!/usr/bin/env bash
# Run one service-backed store suite, either from the shared Bazel cache or
# from a Cargo compile.
#
# Trusted events (`BAZEL_TRUSTED=true`) build the test binaries from the shared
# remote cache and execute them on this runner against the service the job
# stood up. Untrusted events -- fork and Dependabot pull requests -- never
# receive cache credentials, so they run exactly the Cargo commands that
# predate this cutover.
#
# Two properties hold for every Bazel invocation here and must keep holding:
#
#   * PostgreSQL version and connection settings reach the test only through
#     `--test_env`, which is part of the test spawn and of nothing else. Every
#     compile action key is therefore identical across the PG 14/16/18 matrix
#     legs, and the three jobs share one set of compiled outputs.
#   * The PostgreSQL conformance suite runs for several minutes against a real
#     database, and Cargo imposes no per-binary bound. Bazel's default is 300
#     seconds, so `--test_timeout` restores the Cargo shape; the job's
#     `timeout-minutes` remains the real bound.
#   * `--nocache_test_results` plus `no-cache`/`no-remote-cache` on the
#     `TestRunner` mnemonic means a service-backed test RESULT is never read
#     from, and never written to, the shared cache. A cached green for a test
#     whose verdict depends on a live database is a false green. The
#     `--modify_execution_info` filter is scoped to `TestRunner` precisely so
#     the compile actions above it stay cacheable.
#   * `no-remote-exec` on the same mnemonic keeps the test spawn on this
#     runner. The service this job stood up listens on the runner's loopback
#     and exists nowhere else, so a test action dispatched to the execution
#     pool would have no database or bucket to talk to. Only the compile
#     actions below it are submitted to the pool.
#
# Usage: scripts/ci/store-tests.sh <suite>
set -euo pipefail

suite="${1:?usage: store-tests.sh <suite>}"
trusted="${BAZEL_TRUSTED:?BAZEL_TRUSTED must be 'true' or 'false'}"
# CI exports both of these from .github/actions/bazel-shared-cache, and there
# they must stay required: an unset value would mean the credentials step did
# not run and the build would silently miss the shared cache. Outside CI --
# `scripts/ci/with-service.sh`, the same wrapper CI's store jobs use to start a
# container and then run these same suites -- the shared cache is configured by
# the checkout's .bazelrc and .kiln.bazelrc instead, so the defaults below name
# exactly what `kiln build` uses and the output base the .bazelrc `startup` line
# already pins.
if [ -n "${GITHUB_ACTIONS:-}" ]; then
  : "${BAZEL_SHARED_CACHE_FLAGS:?BAZEL_SHARED_CACHE_FLAGS must be set in CI}"
  : "${BAZEL_OUTPUT_USER_ROOT:?BAZEL_OUTPUT_USER_ROOT must be set in CI}"
fi
# `--config=shared` is the same pool configuration `kiln build` uses, so the
# compiles below are shared-cache hits and pool actions. The test spawn itself
# must stay on this machine: the service container publishes its port on this
# host's loopback, and a TestRunner action on a pool worker would reach nothing.
: "${BAZEL_SHARED_CACHE_FLAGS=--config=shared --strategy=TestRunner=local}"
case "${trusted}" in
  true | false) ;;
  *)
    echo "invalid Bazel trust decision: ${trusted}" >&2
    exit 1
    ;;
esac

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

bazel_test() {
  local startup=()
  if [ -n "${BAZEL_OUTPUT_USER_ROOT:-}" ]; then
    startup=(--output_user_root="${BAZEL_OUTPUT_USER_ROOT}")
  fi
  # shellcheck disable=SC2086
  bazel "${startup[@]}" test \
    ${BAZEL_SHARED_CACHE_FLAGS} \
    --nocache_test_results \
    --modify_execution_info=TestRunner=+no-cache,TestRunner=+no-remote-cache,TestRunner=+no-remote-exec \
    --local_test_jobs=1 \
    --test_timeout=1200 \
    --test_output=errors \
    --test_env=LASH_POSTGRES_DATABASE_URL \
    --test_env=LASH_REQUIRE_POSTGRES \
    --test_env=LASH_REQUIRE_MINIO \
    --test_env=LASH_MINIO_ENDPOINT \
    --test_env=LASH_MINIO_REGION \
    --test_env=LASH_MINIO_BUCKET \
    --test_env=LASH_MINIO_ACCESS_KEY \
    --test_env=LASH_MINIO_SECRET_KEY \
    --test_env=LASH_CROSS_BACKEND_CASES \
    "$@"
}

labels() {
  # Generated by tools/bazel/generate_build_files.py: a new service-gated
  # binary joins its service job without a hand edit here.
  tr '\n' ' ' <"tools/bazel/$1_test_labels.txt"
}

case "${suite}" in
  # The compatibility lanes provision the published DDL and compare its live
  # catalog rendering byte-for-byte with schema-shape.txt. The second test is a
  # distinct version-stamp gate.
  pg-catalog-compatibility)
    if [ "${trusted}" = true ]; then
      bazel_test --test_arg=committed_shape_artifact_matches_the_ddl_artifact \
        //crates/lash-postgres-store:lash-postgres-store__unit_test
      bazel_test \
        --test_arg=a_mismatched_version_stamp_is_reported_without_a_column_diff \
        //crates/lash-postgres-store:schema_drift__test
    else
      cargo test -p lash-internal-postgres-store --locked --lib \
        committed_shape_artifact_matches_the_ddl_artifact
      cargo test -p lash-internal-postgres-store --locked --test schema_drift \
        a_mismatched_version_stamp_is_reported_without_a_column_diff
    fi
    ;;

  # Package-wide by design: tests/attempt_atomicity.rs is part of this gate, so
  # narrowing to the conformance binary would silently drop attempt atomicity.
  # The suites self-serialize on a per-process guard and share one database, so
  # the binaries must not overlap: Cargo runs them one at a time, and
  # `--local_test_jobs=1` makes Bazel do the same.
  pg-store)
    if [ "${trusted}" = true ]; then
      # shellcheck disable=SC2046
      bazel_test $(labels postgres)
    else
      cargo test -p lash-internal-postgres-store --locked
    fi
    ;;

  pg-pool-wait)
    if [ "${trusted}" = true ]; then
      bazel_test --test_arg=pool_wait //crates/lash-perf:lash-perf__unit_test
    else
      cargo nextest run -p lash-perf -E 'test(pool_wait)' --locked
    fi
    ;;

  # The per-PR PostgreSQL agent-scenario slot. It used to name the facade
  # Agent Scenario that drove a Lashlang process graph through a ParentEnd
  # fault; the parent-end ledger replaced that scenario, and the property now
  # lives in the store's own crash-recovery test. Keep this leg stable and
  # focused on one named test: a libtest filter that matches nothing exits 0,
  # so the name must always be a test that exists.
  pg-agent-scenario)
    if [ "${trusted}" = true ]; then
      bazel_test \
        --test_arg=public_provider_parent_end_row_is_recovered_after_a_crash_before_the_ledger_write_on_postgres \
        //crates/lash-postgres-store:integration__test
    else
      cargo nextest run --profile ci -p lash-internal-postgres-store \
        --test integration --locked -E \
        'test(public_provider_parent_end_row_is_recovered_after_a_crash_before_the_ledger_write_on_postgres)'
    fi
    ;;

  # The simulator's backend-fault plan against a real PostgreSQL: the same
  # commit-boundary scenarios the SQLite lane runs, driven through
  # `lash_postgres_store::testing::PostgresFaultInjector`. The test skips itself
  # without a database URL, and LASH_REQUIRE_POSTGRES=1 turns a missing URL into
  # a panic, so a missing CI variable cannot silently pass this lane.
  pg-sim-backend-faults)
    if [ "${trusted}" = true ]; then
      bazel_test --test_arg=postgres_backend_fault \
        //crates/lash-sim:lash-sim__unit_test
    else
      cargo nextest run --profile ci -p lash-sim --lib --locked \
        -E 'test(postgres_backend_fault)'
    fi
    ;;

  # The full differential compares backend semantics, not catalog rendering, so
  # it runs once on the primary major instead of three times. `--run-ignored
  # all` is libtest's `--include-ignored`; `-j1` is `--test-threads=1`;
  # `--no-capture` is `--nocapture`.
  pg-cross-backend)
    if [ "${trusted}" = true ]; then
      bazel_test \
        --test_arg=--include-ignored \
        --test_arg=--test-threads=1 \
        --test_arg=--nocapture \
        --test_output=all \
        //crates/lash-sim:cross_backend_store_differential__test
    else
      cargo nextest run --profile ci -p lash-sim \
        --test cross_backend_store_differential \
        --locked -j1 --no-capture --run-ignored all
    fi
    ;;

  s3-store)
    if [ "${trusted}" = true ]; then
      # shellcheck disable=SC2046
      bazel_test $(labels minio)
    else
      cargo test -p lash-internal-s3-store --locked
    fi
    ;;

  s3-attachment-differential)
    if [ "${trusted}" = true ]; then
      bazel_test \
        --test_arg=attachment_blob_store_differential_agrees \
        --test_arg=--include-ignored \
        --test_arg=--nocapture \
        --test_output=all \
        //crates/lash-sim:cross_backend_store_differential__test
    else
      cargo test -p lash-sim \
        --test cross_backend_store_differential \
        --locked attachment_blob_store_differential_agrees -- --nocapture --include-ignored
    fi
    ;;

  *)
    echo "unknown store suite: ${suite}" >&2
    exit 1
    ;;
esac
