//! Named backend test registration. Every invocation gets a fresh fixture.

/// Register one independently reported test per runtime persistence vector.
#[macro_export]
macro_rules! runtime_persistence_tests {
    ($runner:ident) => {
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_increments_head_and_round_trips_agent_frames() { $runner($crate::RuntimePersistenceLaw::commit_increments_head_and_round_trips_agent_frames).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_head_revision_cas_applies_exactly_once() { $runner($crate::RuntimePersistenceLaw::concurrent_head_revision_cas_applies_exactly_once).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_a_different_session_id() { $runner($crate::RuntimePersistenceLaw::commit_rejects_a_different_session_id).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_carried_nondefault_node_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_carried_nondefault_node_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_carried_nondefault_byte_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_carried_nondefault_byte_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_queue_batch_bytes_over_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_queue_batch_bytes_over_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_agent_frame_bytes_over_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_agent_frame_bytes_over_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_usage_delta_bytes_over_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_usage_delta_bytes_over_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_turn_result_bytes_over_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_turn_result_bytes_over_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_with_every_payload_family_inside_budget_succeeds() { $runner($crate::RuntimePersistenceLaw::commit_with_every_payload_family_inside_budget_succeeds).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn load_hydrates_checkpoint_and_usage() { $runner($crate::RuntimePersistenceLaw::load_hydrates_checkpoint_and_usage).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn load_retains_reasoning_only_usage() { $runner($crate::RuntimePersistenceLaw::load_retains_reasoning_only_usage).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_restore_rejects_turn_index_without_increment_headroom() { $runner($crate::RuntimePersistenceLaw::checkpoint_restore_rejects_turn_index_without_increment_headroom).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_restore_rejects_token_usage_whose_prompt_subtotal_overflows() { $runner($crate::RuntimePersistenceLaw::checkpoint_restore_rejects_token_usage_whose_prompt_subtotal_overflows).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn load_rejects_token_usage_overflow() { $runner($crate::RuntimePersistenceLaw::load_rejects_token_usage_overflow).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn usage_delta_identity_is_idempotent_across_commits() { $runner($crate::RuntimePersistenceLaw::usage_delta_identity_is_idempotent_across_commits).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn usage_ordinal_reuse_with_different_payload_survives_receipt_replay() { $runner($crate::RuntimePersistenceLaw::usage_ordinal_reuse_with_different_payload_survives_receipt_replay).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn execution_state_replace_then_clear_removes_the_live_checkpoint_ref() { $runner($crate::RuntimePersistenceLaw::execution_state_replace_then_clear_removes_the_live_checkpoint_ref).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_rejects_unknown_component_ref() { $runner($crate::RuntimePersistenceLaw::checkpoint_rejects_unknown_component_ref).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_read_loads_persisted_history() { $runner($crate::RuntimePersistenceLaw::session_read_loads_persisted_history).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_prompt_layer_round_trips_through_the_committed_head() { $runner($crate::RuntimePersistenceLaw::session_prompt_layer_round_trips_through_the_committed_head).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_protocol_turn_options_round_trip_through_the_committed_head() { $runner($crate::RuntimePersistenceLaw::session_protocol_turn_options_round_trip_through_the_committed_head).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_metadata_round_trips() { $runner($crate::RuntimePersistenceLaw::session_metadata_round_trips).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn attachment_manifest_records_intent_and_commit_stamps() { $runner($crate::RuntimePersistenceLaw::attachment_manifest_records_intent_and_commit_stamps).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn attachment_manifest_keeps_same_content_ownership_per_session() { $runner($crate::RuntimePersistenceLaw::attachment_manifest_keeps_same_content_ownership_per_session).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn attachment_manifest_reference_tracking_and_gc_root_set() { $runner($crate::RuntimePersistenceLaw::attachment_manifest_reference_tracking_and_gc_root_set).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn final_commit_stamp_is_idempotent_and_conflicts_on_changed_hash() { $runner($crate::RuntimePersistenceLaw::final_commit_stamp_is_idempotent_and_conflicts_on_changed_hash).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_request_receipt_replays_after_head_advance() { $runner($crate::RuntimePersistenceLaw::append_request_receipt_replays_after_head_advance).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_request_receipt_rejects_changed_content() { $runner($crate::RuntimePersistenceLaw::append_request_receipt_rejects_changed_content).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_request_exact_hash_rejects_changed_ancestor() { $runner($crate::RuntimePersistenceLaw::append_request_exact_hash_rejects_changed_ancestor).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_request_receipt_rejects_corrupt_node_count() { $runner($crate::RuntimePersistenceLaw::append_request_receipt_rejects_corrupt_node_count).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_same_append_operation_applies_exactly_once() { $runner($crate::RuntimePersistenceLaw::concurrent_same_append_operation_applies_exactly_once).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn legacy_append_receipt_keeps_exact_hash_semantics() { $runner($crate::RuntimePersistenceLaw::legacy_append_receipt_keeps_exact_hash_semantics).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_receipt_encoding_version_mismatch_keeps_exact_hash_semantics() { $runner($crate::RuntimePersistenceLaw::append_receipt_encoding_version_mismatch_keeps_exact_hash_semantics).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_receipt_and_graph_append_are_atomic() { $runner($crate::RuntimePersistenceLaw::append_receipt_and_graph_append_are_atomic).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn fresh_append_receipt_enforces_ancestor_precondition() { $runner($crate::RuntimePersistenceLaw::fresh_append_receipt_enforces_ancestor_precondition).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn store_computed_hash_rejects_mutated_commit() { $runner($crate::RuntimePersistenceLaw::store_computed_hash_rejects_mutated_commit).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_non_derived_append_node_ids() { $runner($crate::RuntimePersistenceLaw::commit_rejects_non_derived_append_node_ids).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_rejects_duplicate_batch_node_ids() { $runner($crate::RuntimePersistenceLaw::append_rejects_duplicate_batch_node_ids).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_rejects_existing_node_id_collision() { $runner($crate::RuntimePersistenceLaw::append_rejects_existing_node_id_collision).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn head_retirement_gate_distinguishes_leaf_change_from_same_leaf() { $runner($crate::RuntimePersistenceLaw::head_retirement_gate_distinguishes_leaf_change_from_same_leaf).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_unresolvable_leaf() { $runner($crate::RuntimePersistenceLaw::commit_rejects_unresolvable_leaf).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_missing_leaf() { $runner($crate::RuntimePersistenceLaw::commit_rejects_missing_leaf).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn empty_append_cannot_move_the_head() { $runner($crate::RuntimePersistenceLaw::empty_append_cannot_move_the_head).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_leaf_without_frame_open_ancestor() { $runner($crate::RuntimePersistenceLaw::commit_rejects_leaf_without_frame_open_ancestor).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_contract() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn borrowed_session_execution_lease_commit_contract() { $runner($crate::RuntimePersistenceLaw::borrowed_session_execution_lease_commit_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn same_incarnation_rotation_gates_claims_not_commits() { $runner($crate::RuntimePersistenceLaw::same_incarnation_rotation_gates_claims_not_commits).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn same_host_distinct_executors_are_lane_less_without_revoking_holder() { $runner($crate::RuntimePersistenceLaw::same_host_distinct_executors_are_lane_less_without_revoking_holder).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_fence_authority() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_fence_authority).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_session_execution_lease_rotation_and_stale_renewal_are_linearizable() { $runner($crate::RuntimePersistenceLaw::concurrent_session_execution_lease_rotation_and_stale_renewal_are_linearizable).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_expires_by_ttl_contract() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_expires_by_ttl_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn durable_queued_drain_wait_store_laws() { $runner($crate::RuntimePersistenceLaw::durable_queued_drain_wait_store_laws).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_diagnostic_read_contract() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_diagnostic_read_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_displacement_contract() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_displacement_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_source_keys_are_idempotent_and_list_ordered() { $runner($crate::RuntimePersistenceLaw::queued_work_source_keys_are_idempotent_and_list_ordered).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_queued_work_source_key_enqueues_report_one_inserted_and_one_existing() { $runner($crate::RuntimePersistenceLaw::concurrent_queued_work_source_key_enqueues_report_one_inserted_and_one_existing).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn decorated_queued_work_source_key_replay_reports_absorbed() { $runner($crate::RuntimePersistenceLaw::decorated_queued_work_source_key_replay_reports_absorbed).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_session_work_ordering_agrees_across_ingress_families() { $runner($crate::RuntimePersistenceLaw::pending_session_work_ordering_agrees_across_ingress_families).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_queue_and_turn_input_claims_have_one_owner() { $runner($crate::RuntimePersistenceLaw::concurrent_queue_and_turn_input_claims_have_one_owner).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_work_claims_both_families_once() { $runner($crate::RuntimePersistenceLaw::checkpoint_work_claims_both_families_once).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_budget_refusal_preserves_active_turn_input() { $runner($crate::RuntimePersistenceLaw::checkpoint_budget_refusal_preserves_active_turn_input).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_claims_honor_min_boundary_at_every_checkpoint() { $runner($crate::RuntimePersistenceLaw::checkpoint_claims_honor_min_boundary_at_every_checkpoint).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_cancel_removes_only_unclaimed_batches() { $runner($crate::RuntimePersistenceLaw::queued_work_cancel_removes_only_unclaimed_batches).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_exact_claim_uses_selected_batch_ids() { $runner($crate::RuntimePersistenceLaw::queued_work_exact_claim_uses_selected_batch_ids).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_classes_gate_command_and_turn_claims() { $runner($crate::RuntimePersistenceLaw::queued_work_classes_gate_command_and_turn_claims).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_claims_respect_boundaries_abandon_and_stale_completion() { $runner($crate::RuntimePersistenceLaw::queued_work_claims_respect_boundaries_abandon_and_stale_completion).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_claims_supersede_across_session_lease_generations_with_timing() { $runner($crate::RuntimePersistenceLaw::queued_work_claims_supersede_across_session_lease_generations_with_timing).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn claim_liveness_for_lease_less_paths_tracks_session_generations() { $runner($crate::RuntimePersistenceLaw::claim_liveness_for_lease_less_paths_tracks_session_generations).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn same_generation_claim_scans_reach_rows_beyond_the_scan_surplus() { $runner($crate::RuntimePersistenceLaw::same_generation_claim_scans_reach_rows_beyond_the_scan_surplus).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_respects_membership_limits_exclusivity_reclaim_and_sessions() { $runner($crate::RuntimePersistenceLaw::queued_work_respects_membership_limits_exclusivity_reclaim_and_sessions).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_join_groups_by_delivery_policy_and_merge_key() { $runner($crate::RuntimePersistenceLaw::queued_work_join_groups_by_delivery_policy_and_merge_key).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn abandoned_predecessor_claim_pair_is_only_reclaimable_across_lease_generations() { $runner($crate::RuntimePersistenceLaw::abandoned_predecessor_claim_pair_is_only_reclaimable_across_lease_generations).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_preserves_interrupted_batch_composition() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_preserves_interrupted_batch_composition).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_names_a_deferred_lane_apart_from_an_exhausted_one() { $runner($crate::RuntimePersistenceLaw::queued_work_names_a_deferred_lane_apart_from_an_exhausted_one).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_selects_claim_identity_across_ready_gap() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_selects_claim_identity_across_ready_gap).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_obeys_delivery_boundary_before_identity() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_obeys_delivery_boundary_before_identity).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_ignores_successor_row_limit() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_ignores_successor_row_limit).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_ignores_a_changed_drain_policy() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_ignores_a_changed_drain_policy).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_selected_multi_identity_validation_and_abandon_restore() { $runner($crate::RuntimePersistenceLaw::queued_work_selected_multi_identity_validation_and_abandon_restore).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_exact_claim_preserves_physical_order_and_key_breaks() { $runner($crate::RuntimePersistenceLaw::queued_work_exact_claim_preserves_physical_order_and_key_breaks).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn process_wakes_batch_by_default() { $runner($crate::RuntimePersistenceLaw::process_wakes_batch_by_default).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_completion_is_lease_guarded() { $runner($crate::RuntimePersistenceLaw::queued_work_completion_is_lease_guarded).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_wake_delivery_is_source_key_idempotent_and_claimed_once() { $runner($crate::RuntimePersistenceLaw::queued_wake_delivery_is_source_key_idempotent_and_claimed_once).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queue_completion_and_turn_commit_stamp_are_atomic() { $runner($crate::RuntimePersistenceLaw::queue_completion_and_turn_commit_stamp_are_atomic).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_turn_inputs_source_keys_order_cancel_and_cross_session() { $runner($crate::RuntimePersistenceLaw::pending_turn_inputs_source_keys_order_cancel_and_cross_session).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_turn_input_bulk_and_suffix_cancellation() { $runner($crate::RuntimePersistenceLaw::pending_turn_input_bulk_and_suffix_cancellation).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_turn_input_claims_reclaim_complete_and_fence() { $runner($crate::RuntimePersistenceLaw::pending_turn_input_claims_reclaim_complete_and_fence).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn turn_input_application_identity_survives_pending_tombstone_vacuum() { $runner($crate::RuntimePersistenceLaw::turn_input_application_identity_survives_pending_tombstone_vacuum).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn turn_input_claims_supersede_across_session_lease_generations_with_timing() { $runner($crate::RuntimePersistenceLaw::turn_input_claims_supersede_across_session_lease_generations_with_timing).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn active_turn_input_claim_reacquires_after_unrecorded_checkpoint() { $runner($crate::RuntimePersistenceLaw::active_turn_input_claim_reacquires_after_unrecorded_checkpoint).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_turn_input_cancel_covers_active_and_deferred_states() { $runner($crate::RuntimePersistenceLaw::pending_turn_input_cancel_covers_active_and_deferred_states).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_active_turn_inputs_defer_unaccepted_once_on_interrupt() { $runner($crate::RuntimePersistenceLaw::pending_active_turn_inputs_defer_unaccepted_once_on_interrupt).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn a_turn_that_cannot_commit_leaves_no_input_pinned_to_it() { $runner($crate::RuntimePersistenceLaw::a_turn_that_cannot_commit_leaves_no_input_pinned_to_it).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn fresh_instances() { $runner($crate::RuntimePersistenceLaw::fresh_instances).await; }
    };
}
/// Register one independently reported test per runtime persistence vector.
#[macro_export]
macro_rules! runtime_persistence_reopenable_tests {
    ($runner:ident) => {
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_increments_head_and_round_trips_agent_frames() { $runner($crate::RuntimePersistenceLaw::commit_increments_head_and_round_trips_agent_frames).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_head_revision_cas_applies_exactly_once() { $runner($crate::RuntimePersistenceLaw::concurrent_head_revision_cas_applies_exactly_once).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_a_different_session_id() { $runner($crate::RuntimePersistenceLaw::commit_rejects_a_different_session_id).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_carried_nondefault_node_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_carried_nondefault_node_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_carried_nondefault_byte_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_carried_nondefault_byte_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_queue_batch_bytes_over_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_queue_batch_bytes_over_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_agent_frame_bytes_over_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_agent_frame_bytes_over_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_usage_delta_bytes_over_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_usage_delta_bytes_over_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_turn_result_bytes_over_budget() { $runner($crate::RuntimePersistenceLaw::commit_rejects_turn_result_bytes_over_budget).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_with_every_payload_family_inside_budget_succeeds() { $runner($crate::RuntimePersistenceLaw::commit_with_every_payload_family_inside_budget_succeeds).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn load_hydrates_checkpoint_and_usage() { $runner($crate::RuntimePersistenceLaw::load_hydrates_checkpoint_and_usage).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn load_retains_reasoning_only_usage() { $runner($crate::RuntimePersistenceLaw::load_retains_reasoning_only_usage).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_restore_rejects_turn_index_without_increment_headroom() { $runner($crate::RuntimePersistenceLaw::checkpoint_restore_rejects_turn_index_without_increment_headroom).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_restore_rejects_token_usage_whose_prompt_subtotal_overflows() { $runner($crate::RuntimePersistenceLaw::checkpoint_restore_rejects_token_usage_whose_prompt_subtotal_overflows).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn load_rejects_token_usage_overflow() { $runner($crate::RuntimePersistenceLaw::load_rejects_token_usage_overflow).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn usage_delta_identity_is_idempotent_across_commits() { $runner($crate::RuntimePersistenceLaw::usage_delta_identity_is_idempotent_across_commits).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn usage_ordinal_reuse_with_different_payload_survives_receipt_replay() { $runner($crate::RuntimePersistenceLaw::usage_ordinal_reuse_with_different_payload_survives_receipt_replay).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn execution_state_replace_then_clear_removes_the_live_checkpoint_ref() { $runner($crate::RuntimePersistenceLaw::execution_state_replace_then_clear_removes_the_live_checkpoint_ref).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_rejects_unknown_component_ref() { $runner($crate::RuntimePersistenceLaw::checkpoint_rejects_unknown_component_ref).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_read_loads_persisted_history() { $runner($crate::RuntimePersistenceLaw::session_read_loads_persisted_history).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_prompt_layer_round_trips_through_the_committed_head() { $runner($crate::RuntimePersistenceLaw::session_prompt_layer_round_trips_through_the_committed_head).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_protocol_turn_options_round_trip_through_the_committed_head() { $runner($crate::RuntimePersistenceLaw::session_protocol_turn_options_round_trip_through_the_committed_head).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_metadata_round_trips() { $runner($crate::RuntimePersistenceLaw::session_metadata_round_trips).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn attachment_manifest_records_intent_and_commit_stamps() { $runner($crate::RuntimePersistenceLaw::attachment_manifest_records_intent_and_commit_stamps).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn attachment_manifest_keeps_same_content_ownership_per_session() { $runner($crate::RuntimePersistenceLaw::attachment_manifest_keeps_same_content_ownership_per_session).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn attachment_manifest_reference_tracking_and_gc_root_set() { $runner($crate::RuntimePersistenceLaw::attachment_manifest_reference_tracking_and_gc_root_set).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn final_commit_stamp_is_idempotent_and_conflicts_on_changed_hash() { $runner($crate::RuntimePersistenceLaw::final_commit_stamp_is_idempotent_and_conflicts_on_changed_hash).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_request_receipt_replays_after_head_advance() { $runner($crate::RuntimePersistenceLaw::append_request_receipt_replays_after_head_advance).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_request_receipt_rejects_changed_content() { $runner($crate::RuntimePersistenceLaw::append_request_receipt_rejects_changed_content).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_request_exact_hash_rejects_changed_ancestor() { $runner($crate::RuntimePersistenceLaw::append_request_exact_hash_rejects_changed_ancestor).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_request_receipt_rejects_corrupt_node_count() { $runner($crate::RuntimePersistenceLaw::append_request_receipt_rejects_corrupt_node_count).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_same_append_operation_applies_exactly_once() { $runner($crate::RuntimePersistenceLaw::concurrent_same_append_operation_applies_exactly_once).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn legacy_append_receipt_keeps_exact_hash_semantics() { $runner($crate::RuntimePersistenceLaw::legacy_append_receipt_keeps_exact_hash_semantics).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_receipt_encoding_version_mismatch_keeps_exact_hash_semantics() { $runner($crate::RuntimePersistenceLaw::append_receipt_encoding_version_mismatch_keeps_exact_hash_semantics).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_receipt_and_graph_append_are_atomic() { $runner($crate::RuntimePersistenceLaw::append_receipt_and_graph_append_are_atomic).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn fresh_append_receipt_enforces_ancestor_precondition() { $runner($crate::RuntimePersistenceLaw::fresh_append_receipt_enforces_ancestor_precondition).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn store_computed_hash_rejects_mutated_commit() { $runner($crate::RuntimePersistenceLaw::store_computed_hash_rejects_mutated_commit).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_non_derived_append_node_ids() { $runner($crate::RuntimePersistenceLaw::commit_rejects_non_derived_append_node_ids).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_rejects_duplicate_batch_node_ids() { $runner($crate::RuntimePersistenceLaw::append_rejects_duplicate_batch_node_ids).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_rejects_existing_node_id_collision() { $runner($crate::RuntimePersistenceLaw::append_rejects_existing_node_id_collision).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn head_retirement_gate_distinguishes_leaf_change_from_same_leaf() { $runner($crate::RuntimePersistenceLaw::head_retirement_gate_distinguishes_leaf_change_from_same_leaf).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_unresolvable_leaf() { $runner($crate::RuntimePersistenceLaw::commit_rejects_unresolvable_leaf).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_missing_leaf() { $runner($crate::RuntimePersistenceLaw::commit_rejects_missing_leaf).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn empty_append_cannot_move_the_head() { $runner($crate::RuntimePersistenceLaw::empty_append_cannot_move_the_head).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn commit_rejects_leaf_without_frame_open_ancestor() { $runner($crate::RuntimePersistenceLaw::commit_rejects_leaf_without_frame_open_ancestor).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_contract() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn borrowed_session_execution_lease_commit_contract() { $runner($crate::RuntimePersistenceLaw::borrowed_session_execution_lease_commit_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn same_incarnation_rotation_gates_claims_not_commits() { $runner($crate::RuntimePersistenceLaw::same_incarnation_rotation_gates_claims_not_commits).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn same_host_distinct_executors_are_lane_less_without_revoking_holder() { $runner($crate::RuntimePersistenceLaw::same_host_distinct_executors_are_lane_less_without_revoking_holder).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_fence_authority() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_fence_authority).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_session_execution_lease_rotation_and_stale_renewal_are_linearizable() { $runner($crate::RuntimePersistenceLaw::concurrent_session_execution_lease_rotation_and_stale_renewal_are_linearizable).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_expires_by_ttl_contract() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_expires_by_ttl_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn durable_queued_drain_wait_store_laws() { $runner($crate::RuntimePersistenceLaw::durable_queued_drain_wait_store_laws).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_diagnostic_read_contract() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_diagnostic_read_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn session_execution_lease_displacement_contract() { $runner($crate::RuntimePersistenceLaw::session_execution_lease_displacement_contract).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_source_keys_are_idempotent_and_list_ordered() { $runner($crate::RuntimePersistenceLaw::queued_work_source_keys_are_idempotent_and_list_ordered).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_queued_work_source_key_enqueues_report_one_inserted_and_one_existing() { $runner($crate::RuntimePersistenceLaw::concurrent_queued_work_source_key_enqueues_report_one_inserted_and_one_existing).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn decorated_queued_work_source_key_replay_reports_absorbed() { $runner($crate::RuntimePersistenceLaw::decorated_queued_work_source_key_replay_reports_absorbed).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_session_work_ordering_agrees_across_ingress_families() { $runner($crate::RuntimePersistenceLaw::pending_session_work_ordering_agrees_across_ingress_families).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn concurrent_queue_and_turn_input_claims_have_one_owner() { $runner($crate::RuntimePersistenceLaw::concurrent_queue_and_turn_input_claims_have_one_owner).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_work_claims_both_families_once() { $runner($crate::RuntimePersistenceLaw::checkpoint_work_claims_both_families_once).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_budget_refusal_preserves_active_turn_input() { $runner($crate::RuntimePersistenceLaw::checkpoint_budget_refusal_preserves_active_turn_input).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn checkpoint_claims_honor_min_boundary_at_every_checkpoint() { $runner($crate::RuntimePersistenceLaw::checkpoint_claims_honor_min_boundary_at_every_checkpoint).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_cancel_removes_only_unclaimed_batches() { $runner($crate::RuntimePersistenceLaw::queued_work_cancel_removes_only_unclaimed_batches).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_exact_claim_uses_selected_batch_ids() { $runner($crate::RuntimePersistenceLaw::queued_work_exact_claim_uses_selected_batch_ids).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_classes_gate_command_and_turn_claims() { $runner($crate::RuntimePersistenceLaw::queued_work_classes_gate_command_and_turn_claims).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_claims_respect_boundaries_abandon_and_stale_completion() { $runner($crate::RuntimePersistenceLaw::queued_work_claims_respect_boundaries_abandon_and_stale_completion).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_claims_supersede_across_session_lease_generations_with_timing() { $runner($crate::RuntimePersistenceLaw::queued_work_claims_supersede_across_session_lease_generations_with_timing).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn claim_liveness_for_lease_less_paths_tracks_session_generations() { $runner($crate::RuntimePersistenceLaw::claim_liveness_for_lease_less_paths_tracks_session_generations).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn same_generation_claim_scans_reach_rows_beyond_the_scan_surplus() { $runner($crate::RuntimePersistenceLaw::same_generation_claim_scans_reach_rows_beyond_the_scan_surplus).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_respects_membership_limits_exclusivity_reclaim_and_sessions() { $runner($crate::RuntimePersistenceLaw::queued_work_respects_membership_limits_exclusivity_reclaim_and_sessions).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_join_groups_by_delivery_policy_and_merge_key() { $runner($crate::RuntimePersistenceLaw::queued_work_join_groups_by_delivery_policy_and_merge_key).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn abandoned_predecessor_claim_pair_is_only_reclaimable_across_lease_generations() { $runner($crate::RuntimePersistenceLaw::abandoned_predecessor_claim_pair_is_only_reclaimable_across_lease_generations).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_preserves_interrupted_batch_composition() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_preserves_interrupted_batch_composition).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_names_a_deferred_lane_apart_from_an_exhausted_one() { $runner($crate::RuntimePersistenceLaw::queued_work_names_a_deferred_lane_apart_from_an_exhausted_one).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_selects_claim_identity_across_ready_gap() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_selects_claim_identity_across_ready_gap).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_obeys_delivery_boundary_before_identity() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_obeys_delivery_boundary_before_identity).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_ignores_successor_row_limit() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_ignores_successor_row_limit).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_redrive_ignores_a_changed_drain_policy() { $runner($crate::RuntimePersistenceLaw::queued_work_redrive_ignores_a_changed_drain_policy).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_selected_multi_identity_validation_and_abandon_restore() { $runner($crate::RuntimePersistenceLaw::queued_work_selected_multi_identity_validation_and_abandon_restore).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_exact_claim_preserves_physical_order_and_key_breaks() { $runner($crate::RuntimePersistenceLaw::queued_work_exact_claim_preserves_physical_order_and_key_breaks).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn process_wakes_batch_by_default() { $runner($crate::RuntimePersistenceLaw::process_wakes_batch_by_default).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_work_completion_is_lease_guarded() { $runner($crate::RuntimePersistenceLaw::queued_work_completion_is_lease_guarded).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queued_wake_delivery_is_source_key_idempotent_and_claimed_once() { $runner($crate::RuntimePersistenceLaw::queued_wake_delivery_is_source_key_idempotent_and_claimed_once).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn queue_completion_and_turn_commit_stamp_are_atomic() { $runner($crate::RuntimePersistenceLaw::queue_completion_and_turn_commit_stamp_are_atomic).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_turn_inputs_source_keys_order_cancel_and_cross_session() { $runner($crate::RuntimePersistenceLaw::pending_turn_inputs_source_keys_order_cancel_and_cross_session).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_turn_input_bulk_and_suffix_cancellation() { $runner($crate::RuntimePersistenceLaw::pending_turn_input_bulk_and_suffix_cancellation).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_turn_input_claims_reclaim_complete_and_fence() { $runner($crate::RuntimePersistenceLaw::pending_turn_input_claims_reclaim_complete_and_fence).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn turn_input_application_identity_survives_pending_tombstone_vacuum() { $runner($crate::RuntimePersistenceLaw::turn_input_application_identity_survives_pending_tombstone_vacuum).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn turn_input_claims_supersede_across_session_lease_generations_with_timing() { $runner($crate::RuntimePersistenceLaw::turn_input_claims_supersede_across_session_lease_generations_with_timing).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn active_turn_input_claim_reacquires_after_unrecorded_checkpoint() { $runner($crate::RuntimePersistenceLaw::active_turn_input_claim_reacquires_after_unrecorded_checkpoint).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_turn_input_cancel_covers_active_and_deferred_states() { $runner($crate::RuntimePersistenceLaw::pending_turn_input_cancel_covers_active_and_deferred_states).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn pending_active_turn_inputs_defer_unaccepted_once_on_interrupt() { $runner($crate::RuntimePersistenceLaw::pending_active_turn_inputs_defer_unaccepted_once_on_interrupt).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn a_turn_that_cannot_commit_leaves_no_input_pinned_to_it() { $runner($crate::RuntimePersistenceLaw::a_turn_that_cannot_commit_leaves_no_input_pinned_to_it).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn reopen_mint_identity() { $runner($crate::RuntimePersistenceLaw::reopen_mint_identity).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn gc_blobs() { $runner($crate::RuntimePersistenceLaw::gc_blobs).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn append_receipt_reopen() { $runner($crate::RuntimePersistenceLaw::append_receipt_reopen).await; }
        #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
        async fn runtime_reopen() { $runner($crate::RuntimePersistenceLaw::runtime_reopen).await; }
    };
}
