#!/usr/bin/env python3
"""Generate or check the example-owned HTTP contract JSON Schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[3]
OUTPUTS = {
    shape: ROOT
    / f"examples/workflow-graph-roundtrip/frontend/src/generated/{shape}.schema.json"
    for shape in ("workflow-document", "error-response")
}


def render(shape: str, generator: Path) -> tuple[int, str]:
    command = [str(generator.resolve()), shape]
    completed = subprocess.run(
        command,
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        sys.stderr.write(completed.stderr)
        return completed.returncode, ""
    try:
        schema = json.loads(completed.stdout)
    except json.JSONDecodeError as error:
        print(f"invalid {shape} schema output: {error}", file=sys.stderr)
        return 1, ""
    return 0, json.dumps(schema, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--generator", type=Path, help="use an already built generator")
    parser.add_argument("--generated", type=Path, help="compare documents already generated by Bazel")
    parser.add_argument("--output", type=Path, default=next(iter(OUTPUTS.values())).parent)
    parser.add_argument("--stamp", type=Path, help="write a success receipt after comparison")
    args = parser.parse_args()
    if args.stamp is not None:
        args.stamp.unlink(missing_ok=True)
    if args.generator is None and args.generated is None:
        if args.check and args.output == next(iter(OUTPUTS.values())).parent:
            return subprocess.run(["kiln", "build", "//:schema_checks"], cwd=ROOT).returncode
        built = subprocess.run(
            ["kiln", "build", "//:example_schema_documents", "--remote_download_outputs=toplevel"],
            cwd=ROOT,
        )
        if built.returncode != 0:
            return built.returncode
        args.generated = ROOT / "bazel-bin/example_schema_documents.documents"
    outputs = {shape: args.output / output.name for shape, output in OUTPUTS.items()}
    rendered = {}
    for shape in OUTPUTS:
        if args.generated is not None:
            try:
                expected = (args.generated / OUTPUTS[shape].name).read_text(encoding="utf-8")
            except OSError as error:
                print(f"cannot read generated {shape} schema: {error}", file=sys.stderr)
                return 1
        else:
            status, expected = render(shape, args.generator)
            if status:
                return status
        rendered[shape] = expected
    if args.check:
        stale = [
            output
            for shape, output in outputs.items()
            if (output.read_text(encoding="utf-8") if output.exists() else None)
            != rendered[shape]
        ]
        if stale:
            for output in stale:
                print(f"generated contract schema is stale: {output}", file=sys.stderr)
            print("run `npm run generate:types` in the frontend", file=sys.stderr)
            return 1
        if args.stamp is not None:
            args.stamp.write_text("example HTTP contract schemas are current\n", encoding="utf-8")
        print("example HTTP contract schemas are current")
        return 0
    for shape, output in outputs.items():
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered[shape], encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
