//! Statements owned by `usage_facts`.
pub const TABLE: &str = "usage_facts";
pub const INSERT_COLUMNS: &str = "owner_kind, owner_id, effect_key, call_ordinal, provider_attempt, fact_kind, disposition, run_id, llm_call_id, source, model, input_tokens, output_tokens, cache_read_input_tokens, cache_write_input_tokens, reasoning_output_tokens, generation_id, payload_hash, recorded_at_ms";
pub const RECORD_COLUMNS: &str = "seq, owner_kind, owner_id, effect_key, call_ordinal, provider_attempt, fact_kind, disposition, run_id, llm_call_id, source, model, input_tokens, output_tokens, cache_read_input_tokens, cache_write_input_tokens, reasoning_output_tokens, generation_id, payload_hash, recorded_at_ms";
crate::statements! {
    pub struct UsageFactsStatements @ "usage_facts" {
        payload = "SELECT payload_hash FROM usage_facts WHERE owner_kind = ?1 AND owner_id = ?2 AND effect_key = ?3 AND call_ordinal = ?4 AND provider_attempt = ?5 AND fact_kind = ?6";
        attempt = "SELECT seq, owner_kind, owner_id, effect_key, call_ordinal, provider_attempt, fact_kind, disposition, run_id, llm_call_id, source, model, input_tokens, output_tokens, cache_read_input_tokens, cache_write_input_tokens, reasoning_output_tokens, generation_id, payload_hash, recorded_at_ms FROM usage_facts WHERE owner_kind = ?1 AND owner_id = ?2 AND effect_key = ?3 AND call_ordinal = ?4 AND provider_attempt = ?5 AND fact_kind = ?6";
        page = "SELECT seq, owner_kind, owner_id, effect_key, call_ordinal, provider_attempt, fact_kind, disposition, run_id, llm_call_id, source, model, input_tokens, output_tokens, cache_read_input_tokens, cache_write_input_tokens, reasoning_output_tokens, generation_id, payload_hash, recorded_at_ms FROM usage_facts WHERE owner_kind = ?1 AND owner_id = ?2 AND seq > ?3 ORDER BY seq LIMIT ?4";
        aggregate = "SELECT source, model, CAST(SUM(input_tokens) AS BIGINT), CAST(SUM(output_tokens) AS BIGINT), CAST(SUM(cache_read_input_tokens) AS BIGINT), CAST(SUM(cache_write_input_tokens) AS BIGINT), CAST(SUM(reasoning_output_tokens) AS BIGINT), SUM(CASE WHEN disposition = 'reported' THEN 1 ELSE 0 END), SUM(CASE WHEN disposition = 'unreported' AND NOT EXISTS (SELECT 1 FROM usage_facts AS correction WHERE correction.owner_kind = attempt.owner_kind AND correction.owner_id = attempt.owner_id AND correction.effect_key = attempt.effect_key AND correction.call_ordinal = attempt.call_ordinal AND correction.provider_attempt = attempt.provider_attempt AND correction.fact_kind = 'correction') THEN 1 ELSE 0 END), SUM(CASE WHEN disposition = 'reconciled' THEN 1 ELSE 0 END) FROM usage_facts AS attempt WHERE owner_kind = ?1 AND owner_id = ?2 GROUP BY source, model ORDER BY source, model";
        outstanding = "SELECT effect_key, call_ordinal, provider_attempt, llm_call_id, source, model, generation_id FROM usage_facts AS attempt WHERE owner_kind = ?1 AND owner_id = ?2 AND disposition = 'unreported' AND NOT EXISTS (SELECT 1 FROM usage_facts AS correction WHERE correction.owner_kind = attempt.owner_kind AND correction.owner_id = attempt.owner_id AND correction.effect_key = attempt.effect_key AND correction.call_ordinal = attempt.call_ordinal AND correction.provider_attempt = attempt.provider_attempt AND correction.fact_kind = 'correction') ORDER BY effect_key, call_ordinal, provider_attempt";
        delete_retired = "DELETE FROM usage_facts AS fact WHERE EXISTS (SELECT 1 FROM usage_owner_retirements AS retirement WHERE retirement.owner_kind = fact.owner_kind AND retirement.owner_id = fact.owner_id AND retirement.retired_at_ms < ?1)";
    }
}
