//! Statements owned by `usage_meters`.
pub const TABLE: &str = "usage_meters";
pub const RECORD_COLUMNS: &str = "effect_key, meter_id, execution_scope_key, source, profile_key, requested_model, admitted_at_ms, state, unknown_reason, conflict_call_ordinal, conflict_provider_attempt, conflict_fact_kind, conflict_stored_payload_hash, conflict_offered_payload_hash, resolved_at_ms";
crate::statements! {
    pub struct UsageMetersStatements @ "usage_meters" {
        find = "SELECT effect_key, meter_id, execution_scope_key, source, profile_key, requested_model, admitted_at_ms, state, unknown_reason, conflict_call_ordinal, conflict_provider_attempt, conflict_fact_kind, conflict_stored_payload_hash, conflict_offered_payload_hash, resolved_at_ms FROM usage_meters WHERE owner_kind = ?1 AND owner_id = ?2 AND effect_key = ?3 AND meter_id = ?4";
        resolve = "UPDATE usage_meters SET state = ?5, unknown_reason = ?6, conflict_call_ordinal = NULL, conflict_provider_attempt = NULL, conflict_fact_kind = NULL, conflict_stored_payload_hash = NULL, conflict_offered_payload_hash = NULL, resolved_at_ms = ?7 WHERE owner_kind = ?1 AND owner_id = ?2 AND effect_key = ?3 AND meter_id = ?4 AND (state = 'open' OR (state = 'unknown' AND (state <> ?5 OR unknown_reason <> ?6)))";
        supersede = "UPDATE usage_meters SET state = 'unknown', unknown_reason = 'superseded_meter', resolved_at_ms = ?5 WHERE owner_kind = ?1 AND owner_id = ?2 AND effect_key = ?3 AND meter_id <> ?4 AND state = 'open'";
        insert_conflict = "INSERT INTO usage_meters (owner_kind, owner_id, effect_key, meter_id, state, conflict_call_ordinal, conflict_provider_attempt, conflict_fact_kind, conflict_stored_payload_hash, conflict_offered_payload_hash, resolved_at_ms) VALUES (?1, ?2, ?3, ?4, 'conflicted', ?5, ?6, ?7, ?8, ?9, ?10) ON CONFLICT (owner_kind, owner_id, effect_key, meter_id) DO NOTHING";
        conflict = "UPDATE usage_meters SET state = 'conflicted', unknown_reason = NULL, conflict_call_ordinal = ?5, conflict_provider_attempt = ?6, conflict_fact_kind = ?7, conflict_stored_payload_hash = ?8, conflict_offered_payload_hash = ?9, resolved_at_ms = ?10 WHERE owner_kind = ?1 AND owner_id = ?2 AND effect_key = ?3 AND (meter_id = ?4 OR state = 'open') AND (state <> 'conflicted' OR conflict_call_ordinal <> ?5 OR conflict_provider_attempt <> ?6 OR conflict_fact_kind <> ?7 OR conflict_stored_payload_hash <> ?8 OR conflict_offered_payload_hash <> ?9)";
        retire_execution = "UPDATE usage_meters SET state = 'unknown', unknown_reason = 'execution_ended', resolved_at_ms = ?4 WHERE owner_kind = ?1 AND owner_id = ?2 AND execution_scope_key = ?3 AND state = 'open'";
        retire_owner = "UPDATE usage_meters SET state = 'unknown', unknown_reason = 'owner_retired', resolved_at_ms = ?3 WHERE owner_kind = ?1 AND owner_id = ?2 AND state = 'open'";
        completeness = "SELECT CAST(COALESCE(SUM(CASE WHEN state = 'open' THEN 1 ELSE 0 END), 0) AS BIGINT), MIN(CASE WHEN state = 'open' THEN admitted_at_ms END), CAST(COALESCE(SUM(CASE WHEN state = 'unknown' THEN 1 ELSE 0 END), 0) AS BIGINT), CAST(COALESCE(SUM(CASE WHEN state = 'conflicted' THEN 1 ELSE 0 END), 0) AS BIGINT) FROM usage_meters WHERE owner_kind = ?1 AND owner_id = ?2";
        page = "SELECT effect_key, meter_id, execution_scope_key, source, profile_key, requested_model, admitted_at_ms, state, unknown_reason, conflict_call_ordinal, conflict_provider_attempt, conflict_fact_kind, conflict_stored_payload_hash, conflict_offered_payload_hash, resolved_at_ms FROM usage_meters WHERE owner_kind = ?1 AND owner_id = ?2 AND (?3 = 'all' OR (?3 = 'open' AND state = 'open') OR (?3 = 'unresolved' AND state IN ('unknown', 'conflicted'))) AND (effect_key > ?4 OR (effect_key = ?4 AND meter_id > ?5)) ORDER BY effect_key, meter_id LIMIT ?6";
        delete_retired = "DELETE FROM usage_meters AS run WHERE EXISTS (SELECT 1 FROM usage_owner_retirements AS retirement WHERE retirement.owner_kind = run.owner_kind AND retirement.owner_id = run.owner_id AND retirement.retired_at_ms < ?1)";
    }
}
