// Regenerate with crates/lash-kernel-conformance/index.py; owned with this shard tree.
const CORPUS_FILES: &[(&str, &str)] = &[
    ("K-BND-003.json", include_str!("../../protocol/bnd/K-BND-003.json")),
    ("K-CHG-003.json", include_str!("../../protocol/chg/K-CHG-003.json")),
    ("K-CHG-004.json", include_str!("../../protocol/chg/K-CHG-004.json")),
    ("K-CHG-005.json", include_str!("../../protocol/chg/K-CHG-005.json")),
    ("K-CHG-006.json", include_str!("../../protocol/chg/K-CHG-006.json")),
    ("K-EDIT-001.json", include_str!("../../protocol/edit/K-EDIT-001.json")),
    ("K-EDIT-002.json", include_str!("../../protocol/edit/K-EDIT-002.json")),
    ("K-EDIT-003.json", include_str!("../../protocol/edit/K-EDIT-003.json")),
    ("K-EDIT-004.json", include_str!("../../protocol/edit/K-EDIT-004.json")),
    ("K-EDIT-005.json", include_str!("../../protocol/edit/K-EDIT-005.json")),
    ("K-EDIT-006.json", include_str!("../../protocol/edit/K-EDIT-006.json")),
    ("K-EDIT-007.json", include_str!("../../protocol/edit/K-EDIT-007.json")),
    ("K-EDIT-008.json", include_str!("../../protocol/edit/K-EDIT-008.json")),
    ("K-EDIT-009.json", include_str!("../../protocol/edit/K-EDIT-009.json")),
    ("K-EDIT-010.json", include_str!("../../protocol/edit/K-EDIT-010.json")),
    ("K-EFF-011.json", include_str!("../../protocol/eff/K-EFF-011.json")),
    ("K-LIB-010.json", include_str!("../../protocol/lib/K-LIB-010.json")),
    ("K-SES-001.json", include_str!("../../protocol/ses/K-SES-001.json")),
    ("K-SES-002.json", include_str!("../../protocol/ses/K-SES-002.json")),
    ("K-SES-003.json", include_str!("../../protocol/ses/K-SES-003.json")),
    ("K-SITE-001.json", include_str!("../../protocol/site/K-SITE-001.json")),
    ("K-SITE-002.json", include_str!("../../protocol/site/K-SITE-002.json")),
    ("K-SITE-003.json", include_str!("../../protocol/site/K-SITE-003.json")),
    ("K-VER-003.json", include_str!("../../protocol/ver/K-VER-003.json")),
    ("K-VER-004.json", include_str!("../../protocol/ver/K-VER-004.json")),
    ("K-VER-005.json", include_str!("../../protocol/ver/K-VER-005.json")),
];
