//! Emits the declaration order of the snapshot types declared in this crate's
//! own `src/executor/state.rs`.
//!
//! It reads nothing but that file, and it must stay that way. Bazel compiles a
//! build script's dependency closure in the exec configuration as well as the
//! target one, so a first-party dependency here duplicates the whole runtime
//! tree beneath it at `opt-level=3` for artifacts no product consumes. The
//! field orders that belong to `lash-sansio` and `lash-lashlang-runtime` types
//! are therefore declared in `src/executor/state.rs` and proved against those
//! types' live serialization by
//! `generated_snapshot_field_schemas_match_all_fields_set_serialization`
//! (FIG-3032).

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use syn::{Attribute, Fields, Item};

/// Every fallible step in this build script reports through `main`, so cargo
/// prints the reason a generation step failed instead of a panic backtrace
/// from inside the build script (FIG-3167).
type BuildResult<T> = Result<T, Box<dyn std::error::Error>>;

#[derive(Clone)]
enum Definition {
    Struct(syn::ItemStruct),
    Enum(syn::ItemEnum),
}

fn main() -> BuildResult<()> {
    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR")
            .ok_or("CARGO_MANIFEST_DIR is unset; cargo always sets it for a build script")?,
    );
    let local_source = manifest_dir.join("src/executor/state.rs");
    println!("cargo:rerun-if-changed=src/executor/state.rs");
    let mut definitions = HashMap::new();
    collect_definitions(&local_source, &mut definitions);

    let schemas = [
        (
            "ROOT_FIELDS",
            source_fields_for("RlmSnapshotRoot", &definitions)?,
        ),
        (
            "PERSISTED_VALUE_FIELDS",
            source_fields_for("PersistedValue", &definitions)?,
        ),
    ];

    let mut generated = String::from("// @generated by build.rs from src/executor/state.rs.\n");
    for (constant, fields) in schemas {
        assert!(
            !fields.is_empty(),
            "{constant} produced no serialized fields"
        );
        write!(&mut generated, "const {constant}: &[&str] = &[")?;
        for field in fields {
            write!(&mut generated, "{field:?},")?;
        }
        generated.push_str("];\n");
    }

    let out = PathBuf::from(
        std::env::var_os("OUT_DIR")
            .ok_or("OUT_DIR is unset; cargo always sets it for a build script")?,
    )
    .join("rlm_snapshot_fields.rs");
    fs::write(&out, generated).map_err(|error| {
        format!(
            "write generated snapshot fields to {}: {error}",
            out.display()
        )
    })?;
    Ok(())
}

fn collect_definitions(path: &Path, definitions: &mut HashMap<String, Definition>) {
    let source = fs::read_to_string(path).unwrap_or_else(|error| {
        panic!(
            "failed to read snapshot schema source {}: {error}",
            path.display()
        )
    });
    let file = syn::parse_file(&source).unwrap_or_else(|error| {
        panic!(
            "failed to parse snapshot schema source {}: {error}",
            path.display()
        )
    });
    for item in file.items {
        match item {
            Item::Struct(item) => {
                definitions.insert(item.ident.to_string(), Definition::Struct(item));
            }
            Item::Enum(item) => {
                definitions.insert(item.ident.to_string(), Definition::Enum(item));
            }
            _ => {}
        }
    }
}

fn source_fields_for(
    rust_type: &str,
    definitions: &HashMap<String, Definition>,
) -> BuildResult<Vec<String>> {
    let definition = definitions
        .get(rust_type)
        .ok_or_else(|| format!("snapshot schema type `{rust_type}` was not found"))?;
    let mut fields = Vec::new();
    match definition {
        Definition::Struct(item) => collect_source_fields(rust_type, &item.fields, &mut fields)?,
        Definition::Enum(item) => {
            if let Some(tag) = serde_string(&item.attrs, "tag")? {
                fields.push(tag);
            }
            for variant in &item.variants {
                collect_source_fields(rust_type, &variant.fields, &mut fields)?;
            }
        }
    }
    Ok(deduplicate(fields))
}

fn collect_source_fields(
    rust_type: &str,
    fields: &Fields,
    output: &mut Vec<String>,
) -> BuildResult<()> {
    for (index, field) in fields.iter().enumerate() {
        if serde_flag(&field.attrs, "skip")? || serde_flag(&field.attrs, "skip_serializing")? {
            continue;
        }
        let name = match serde_string(&field.attrs, "rename")? {
            Some(renamed) => renamed,
            None => field
                .ident
                .as_ref()
                .ok_or_else(|| {
                    format!(
                        "snapshot schema type `{rust_type}` has an unnamed field at position \
                         {index}; the generated field list can only project named fields"
                    )
                })?
                .to_string(),
        };
        output.push(name);
    }
    Ok(())
}

fn serde_flag(attributes: &[Attribute], wanted: &str) -> BuildResult<bool> {
    for attribute in attributes
        .iter()
        .filter(|attribute| attribute.path().is_ident("serde"))
    {
        let mut found = false;
        attribute.parse_nested_meta(|meta| {
            if meta.path.is_ident(wanted) {
                found = true;
            }
            if meta.input.peek(syn::Token![=]) {
                let _: syn::Expr = meta.value()?.parse()?;
            }
            Ok(())
        })?;
        if found {
            return Ok(true);
        }
    }
    Ok(false)
}

fn serde_string(attributes: &[Attribute], wanted: &str) -> BuildResult<Option<String>> {
    for attribute in attributes
        .iter()
        .filter(|attribute| attribute.path().is_ident("serde"))
    {
        let mut found = None;
        attribute.parse_nested_meta(|meta| {
            if meta.path.is_ident(wanted) {
                found = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.input.peek(syn::Token![=]) {
                let _: syn::Expr = meta.value()?.parse()?;
            }
            Ok(())
        })?;
        if found.is_some() {
            return Ok(found);
        }
    }
    Ok(None)
}

fn deduplicate(fields: Vec<String>) -> Vec<String> {
    let mut seen = HashSet::new();
    fields
        .into_iter()
        .filter(|field| seen.insert(field.clone()))
        .collect()
}
