use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;
use serde_json::json;
use syn::{Attribute, Fields, Item};

/// Every fallible step in this build script reports through `main`, so cargo
/// prints the reason a generation step failed instead of a panic backtrace
/// from inside the build script (FIG-3167).
type BuildResult<T> = Result<T, Box<dyn std::error::Error>>;

#[derive(Clone)]
enum Definition {
    Struct(syn::ItemStruct),
    Enum(syn::ItemEnum),
}

fn main() -> BuildResult<()> {
    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR")
            .ok_or("CARGO_MANIFEST_DIR is unset; cargo always sets it for a build script")?,
    );
    let local_source = manifest_dir.join("src/executor/state.rs");
    println!("cargo:rerun-if-changed=src/executor/state.rs");
    let mut definitions = HashMap::new();
    collect_definitions(&local_source, &mut definitions);

    let mut schemas = vec![
        (
            "ROOT_FIELDS",
            source_fields_for("RlmSnapshotRoot", &definitions)?,
        ),
        (
            "PERSISTED_VALUE_FIELDS",
            source_fields_for("PersistedValue", &definitions)?,
        ),
    ];
    schemas.extend(serialized_dependency_schemas()?);

    let mut generated = String::from("// @generated by build.rs from the serialized Rust types.\n");
    for (constant, fields) in schemas {
        assert!(
            !fields.is_empty(),
            "{constant} produced no serialized fields"
        );
        write!(&mut generated, "const {constant}: &[&str] = &[")?;
        for field in fields {
            write!(&mut generated, "{field:?},")?;
        }
        generated.push_str("];\n");
    }

    let out = PathBuf::from(
        std::env::var_os("OUT_DIR")
            .ok_or("OUT_DIR is unset; cargo always sets it for a build script")?,
    )
    .join("rlm_snapshot_fields.rs");
    fs::write(&out, generated).map_err(|error| {
        format!(
            "write generated snapshot fields to {}: {error}",
            out.display()
        )
    })?;
    Ok(())
}

fn serialized_dependency_schemas() -> BuildResult<Vec<(&'static str, Vec<String>)>> {
    use lash_lashlang_runtime::{
        DeferredResolutionLinkKey, DeferredResolutionRecord, DeferredTriggerResolutionRecord,
        Resolution, ToolGrant, TriggerGrant, TriggerResolution,
    };
    use lash_sansio::{
        CompactToolContract, ProjectionMode, SchemaContract, SchemaProjectionOverride,
        SchemaProjectionPolicy, ToolActivation, ToolArgumentProjectionPolicy, ToolDefinition,
        ToolOutputContract, ToolRetryPolicy,
    };

    let compact_contract = CompactToolContract {
        name: "lookup".to_string(),
        signature: "lookup(query: string)".to_string(),
        returns: "object".to_string(),
        parameters: vec![json!({"name": "query"})],
        return_fields: vec![json!({"name": "answer"})],
        description: "Look up an answer".to_string(),
        examples: vec!["lookup(\"weather\")".to_string()],
    };
    let schema_override = SchemaProjectionOverride {
        dialect: "test".to_string(),
        schema: json!({"type": "string"}),
    };
    let schema_projection = SchemaProjectionPolicy {
        mode: ProjectionMode::Exact,
        overrides: vec![schema_override.clone()],
    };
    let schema_contract = SchemaContract {
        canonical: json!({"type": "object"}),
        projection: schema_projection.clone(),
    };
    let retry_policy = ToolRetryPolicy::Safe {
        max_attempts: 3,
        base_delay_ms: 10,
        max_delay_ms: 100,
    };
    let output_contract = ToolOutputContract::FromInputSchema {
        input_field: "schema".to_string(),
        default_schema: Some(json!({"type": "object"})),
    };
    let argument_projection = ToolArgumentProjectionPolicy::PreserveProjectedRefsInField {
        field: "payload".to_string(),
    };
    let mut definition = ToolDefinition::raw(
        "tool.lookup",
        "lookup",
        "Look up an answer",
        json!({"type": "object"}),
        json!({"type": "object"}),
    );
    definition.manifest.compact_contract = Some(compact_contract.clone());
    definition.manifest.activation = ToolActivation::Internal;
    definition
        .manifest
        .bindings
        .insert("service".to_string(), json!({"account": "primary"}));
    definition.manifest.argument_projection = argument_projection.clone();
    definition.manifest.retry_policy = retry_policy;
    definition.contract.input_schema = schema_contract.clone();
    definition.contract.output_schema = schema_contract.clone();
    definition.contract.output_contract = output_contract.clone();
    definition.contract.examples = vec!["lookup weather".to_string()];

    let grant = ToolGrant::new(definition.clone())
        .with_source_id("registry")
        .with_execution_binding(json!({"route": "primary"}));
    let resolution = Resolution::Resolved(Box::new(grant));
    let link_key = DeferredResolutionLinkKey {
        address: lash_sansio::EffectAddress::new(
            lash_sansio::ExecutionScope::turn("session", "turn"),
            "replay",
        )
        .map_err(|error| format!("build the generated snapshot effect address: {error}"))?,
    };
    let deferred_resolutions = DeferredResolutionRecord {
        link_key: Some(link_key.clone()),
        resolutions: [("lookup".to_string(), resolution.clone())]
            .into_iter()
            .collect(),
    };
    let trigger_grant: TriggerGrant = serde_json::from_value(json!({
        "provider_id": "calendar",
        "constructor_path": ["calendar", "Changed"],
        "input_type": {"Object": [{"name": "calendar", "ty": "Str", "optional": false}]},
        "event_type": {
            "name": "calendar.Change",
            "ty": {"Object": [{"name": "id", "ty": "Str", "optional": false}]}
        },
        "route": {"account": "primary"}
    }))
    .map_err(|error| format!("build the generated trigger grant witness: {error}"))?;
    let trigger_resolution = TriggerResolution::Resolved(Box::new(trigger_grant));
    let deferred_trigger_resolutions = DeferredTriggerResolutionRecord {
        link_key: Some(link_key.clone()),
        resolutions: [("calendar.Changed".to_string(), trigger_resolution.clone())]
            .into_iter()
            .collect(),
    };

    Ok(vec![
        (
            "DEFERRED_RESOLUTION_FIELDS",
            serialized_union(&[serialized_fields(&deferred_resolutions)?]),
        ),
        (
            "DEFERRED_LINK_KEY_FIELDS",
            serialized_union(&[serialized_fields(&link_key)?]),
        ),
        (
            "DEFERRED_TRIGGER_RESOLUTION_FIELDS",
            serialized_union(&[serialized_fields(&deferred_trigger_resolutions)?]),
        ),
        (
            "TRIGGER_RESOLUTION_FIELDS",
            serialized_union(&[
                serialized_fields(&trigger_resolution)?,
                serialized_fields(&TriggerResolution::NotAvailable)?,
                serialized_fields(&TriggerResolution::Ambiguous {
                    provider_ids: vec!["a".to_string(), "b".to_string()],
                })?,
            ]),
        ),
        (
            "RESOLUTION_FIELDS",
            serialized_union(&[
                serialized_fields(&resolution)?,
                serialized_fields(&Resolution::NotAvailable)?,
            ]),
        ),
        (
            "TOOL_DEFINITION_FIELDS",
            serialized_union(&[serialized_fields(&definition)?]),
        ),
        (
            "SCHEMA_CONTRACT_FIELDS",
            serialized_union(&[serialized_fields(&schema_contract)?]),
        ),
        (
            "SCHEMA_PROJECTION_FIELDS",
            serialized_union(&[serialized_fields(&schema_projection)?]),
        ),
        (
            "SCHEMA_OVERRIDE_FIELDS",
            serialized_union(&[serialized_fields(&schema_override)?]),
        ),
        (
            "COMPACT_CONTRACT_FIELDS",
            serialized_union(&[serialized_fields(&compact_contract)?]),
        ),
        (
            "RETRY_POLICY_FIELDS",
            serialized_union(&[serialized_fields(&retry_policy)?]),
        ),
        (
            "OUTPUT_CONTRACT_FIELDS",
            serialized_union(&[serialized_fields(&output_contract)?]),
        ),
        (
            "ARGUMENT_PROJECTION_FIELDS",
            serialized_union(&[serialized_fields(&argument_projection)?]),
        ),
    ])
}

fn collect_definitions(path: &Path, definitions: &mut HashMap<String, Definition>) {
    let source = fs::read_to_string(path).unwrap_or_else(|error| {
        panic!(
            "failed to read snapshot schema source {}: {error}",
            path.display()
        )
    });
    let file = syn::parse_file(&source).unwrap_or_else(|error| {
        panic!(
            "failed to parse snapshot schema source {}: {error}",
            path.display()
        )
    });
    for item in file.items {
        match item {
            Item::Struct(item) => {
                definitions.insert(item.ident.to_string(), Definition::Struct(item));
            }
            Item::Enum(item) => {
                definitions.insert(item.ident.to_string(), Definition::Enum(item));
            }
            _ => {}
        }
    }
}

fn source_fields_for(
    rust_type: &str,
    definitions: &HashMap<String, Definition>,
) -> BuildResult<Vec<String>> {
    let definition = definitions
        .get(rust_type)
        .ok_or_else(|| format!("snapshot schema type `{rust_type}` was not found"))?;
    let mut fields = Vec::new();
    match definition {
        Definition::Struct(item) => collect_source_fields(rust_type, &item.fields, &mut fields)?,
        Definition::Enum(item) => {
            if let Some(tag) = serde_string(&item.attrs, "tag")? {
                fields.push(tag);
            }
            for variant in &item.variants {
                collect_source_fields(rust_type, &variant.fields, &mut fields)?;
            }
        }
    }
    Ok(deduplicate(fields))
}

fn collect_source_fields(
    rust_type: &str,
    fields: &Fields,
    output: &mut Vec<String>,
) -> BuildResult<()> {
    for (index, field) in fields.iter().enumerate() {
        if serde_flag(&field.attrs, "skip")? || serde_flag(&field.attrs, "skip_serializing")? {
            continue;
        }
        let name = match serde_string(&field.attrs, "rename")? {
            Some(renamed) => renamed,
            None => field
                .ident
                .as_ref()
                .ok_or_else(|| {
                    format!(
                        "snapshot schema type `{rust_type}` has an unnamed field at position \
                         {index}; the generated field list can only project named fields"
                    )
                })?
                .to_string(),
        };
        output.push(name);
    }
    Ok(())
}

fn serde_flag(attributes: &[Attribute], wanted: &str) -> BuildResult<bool> {
    for attribute in attributes
        .iter()
        .filter(|attribute| attribute.path().is_ident("serde"))
    {
        let mut found = false;
        attribute.parse_nested_meta(|meta| {
            if meta.path.is_ident(wanted) {
                found = true;
            }
            if meta.input.peek(syn::Token![=]) {
                let _: syn::Expr = meta.value()?.parse()?;
            }
            Ok(())
        })?;
        if found {
            return Ok(true);
        }
    }
    Ok(false)
}

fn serde_string(attributes: &[Attribute], wanted: &str) -> BuildResult<Option<String>> {
    for attribute in attributes
        .iter()
        .filter(|attribute| attribute.path().is_ident("serde"))
    {
        let mut found = None;
        attribute.parse_nested_meta(|meta| {
            if meta.path.is_ident(wanted) {
                found = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.input.peek(syn::Token![=]) {
                let _: syn::Expr = meta.value()?.parse()?;
            }
            Ok(())
        })?;
        if found.is_some() {
            return Ok(found);
        }
    }
    Ok(None)
}

fn serialized_fields(value: &impl Serialize) -> BuildResult<Vec<String>> {
    let encoded = serde_json::to_string(value)
        .map_err(|error| format!("serialize the build-time schema witness: {error}"))?;
    top_level_json_object_keys(&encoded)
}

fn serialized_union(serialized: &[Vec<String>]) -> Vec<String> {
    let mut fields = Vec::new();
    for schema in serialized {
        for field in schema {
            if !fields.contains(field) {
                fields.push(field.clone());
            }
        }
    }
    fields
}

fn top_level_json_object_keys(encoded: &str) -> BuildResult<Vec<String>> {
    let bytes = encoded.as_bytes();
    assert_eq!(bytes.first(), Some(&b'{'), "schema value must be a map");
    let mut keys = Vec::new();
    let mut cursor = 1;
    while cursor < bytes.len() {
        while matches!(bytes.get(cursor), Some(b' ' | b'\n' | b'\r' | b'\t' | b',')) {
            cursor += 1;
        }
        if bytes.get(cursor) == Some(&b'}') {
            break;
        }
        let key_end = json_string_end(bytes, cursor);
        keys.push(
            serde_json::from_str::<String>(&encoded[cursor..key_end]).map_err(|error| {
                format!("decode a serialized field name from the schema witness: {error}")
            })?,
        );
        cursor = key_end;
        while matches!(bytes.get(cursor), Some(b' ' | b'\n' | b'\r' | b'\t')) {
            cursor += 1;
        }
        assert_eq!(bytes.get(cursor), Some(&b':'));
        cursor = json_value_end(bytes, cursor + 1);
    }
    Ok(keys)
}

fn json_string_end(bytes: &[u8], start: usize) -> usize {
    assert_eq!(bytes.get(start), Some(&b'"'));
    let mut cursor = start + 1;
    let mut escaped = false;
    while cursor < bytes.len() {
        match (bytes[cursor], escaped) {
            (_, true) => escaped = false,
            (b'\\', false) => escaped = true,
            (b'"', false) => return cursor + 1,
            _ => {}
        }
        cursor += 1;
    }
    panic!("unterminated JSON string")
}

fn json_value_end(bytes: &[u8], start: usize) -> usize {
    let mut cursor = start;
    let mut depth = 0_usize;
    let mut in_string = false;
    let mut escaped = false;
    while cursor < bytes.len() {
        let byte = bytes[cursor];
        if in_string {
            match (byte, escaped) {
                (_, true) => escaped = false,
                (b'\\', false) => escaped = true,
                (b'"', false) => in_string = false,
                _ => {}
            }
        } else {
            match byte {
                b'"' => in_string = true,
                b'{' | b'[' => depth += 1,
                b'}' | b']' if depth > 0 => depth -= 1,
                b',' | b'}' if depth == 0 => return cursor,
                _ => {}
            }
        }
        cursor += 1;
    }
    cursor
}

fn deduplicate(fields: Vec<String>) -> Vec<String> {
    let mut seen = HashSet::new();
    fields
        .into_iter()
        .filter(|field| seen.insert(field.clone()))
        .collect()
}
