#!/usr/bin/env python3
"""Generate or check the checked-in workflow JSON Schema documents."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "schemas" / "host"


def rendered_documents(payload: list[dict[str, object]]) -> dict[Path, str]:
    documents: dict[Path, str] = {}
    for document in payload:
        shape = document["shape"]
        version = document["version"]
        schema = document["schema"]
        if not isinstance(shape, str) or not isinstance(version, int):
            raise ValueError("generator returned an invalid shape registration")
        relative = Path(shape) / f"v{version}.schema.json"
        documents[relative] = json.dumps(schema, indent=2) + "\n"
    return documents


def generate(
    check: bool,
    generators: list[Path] | None = None,
    generated: Path | None = None,
    output: Path | None = None,
) -> int:
    output = OUTPUT if output is None else output
    if generated is not None:
        documents = {
            path.relative_to(generated): path.read_text(encoding="utf-8")
            for path in generated.glob("*/*.schema.json")
        }
        if not documents:
            print("generated workflow schema directory is empty", file=sys.stderr)
            return 1
    else:
        if not generators:
            raise ValueError("a generator or generated documents are required")
        payload: list[dict[str, object]] = []
        for generator in generators:
            completed = subprocess.run(
                [str(generator.resolve())], cwd=ROOT, check=False, capture_output=True, text=True
            )
            if completed.returncode != 0:
                sys.stderr.write(completed.stderr)
                return completed.returncode
            try:
                payload.extend(json.loads(completed.stdout))
            except (json.JSONDecodeError, TypeError) as error:
                print(f"invalid schema generator output: {error}", file=sys.stderr)
                return 1
        try:
            documents = rendered_documents(payload)
        except (json.JSONDecodeError, KeyError, TypeError, ValueError) as error:
            print(f"invalid workflow schema generator output: {error}", file=sys.stderr)
            return 1

    stale: list[str] = []
    for relative, expected in documents.items():
        path = output / relative
        if check:
            try:
                actual = path.read_text(encoding="utf-8")
            except OSError as error:
                stale.append(f"{path} cannot be read: {error}")
            else:
                if actual != expected:
                    stale.append(f"{path} differs")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")

    expected_paths = {output / relative for relative in documents}
    if output.exists():
        for path in output.glob("*/*.schema.json"):
            if path not in expected_paths:
                if check:
                    stale.append(f"{path} is obsolete")
                else:
                    path.unlink()

    if stale:
        print("workflow schema drift detected:", file=sys.stderr)
        print("\n".join(stale), file=sys.stderr)
        print("run `python3 scripts/generate-workflow-schemas.py`", file=sys.stderr)
        return 1
    if check:
        print("workflow schema documents are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if checked-in documents differ from fresh generation",
    )
    parser.add_argument("--generator", type=Path, action="append", dest="generators",
                        help="use an already built generator; may be repeated")
    parser.add_argument("--generated", type=Path, help="compare documents already generated by Bazel")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--stamp", type=Path, help="write a success receipt after comparison")
    args = parser.parse_args()
    if args.stamp is not None:
        args.stamp.unlink(missing_ok=True)
    if args.generators is None and args.generated is None:
        if args.check and args.output == OUTPUT:
            return subprocess.run(["kiln", "build", "//:host_schema_check"], cwd=ROOT).returncode
        built = subprocess.run(
            ["kiln", "build", "//:host_schema_documents", "--remote_download_outputs=toplevel"],
            cwd=ROOT,
        )
        if built.returncode != 0:
            return built.returncode
        args.generated = ROOT / "bazel-bin/host_schema_documents.documents"
    status = generate(args.check, args.generators, args.generated, args.output)
    if status == 0 and args.stamp is not None:
        args.stamp.write_text("workflow schema documents are current\n", encoding="utf-8")
    return status


if __name__ == "__main__":
    sys.exit(main())
