#!/usr/bin/env python3
"""Unit tests for the remote sizing contract.

`tools/bazel/action_sizes_from_log.py` turns the pool's usage logs into the
measured compile table; `tools/bazel/generate_build_files.py` turns that table
and the test-run sizes into `exec_properties`, and `tools/bazel/test_batch.bzl`
sizes a batch from its member request.
"""

from __future__ import annotations

import json
import pathlib
import re
import sys
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools/bazel"))

import action_sizes_from_log as sizes  # noqa: E402
import generate_build_files as generator  # noqa: E402


GIB = 1024**3
CRATES = {("lash-internal-core", "lash_core"), ("lash-sim", "logical_turn")}


def record(
    pkg: str = "lash-internal-core",
    crate: str = "lash_core",
    cores: float = 1.0,
    peak_bytes: int = GIB,
    wall_ms: int = 10_000,
    requested_cpu: str = "4",
    tool: str = "process_wrapper",
    exit_status: str = "0",
) -> str:
    cpu_usec = int(cores * wall_ms * 1000)
    return "\t".join(
        [
            "1789424023",
            f"crate={crate}",
            f"pkg={pkg}",
            "kind=-",
            f"tool={tool}",
            f"peak_bytes={peak_bytes}",
            f"cpu_usec={cpu_usec}",
            f"wall_ms={wall_ms}",
            f"exit={exit_status}",
            "requested_kb=4194304",
            f"requested_cpu={requested_cpu}",
        ]
    )


def table(lines: list[str]) -> dict:
    return sizes.table(sizes.collect(lines, CRATES))


def generated_blocks():
    for path in sorted(ROOT.rglob("BUILD.bazel")):
        if "bazel-" in path.parts[len(ROOT.parts)]:
            continue
        text = path.read_text(encoding="utf-8")
        if "@generated by tools/bazel/generate_build_files.py" not in text:
            continue
        for block in text.split("\n\n"):
            yield path, block


def properties_of(block: str) -> dict[str, str]:
    match = re.search(r"exec_properties = (\{[^}]*\})", block)
    return json.loads(match.group(1)) if match else {}


class CollectTest(unittest.TestCase):
    def test_only_lash_packages_are_measured(self) -> None:
        # The pool is shared: another repository's crate, even one with a Lash
        # crate's name, never reaches this table.
        lines = [record(cores=3.0)] * 20
        lines += [record(pkg="control-plane", crate="control_plane", cores=7.0)] * 50
        lines += [record(pkg="other-repo", crate="lash_core", cores=7.0)] * 50
        measured = sizes.collect(lines, CRATES)
        self.assertEqual(sorted(measured), ["lash-internal-core/lash_core"])
        self.assertEqual(len(measured["lash-internal-core/lash_core"].records), 20)

    def test_only_successful_compiles_of_a_second_or_more_count(self) -> None:
        lines = [
            record(tool="test-setup.sh"),
            record(tool="generate-xml.sh"),
            record(exit_status="137"),
            record(wall_ms=999),
            "torn line",
            "1789424023\tcrate=lash_core\tno-separator",
        ]
        self.assertEqual(sizes.collect(lines, CRATES), {})

    def test_first_party_crates_come_from_workspace_targets(self) -> None:
        metadata = {
            "packages": [
                {
                    "name": "lash-sim",
                    "targets": [
                        {"name": "lash_sim", "kind": ["lib"]},
                        {"name": "logical-turn", "kind": ["test"]},
                        {"name": "build-script-build", "kind": ["custom-build"]},
                    ],
                }
            ]
        }
        self.assertEqual(
            sizes.first_party_crates(metadata),
            {("lash-sim", "lash_sim"), ("lash-sim", "logical_turn")},
        )


class TableTest(unittest.TestCase):
    def test_cpu_is_the_p95_rounded_up_past_the_tolerance(self) -> None:
        # p95 of 19 x 1.0 and 1 x 2.5 cores is 1.0 (nearest rank), so 1 CPU;
        # memory keeps the row.
        lines = [record(cores=1.0, peak_bytes=2 * GIB)] * 19 + [record(cores=2.5)]
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 1)
        # 2.15 cores at p95 is within the tolerance of 2.
        lines = [record(cores=2.15)] * 20
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 2)
        # 2.25 is not.
        lines = [record(cores=2.25)] * 20
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 3)

    def test_cpu_is_capped_at_eight(self) -> None:
        lines = [record(cores=14.0)] * 20
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 8)
        self.assertEqual(sizes.MAX_CPU_COUNT, 8)

    def test_one_cpu_samples_are_left_out_when_larger_requests_exist(self) -> None:
        # Under a 1-CPU quota an action cannot show that it wants more.
        lines = [record(cores=1.0, requested_cpu="1")] * 200
        lines += [record(cores=2.0, requested_cpu="4")] * 20
        entry = table(lines)["lash-internal-core/lash_core"]
        self.assertEqual(entry["cpu_count"], 2)
        self.assertEqual(entry["samples"], 220)

    def test_one_cpu_samples_are_used_when_they_are_all_there_is(self) -> None:
        lines = [record(cores=1.6, requested_cpu="1")] * 20
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 2)

    def test_memory_follows_the_worst_peak_with_margin(self) -> None:
        lines = [record(cores=2.0, peak_bytes=GIB)] * 19
        lines += [record(cores=2.0, peak_bytes=3 * GIB)]
        entry = table(lines)["lash-internal-core/lash_core"]
        self.assertEqual(entry["peak_bytes"], 3 * GIB)
        # 3 GiB x 1.5 = 4.5 GiB, already a multiple of 512 MiB.
        self.assertEqual(entry["memory_kb"], 4718592)

    def test_memory_never_goes_below_the_default(self) -> None:
        lines = [record(cores=2.0, peak_bytes=GIB // 4)] * 20
        self.assertEqual(
            table(lines)["lash-internal-core/lash_core"]["memory_kb"],
            sizes.DEFAULT_MEMORY_KB,
        )

    def test_too_few_samples_make_no_row(self) -> None:
        self.assertEqual(table([record(cores=4.0)] * (sizes.MIN_SAMPLES - 1)), {})

    def test_a_row_at_the_defaults_is_dropped(self) -> None:
        self.assertEqual(table([record(cores=1.0, peak_bytes=GIB)] * 20), {})

    def test_rendered_table_is_sorted_and_newline_terminated(self) -> None:
        lines = [record(cores=2.0)] * 20
        lines += [record(pkg="lash-sim", crate="logical_turn", cores=2.0)] * 20
        rendered = sizes.render(table(lines))
        self.assertTrue(rendered.endswith("}\n"))
        self.assertEqual(list(json.loads(rendered)), sorted(json.loads(rendered)))

    def test_the_checked_in_table_matches_the_documented_shape(self) -> None:
        checked_in = json.loads(
            (ROOT / "tools/bazel/action-sizes.json").read_text(encoding="utf-8")
        )
        inventory = json.loads(
            (ROOT / "tools/bazel/target-inventory.json").read_text(encoding="utf-8")
        )
        crates = {
            f"{package['package']}/{target['cargo'].replace('-', '_')}"
            for package in inventory["packages"]
            for target in package["targets"]
            if target.get("cargo")
        }
        self.assertTrue(checked_in)
        for key, entry in checked_in.items():
            with self.subTest(key=key):
                self.assertIn(key, crates, "a row that names no first-party crate is dead")
                self.assertEqual(
                    sorted(entry),
                    ["cpu_count", "memory_kb", "p95_cores", "peak_bytes", "samples"],
                )
                self.assertTrue(
                    entry["memory_kb"] > sizes.DEFAULT_MEMORY_KB
                    or entry["cpu_count"] > sizes.DEFAULT_CPU_COUNT,
                    "an entry that asks for no more than the defaults is noise",
                )
                self.assertEqual(entry["cpu_count"], sizes.cpu_count_for(entry["p95_cores"]))
                self.assertEqual(entry["memory_kb"], sizes.memory_kb_for(entry["peak_bytes"]))
                self.assertGreaterEqual(entry["samples"], sizes.MIN_SAMPLES)


class CompileRequestTest(unittest.TestCase):
    """Plain `exec_properties` size compiles, from the measured row only."""

    def test_an_unmeasured_compile_states_nothing(self) -> None:
        for kind in ("lib", "bin"):
            with self.subTest(kind=kind):
                self.assertEqual(
                    generator.exec_properties("no-such-package", "no_such_crate", kind), {}
                )

    def test_a_measured_row_is_emitted_as_measured(self) -> None:
        key = "lash-internal-core/lash_core"
        entry = generator.ACTION_SIZES[key]
        self.assertEqual(
            generator.exec_properties("lash-internal-core", "lash_core", "lib"),
            {"cpu_count": str(entry["cpu_count"]), "memory_kb": str(entry["memory_kb"])},
        )

    def test_every_generated_compile_request_is_its_measured_row(self) -> None:
        seen = 0
        for path, block in generated_blocks():
            properties = properties_of(block)
            if "cpu_count" not in properties:
                continue
            package = re.search(r'package_name = "([^"]+)"', block)
            crate = re.search(r'crate_name = "([^"]+)"', block)
            self.assertIsNotNone(package, f"{path}: sized block without package_name")
            self.assertIsNotNone(crate, f"{path}: sized block without crate_name")
            entry = generator.ACTION_SIZES[f"{package.group(1)}/{crate.group(1)}"]
            seen += 1
            with self.subTest(path=str(path), crate=crate.group(1)):
                self.assertEqual(properties["cpu_count"], str(entry["cpu_count"]))
                self.assertEqual(properties["memory_kb"], str(entry["memory_kb"]))
        self.assertGreater(seen, 0)


class TestRunRequestTest(unittest.TestCase):
    """A test run is sized through the `test` exec group, apart from its compile.

    A run is a whole libtest binary running a tokio runtime and a store. At one
    core the suite's own threads contend for it and time-sensitive cases fail
    outright: CI run 34950810111 lost `//crates/lash-perf:lash-perf__unit_test`
    on a phase assertion and timed out `//crates/lash-sim:stack_policy__test`.
    """

    def test_an_unmeasured_test_asks_for_the_run_floor_only(self) -> None:
        self.assertEqual(generator.TEST_CPU_FLOOR, 4)
        self.assertEqual(
            generator.exec_properties("no-such-package", "no_such_crate", "test"),
            {
                "test.cpu_count": str(generator.TEST_CPU_FLOOR),
                "test.memory_kb": str(generator.TEST_MEMORY_FLOOR_KB),
            },
        )

    def test_a_listed_run_keeps_its_larger_request(self) -> None:
        properties = generator.exec_properties("lash-internal-core", "lash_core", "test")
        self.assertEqual(properties["test.cpu_count"], "8")
        self.assertEqual(properties["test.memory_kb"], "6815744")
        # The compile half is the measured row, not the run's size.
        self.assertEqual(
            properties["cpu_count"],
            str(generator.ACTION_SIZES["lash-internal-core/lash_core"]["cpu_count"]),
        )

    def test_listed_runs_never_ask_for_less_than_the_floor(self) -> None:
        for key, run in generator.TEST_RUN_SIZES.items():
            with self.subTest(key=key):
                self.assertGreaterEqual(run["cpu_count"], generator.TEST_CPU_FLOOR)
                self.assertGreaterEqual(run["memory_kb"], generator.TEST_MEMORY_FLOOR_KB)
                self.assertLessEqual(run["cpu_count"], sizes.MAX_CPU_COUNT)

    def test_every_generated_test_target_states_its_run(self) -> None:
        test_rules = (
            "lash_rust_unit_test(",
            "lash_rust_integration_test(",
            "lash_rust_feature_test(",
        )
        seen = 0
        for path, block in generated_blocks():
            if not block.startswith(test_rules):
                continue
            properties = properties_of(block)
            seen += 1
            with self.subTest(path=str(path), block=block.splitlines()[1]):
                self.assertGreaterEqual(
                    int(properties["test.cpu_count"]), generator.TEST_CPU_FLOOR
                )
                self.assertGreaterEqual(
                    int(properties["test.memory_kb"]), generator.TEST_MEMORY_FLOOR_KB
                )
        self.assertGreater(seen, 0)

    def test_no_other_target_states_a_run(self) -> None:
        for path, block in generated_blocks():
            if block.startswith(("lash_rust_library(", "lash_rust_binary(", "lash_rust_feature_library(", "lash_rust_feature_binary(")):
                with self.subTest(path=str(path), block=block.splitlines()[1]):
                    self.assertFalse(
                        [key for key in properties_of(block) if key.startswith("test.")]
                    )


class BatchBudgetTest(unittest.TestCase):
    """A batch reserves what it runs, and runs no more than it reserves."""

    def test_batches_only_hold_floor_sized_members(self) -> None:
        for key in generator.TEST_RUN_SIZES:
            with self.subTest(key=key):
                self.assertFalse(generator.batchable_run(*key.split("/")))
        self.assertTrue(generator.batchable_run("no-such-package", "no_such_crate"))

    def test_every_generated_batch_declares_the_member_floor(self) -> None:
        seen = 0
        for path, block in generated_blocks():
            if not block.startswith("lash_batch_test("):
                continue
            seen += 1
            with self.subTest(path=str(path)):
                self.assertIn(f"member_cpu_count = {generator.TEST_CPU_FLOOR},", block)
                self.assertIn(
                    f"member_memory_kb = {generator.TEST_MEMORY_FLOOR_KB},", block
                )
        self.assertGreater(seen, 0)

    def test_the_rule_reserves_every_slot_it_runs(self) -> None:
        bzl = (ROOT / "tools/bazel/test_batch.bzl").read_text(encoding="utf-8")
        self.assertRegex(bzl, r"\nBATCH_JOBS = [1-9]\d*\n")
        self.assertIn('"test.cpu_count": str(BATCH_JOBS * member_cpu_count)', bzl)
        self.assertIn('"test.memory_kb": str(BATCH_JOBS * member_memory_kb)', bzl)
        self.assertIn("jobs = BATCH_JOBS", bzl)
        self.assertIn("export LASH_BATCH_JOBS={jobs}", bzl)
        runner = (ROOT / "tools/bazel/test_batch_runner.sh").read_text(encoding="utf-8")
        self.assertIn("jobs_cap=${LASH_BATCH_JOBS:?", runner)
        self.assertNotIn("nproc", runner)


class TableValidationTest(unittest.TestCase):
    def test_a_stale_row_fails_generation(self) -> None:
        metadata = {
            "workspace_members": ["id"],
            "packages": [
                {"id": "id", "name": "lash-sim", "targets": [{"name": "lash_sim", "kind": ["lib"]}]}
            ],
        }
        saved = dict(generator.ACTION_SIZES)
        saved_runs = dict(generator.TEST_RUN_SIZES)
        try:
            generator.ACTION_SIZES.clear()
            generator.TEST_RUN_SIZES.clear()
            generator.ACTION_SIZES["lash-sim/lash_sim"] = {"cpu_count": 2}
            generator.validate_action_sizes(metadata)
            generator.ACTION_SIZES["gone/gone"] = {"cpu_count": 2}
            with self.assertRaises(SystemExit):
                generator.validate_action_sizes(metadata)
        finally:
            generator.ACTION_SIZES.clear()
            generator.ACTION_SIZES.update(saved)
            generator.TEST_RUN_SIZES.clear()
            generator.TEST_RUN_SIZES.update(saved_runs)


class DefaultsAgreeTest(unittest.TestCase):
    """The two defaults are written down in three places; they must match.

    `.bazelrc` is what the pool is actually asked for, and the other two decide
    which rows are worth keeping and what an unmeasured target inherits.
    """

    def test_bazelrc_and_the_tools_agree(self) -> None:
        bazelrc = (ROOT / ".bazelrc").read_text(encoding="utf-8")
        for name, value in (
            ("cpu_count", sizes.DEFAULT_CPU_COUNT),
            ("memory_kb", sizes.DEFAULT_MEMORY_KB),
        ):
            self.assertIn(f"build --remote_default_exec_properties={name}={value}\n", bazelrc)
        self.assertEqual(generator.DEFAULT_CPU_COUNT, sizes.DEFAULT_CPU_COUNT)
        self.assertEqual(generator.DEFAULT_MEMORY_KB, sizes.DEFAULT_MEMORY_KB)

    def test_ci_inherits_the_same_defaults(self) -> None:
        action = (ROOT / ".github/actions/bazel-shared-cache/action.yml").read_text()
        for name in ("cpu_count", "memory_kb"):
            self.assertNotIn(f"--remote_default_exec_properties={name}=", action)


if __name__ == "__main__":
    unittest.main()
