#!/usr/bin/env python3
"""Unit tests for the remote sizing contract.

`tools/bazel/action_sizes_from_log.py` turns the pool's usage logs into the
measured compile and test-run tables; `tools/bazel/generate_build_files.py`
turns them into `exec_properties` and sizes each `:test_batch` from its members,
and `tools/bazel/test_batch.bzl` reserves what it is given.
"""

from __future__ import annotations

import json
import pathlib
import re
import sys
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools/bazel"))

import action_sizes_from_log as sizes  # noqa: E402
import generate_build_files as generator  # noqa: E402


GIB = 1024**3
CRATES = {("lash-internal-core", "lash_core"), ("lash-sim", "logical_turn")}


def record(
    pkg: str = "lash-internal-core",
    crate: str = "lash_core",
    cores: float = 1.0,
    peak_bytes: int = GIB,
    wall_ms: int = 10_000,
    requested_cpu: str = "4",
    tool: str = "process_wrapper",
    exit_status: str = "0",
) -> str:
    cpu_usec = int(cores * wall_ms * 1000)
    return "\t".join(
        [
            "1789424023",
            f"crate={crate}",
            f"pkg={pkg}",
            "kind=-",
            f"tool={tool}",
            f"peak_bytes={peak_bytes}",
            f"cpu_usec={cpu_usec}",
            f"wall_ms={wall_ms}",
            f"exit={exit_status}",
            "requested_kb=4194304",
            f"requested_cpu={requested_cpu}",
        ]
    )


def table(lines: list[str]) -> dict:
    return sizes.table(sizes.collect(lines, CRATES))


def generated_blocks():
    for path in sorted(ROOT.rglob("BUILD.bazel")):
        if "bazel-" in path.parts[len(ROOT.parts)]:
            continue
        text = path.read_text(encoding="utf-8")
        if "@generated by tools/bazel/generate_build_files.py" not in text:
            continue
        for block in text.split("\n\n"):
            yield path, block


def properties_of(block: str) -> dict[str, str]:
    match = re.search(r"exec_properties = (\{[^}]*\})", block)
    return json.loads(match.group(1)) if match else {}


class CollectTest(unittest.TestCase):
    def test_only_lash_packages_are_measured(self) -> None:
        # The pool is shared: another repository's crate, even one with a Lash
        # crate's name, never reaches this table.
        lines = [record(cores=3.0)] * 20
        lines += [record(pkg="control-plane", crate="control_plane", cores=7.0)] * 50
        lines += [record(pkg="other-repo", crate="lash_core", cores=7.0)] * 50
        measured = sizes.collect(lines, CRATES)
        self.assertEqual(sorted(measured), ["lash-internal-core/lash_core"])
        self.assertEqual(len(measured["lash-internal-core/lash_core"].records), 20)

    def test_only_successful_compiles_of_a_second_or_more_count(self) -> None:
        lines = [
            record(tool="test-setup.sh"),
            record(tool="generate-xml.sh"),
            record(exit_status="137"),
            record(wall_ms=999),
            "torn line",
            "1789424023\tcrate=lash_core\tno-separator",
        ]
        self.assertEqual(sizes.collect(lines, CRATES), {})

    def test_first_party_crates_come_from_workspace_targets(self) -> None:
        metadata = {
            "packages": [
                {
                    "name": "lash-sim",
                    "targets": [
                        {"name": "lash_sim", "kind": ["lib"]},
                        {"name": "logical-turn", "kind": ["test"]},
                        {"name": "build-script-build", "kind": ["custom-build"]},
                    ],
                }
            ]
        }
        self.assertEqual(
            sizes.first_party_crates(metadata),
            {("lash-sim", "lash_sim"), ("lash-sim", "logical_turn")},
        )


class TableTest(unittest.TestCase):
    def test_cpu_is_the_p95_rounded_up_past_the_tolerance(self) -> None:
        # p95 of 19 x 1.0 and 1 x 2.5 cores is 1.0 (nearest rank), so 1 CPU;
        # memory keeps the row.
        lines = [record(cores=1.0, peak_bytes=2 * GIB)] * 19 + [record(cores=2.5)]
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 1)
        # 2.15 cores at p95 is within the tolerance of 2.
        lines = [record(cores=2.15)] * 20
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 2)
        # 2.25 is not.
        lines = [record(cores=2.25)] * 20
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 3)

    def test_cpu_is_capped_at_eight(self) -> None:
        lines = [record(cores=14.0)] * 20
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 8)
        self.assertEqual(sizes.MAX_CPU_COUNT, 8)

    def test_one_cpu_samples_are_left_out_when_larger_requests_exist(self) -> None:
        # Under a 1-CPU quota an action cannot show that it wants more.
        lines = [record(cores=1.0, requested_cpu="1")] * 200
        lines += [record(cores=2.0, requested_cpu="4")] * 20
        entry = table(lines)["lash-internal-core/lash_core"]
        self.assertEqual(entry["cpu_count"], 2)
        self.assertEqual(entry["samples"], 220)

    def test_one_cpu_samples_are_used_when_they_are_all_there_is(self) -> None:
        lines = [record(cores=1.6, requested_cpu="1")] * 20
        self.assertEqual(table(lines)["lash-internal-core/lash_core"]["cpu_count"], 2)

    def test_memory_follows_the_worst_peak_with_margin(self) -> None:
        lines = [record(cores=2.0, peak_bytes=GIB)] * 19
        lines += [record(cores=2.0, peak_bytes=3 * GIB)]
        entry = table(lines)["lash-internal-core/lash_core"]
        self.assertEqual(entry["peak_bytes"], 3 * GIB)
        # 3 GiB x 1.5 = 4.5 GiB, already a multiple of 512 MiB.
        self.assertEqual(entry["memory_kb"], 4718592)

    def test_memory_never_goes_below_the_default(self) -> None:
        lines = [record(cores=2.0, peak_bytes=GIB // 4)] * 20
        self.assertEqual(
            table(lines)["lash-internal-core/lash_core"]["memory_kb"],
            sizes.DEFAULT_MEMORY_KB,
        )

    def test_too_few_samples_make_no_row(self) -> None:
        lines = [record(pkg="lash-sim", crate="logical_turn", cores=4.0)] * (
            sizes.MIN_SAMPLES - 1
        )
        self.assertNotIn("lash-sim/logical_turn", table(lines))

    def test_a_row_at_the_defaults_is_dropped(self) -> None:
        lines = [record(pkg="lash-sim", crate="logical_turn", cores=1.0)] * 20
        self.assertNotIn("lash-sim/logical_turn", table(lines))

    def test_the_minimum_floor_keeps_and_roughly_sizes_a_row(self) -> None:
        saved = dict(sizes.MINIMUM_MEMORY_KB)
        try:
            sizes.MINIMUM_MEMORY_KB["lash-internal-core/lash_core"] = 5 * 1024 * 1024
            # The formula lands at 1.5 GiB from a 1 GiB peak; the floor wins.
            lines = [record(cores=2.0, peak_bytes=GIB)] * 20
            entry = table(lines)["lash-internal-core/lash_core"]
            self.assertEqual(entry["memory_kb"], 5242880)
            self.assertEqual(entry["cpu_count"], 2)
            # Too few samples to measure still yields the floor, not absence.
            entry = table([record(cores=1.0, peak_bytes=GIB)] * 3)[
                "lash-internal-core/lash_core"
            ]
            self.assertEqual(entry["memory_kb"], 5242880)
            self.assertEqual(entry["samples"], 3)
        finally:
            sizes.MINIMUM_MEMORY_KB.clear()
            sizes.MINIMUM_MEMORY_KB.update(saved)

    def test_a_measured_need_above_the_minimum_wins(self) -> None:
        saved = dict(sizes.MINIMUM_MEMORY_KB)
        try:
            sizes.MINIMUM_MEMORY_KB["lash-internal-core/lash_core"] = 2 * 1024 * 1024
            lines = [record(cores=2.0, peak_bytes=3 * GIB)] * 20
            self.assertEqual(
                table(lines)["lash-internal-core/lash_core"]["memory_kb"], 4718592
            )
        finally:
            sizes.MINIMUM_MEMORY_KB.clear()
            sizes.MINIMUM_MEMORY_KB.update(saved)

    def test_rendered_table_is_sorted_and_newline_terminated(self) -> None:
        lines = [record(cores=2.0)] * 20
        lines += [record(pkg="lash-sim", crate="logical_turn", cores=2.0)] * 20
        rendered = sizes.render(table(lines))
        self.assertTrue(rendered.endswith("}\n"))
        self.assertEqual(list(json.loads(rendered)), sorted(json.loads(rendered)))

    def test_the_checked_in_table_matches_the_documented_shape(self) -> None:
        checked_in = json.loads(
            (ROOT / "tools/bazel/action-sizes.json").read_text(encoding="utf-8")
        )
        inventory = json.loads(
            (ROOT / "tools/bazel/target-inventory.json").read_text(encoding="utf-8")
        )
        crates = {
            f"{package['package']}/{target['cargo'].replace('-', '_')}"
            for package in inventory["packages"]
            for target in package["targets"]
            if target.get("cargo")
        }
        self.assertTrue(checked_in)
        for key, entry in checked_in.items():
            with self.subTest(key=key):
                self.assertIn(key, crates, "a row that names no first-party crate is dead")
                self.assertEqual(
                    sorted(entry),
                    ["cpu_count", "memory_kb", "p95_cores", "peak_bytes", "samples"],
                )
                self.assertTrue(
                    entry["memory_kb"] > sizes.DEFAULT_MEMORY_KB
                    or entry["cpu_count"] > sizes.DEFAULT_CPU_COUNT,
                    "an entry that asks for no more than the defaults is noise",
                )
                self.assertEqual(entry["cpu_count"], sizes.cpu_count_for(entry["p95_cores"]))
                self.assertEqual(
                    entry["memory_kb"],
                    max(
                        sizes.memory_kb_for(entry["peak_bytes"]),
                        sizes.MINIMUM_MEMORY_KB.get(key, 0),
                    ),
                )
                self.assertTrue(
                    entry["samples"] >= sizes.MIN_SAMPLES
                    or key in sizes.MINIMUM_MEMORY_KB,
                    "an unmeasured row survives only on an explicit minimum",
                )


class CompileRequestTest(unittest.TestCase):
    """Plain `exec_properties` size compiles, from the measured row only."""

    def test_an_unmeasured_compile_states_nothing(self) -> None:
        for kind in ("lib", "bin"):
            with self.subTest(kind=kind):
                self.assertEqual(
                    generator.exec_properties("no-such-package", "no_such_crate", kind), {}
                )

    def test_a_measured_row_is_emitted_as_measured(self) -> None:
        key = "lash-internal-core/lash_core"
        entry = generator.ACTION_SIZES[key]
        self.assertEqual(
            generator.exec_properties("lash-internal-core", "lash_core", "lib"),
            {"cpu_count": str(entry["cpu_count"]), "memory_kb": str(entry["memory_kb"])},
        )

    def test_every_generated_compile_request_is_its_measured_row(self) -> None:
        seen = 0
        for path, block in generated_blocks():
            properties = properties_of(block)
            if "cpu_count" not in properties:
                continue
            if block.startswith("rust_doc("):
                # Covered by test_every_generated_doc_request_matches_its_library.
                continue
            package = re.search(r'package_name = "([^"]+)"', block)
            crate = re.search(r'crate_name = "([^"]+)"', block)
            self.assertIsNotNone(package, f"{path}: sized block without package_name")
            self.assertIsNotNone(crate, f"{path}: sized block without crate_name")
            entry = generator.ACTION_SIZES[f"{package.group(1)}/{crate.group(1)}"]
            seen += 1
            with self.subTest(path=str(path), crate=crate.group(1)):
                self.assertEqual(properties["cpu_count"], str(entry["cpu_count"]))
                self.assertEqual(properties["memory_kb"], str(entry["memory_kb"]))
        self.assertGreater(seen, 0)

    def test_every_generated_doc_request_matches_its_library(self) -> None:
        """A rust_doc target states exactly its library's compile row."""
        seen = 0
        per_file: dict[pathlib.Path, list[str]] = {}
        for path, block in generated_blocks():
            per_file.setdefault(path, []).append(block)
        for path, blocks in per_file.items():
            requests = {}
            for block in blocks:
                name = re.search(r'^    name = "([^"]+)"', block, re.M)
                if name and "cpu_count" in properties_of(block):
                    requests[name.group(1)] = properties_of(block)
            for block in blocks:
                if not block.startswith("rust_doc("):
                    continue
                crate = re.search(r'crate = ":([^"]+)"', block)
                self.assertIsNotNone(crate, f"{path}: rust_doc without a crate")
                properties = properties_of(block)
                seen += 1
                with self.subTest(path=str(path), doc=crate.group(1)):
                    self.assertEqual(properties, requests.get(crate.group(1), {}))
        self.assertGreater(seen, 0)


def run_record(
    label: str = "//crates/lash-core:runtime_turns__test",
    role: str = "run",
    cores: float = 1.0,
    peak_bytes: int = 100 * 1024 * 1024,
    wall_ms: int = 4_000,
    exit_status: str = "0",
    requested_cpu: str = "4",
) -> str:
    """A test action's usage record, as the supervisor writes it since kiln#28."""
    return "\t".join(
        [
            "1790160000",
            "crate=-",
            "pkg=-",
            "kind=-",
            "tool=test-setup.sh",
            f"peak_bytes={peak_bytes}",
            f"cpu_usec={int(cores * wall_ms * 1000)}",
            f"wall_ms={wall_ms}",
            f"exit={exit_status}",
            "requested_kb=4194304",
            f"requested_cpu={requested_cpu}",
            f"test={role}:-:{label}",
        ]
    )


TEST_LABELS = {"//crates/lash-core:runtime_turns__test", "//crates/lash-core:test_batch"}


def run_table(lines: list[str]) -> dict:
    return sizes.test_run_table(sizes.collect_test_runs(lines, TEST_LABELS))


class TestRunTableTest(unittest.TestCase):
    """Test runs are sized per Bazel label from the `test` field of the log."""

    def test_only_successful_runs_of_generated_labels_count(self) -> None:
        lines = [run_record()] * 3
        lines += [run_record(role="xml")] * 5
        lines += [run_record(exit_status="1")] * 5
        lines += [run_record(label="//crates/hirsel-proto:hirsel-proto__unit_test")] * 5
        # A compile record, and one written before the field existed.
        lines += [record()] * 5
        lines += [run_record().rsplit("\t", 1)[0]] * 5
        table_ = run_table(lines)
        self.assertEqual(list(table_), ["//crates/lash-core:runtime_turns__test"])
        self.assertEqual(table_["//crates/lash-core:runtime_turns__test"]["samples"], 3)

    def test_a_label_containing_colons_is_read_whole(self) -> None:
        label = "//crates/lash-core:test_batch"
        self.assertIn(label, run_table([run_record(label=label)] * 3))

    def test_three_samples_make_a_row_and_two_do_not(self) -> None:
        self.assertEqual(sizes.TEST_MIN_SAMPLES, 3)
        self.assertEqual(run_table([run_record()] * 2), {})
        self.assertEqual(len(run_table([run_record()] * 3)), 1)

    def test_memory_is_the_peak_with_margin_and_a_one_gib_floor(self) -> None:
        entry = run_table([run_record(peak_bytes=100 * 1024 * 1024)] * 3)
        self.assertEqual(entry["//crates/lash-core:runtime_turns__test"]["memory_kb"], 1048576)
        # 7.45 GiB x 1.5 = 11.2 GiB, rounded up to 11.5 GiB.
        entry = run_table([run_record(peak_bytes=7_999_586_304)] * 3)
        self.assertEqual(entry["//crates/lash-core:runtime_turns__test"]["memory_kb"], 12058624)

    def test_cpu_is_the_compile_p95_rule(self) -> None:
        entry = run_table([run_record(cores=2.15)] * 3)
        self.assertEqual(entry["//crates/lash-core:runtime_turns__test"]["cpu_count"], 2)
        entry = run_table([run_record(cores=2.25)] * 3)
        self.assertEqual(entry["//crates/lash-core:runtime_turns__test"]["cpu_count"], 3)
        entry = run_table([run_record(cores=20.0)] * 3)
        self.assertEqual(entry["//crates/lash-core:runtime_turns__test"]["cpu_count"], 8)

    def test_sub_second_runs_count_as_samples_but_not_as_cpu_evidence(self) -> None:
        entry = run_table([run_record(cores=3.0, wall_ms=400)] * 3)[
            "//crates/lash-core:runtime_turns__test"
        ]
        self.assertEqual((entry["samples"], entry["cpu_count"], entry["p95_cores"]), (3, 1, 0.0))
        lines = [run_record(cores=3.0, wall_ms=400)] * 3 + [run_record(cores=2.5)]
        entry = run_table(lines)["//crates/lash-core:runtime_turns__test"]
        self.assertEqual((entry["samples"], entry["cpu_count"]), (4, 3))

    def test_the_checked_in_table_names_generated_tests_only(self) -> None:
        checked_in = json.loads(
            (ROOT / "tools/bazel/test-run-sizes.json").read_text(encoding="utf-8")
        )
        inventory = json.loads(
            (ROOT / "tools/bazel/target-inventory.json").read_text(encoding="utf-8")
        )
        labels = sizes.test_labels(inventory)
        self.assertTrue(checked_in)
        for label, entry in checked_in.items():
            with self.subTest(label=label):
                self.assertIn(label, labels)
                self.assertEqual(
                    sorted(entry),
                    ["cpu_count", "memory_kb", "p95_cores", "peak_bytes", "samples"],
                )
                self.assertGreaterEqual(entry["samples"], sizes.TEST_MIN_SAMPLES)
                self.assertGreaterEqual(entry["memory_kb"], sizes.TEST_MEMORY_FLOOR_KB)
                self.assertTrue(1 <= entry["cpu_count"] <= sizes.MAX_CPU_COUNT)


class TestRunRequestTest(unittest.TestCase):
    """A test run is sized through the `test` exec group, apart from its compile."""

    def test_an_unmeasured_test_keeps_the_request_it_had(self) -> None:
        self.assertEqual(generator.UNMEASURED_TEST_RUN, {"cpu_count": 2, "memory_kb": 1048576})
        self.assertEqual(
            generator.exec_properties(
                "no-such-package", "no_such_crate", "test", "//no/such:test"
            ),
            {"test.cpu_count": "2", "test.memory_kb": "1048576"},
        )
        # An unmeasured run of a large suite keeps its larger request.
        self.assertEqual(
            generator.test_run_request(
                "lash-internal-core", "lash_core", "//crates/lash-core:never_measured"
            ),
            {"cpu_count": 8, "memory_kb": 6815744},
        )

    def test_a_measured_run_asks_for_its_row(self) -> None:
        label = "//crates/lash-core:lash-core__unit_test"
        row = generator.TEST_RUN_SIZES[label]
        properties = generator.exec_properties("lash-internal-core", "lash_core", "test", label)
        self.assertEqual(properties["test.cpu_count"], str(row["cpu_count"]))
        self.assertEqual(properties["test.memory_kb"], str(row["memory_kb"]))
        # The compile half is the measured compile row, not the run's size.
        self.assertEqual(
            properties["cpu_count"],
            str(generator.ACTION_SIZES["lash-internal-core/lash_core"]["cpu_count"]),
        )

    def test_a_feature_variant_inherits_its_base_labels_row(self) -> None:
        # A `__fv_` variant is the same binary under another resolution; the
        # pool rarely prices the variant's own label, so it must not fall back
        # to the unmeasured default.
        label = "//crates/lash-core:lash-core__unit_test"
        row = generator.TEST_RUN_SIZES[label]
        variant = generator.test_run_request(
            "lash-internal-core", "lash_core", f"{label}__fv_0123abcd"
        )
        self.assertEqual(
            variant, {"cpu_count": row["cpu_count"], "memory_kb": row["memory_kb"]}
        )
        # A variant with its own measured row still uses it.
        own = next(label for label in generator.TEST_RUN_SIZES if "__fv_" in label)
        self.assertEqual(
            generator.test_run_request("lash-internal-core", "lash_core", own),
            {
                "cpu_count": generator.TEST_RUN_SIZES[own]["cpu_count"],
                "memory_kb": generator.TEST_RUN_SIZES[own]["memory_kb"],
            },
        )

    def test_a_pinned_label_asks_for_its_pin(self) -> None:
        label = "//crates/lash-protocol-rlm:cell_binding_drift__test"
        pin = generator.PINNED_TEST_RUNS[label]
        self.assertEqual(
            generator.test_run_request(
                "lash-internal-protocol-rlm", "cell_binding_drift", label
            ),
            dict(pin),
        )
        # The pin reaches the feature variant through the base label.
        self.assertEqual(
            generator.test_run_request(
                "lash-internal-protocol-rlm", "cell_binding_drift", f"{label}__fv_0123abcd"
            ),
            dict(pin),
        )

    def test_timing_sensitive_suites_keep_four_cores(self) -> None:
        self.assertEqual(set(generator.CONTENTION_FLOOR["packages"]), {"lash-perf", "lash-sim"})
        label = "//crates/lash-perf:lash-perf__unit_test"
        self.assertLess(generator.TEST_RUN_SIZES[label]["cpu_count"], 4)
        self.assertEqual(
            generator.test_run_request("lash-perf", "lash_perf", label)["cpu_count"], 4
        )

    def test_a_test_target_must_name_its_label(self) -> None:
        with self.assertRaises(ValueError):
            generator.exec_properties("lash-sim", "lash_sim", "test")

    def test_every_generated_test_target_states_its_run(self) -> None:
        test_rules = (
            "lash_rust_unit_test(",
            "lash_rust_integration_test(",
            "lash_rust_feature_test(",
        )
        seen = 0
        for path, block in generated_blocks():
            if not block.startswith(test_rules):
                continue
            properties = properties_of(block)
            seen += 1
            package = path.parent.relative_to(ROOT).as_posix()
            name = re.search(r'name = "([^"]+)"', block).group(1)
            label = f"//{package}:{name}"
            with self.subTest(label=label):
                cpu = int(properties["test.cpu_count"])
                memory_kb = int(properties["test.memory_kb"])
                # A `__fv_` variant is sized by its base label's row or pin.
                base = label.split("__fv_", 1)[0]
                row = generator.TEST_RUN_SIZES.get(label) or generator.TEST_RUN_SIZES.get(base)
                pin = generator.PINNED_TEST_RUNS.get(label) or generator.PINNED_TEST_RUNS.get(base)
                if row is not None:
                    self.assertEqual(memory_kb, row["memory_kb"])
                    self.assertGreaterEqual(cpu, row["cpu_count"])
                elif pin is not None:
                    self.assertEqual(memory_kb, pin["memory_kb"])
                    self.assertGreaterEqual(cpu, pin["cpu_count"])
                else:
                    self.assertGreaterEqual(cpu, generator.UNMEASURED_TEST_RUN["cpu_count"])
                if package in ("crates/lash-perf", "crates/lash-sim"):
                    self.assertGreaterEqual(cpu, generator.CONTENTION_FLOOR["cpu_count"])
        self.assertGreater(seen, 0)

    def test_no_other_target_states_a_run(self) -> None:
        for path, block in generated_blocks():
            if block.startswith(("lash_rust_library(", "lash_rust_binary(", "lash_rust_feature_library(", "lash_rust_feature_binary(")):
                with self.subTest(path=str(path), block=block.splitlines()[1]):
                    self.assertFalse(
                        [key for key in properties_of(block) if key.startswith("test.")]
                    )


class BatchBudgetTest(unittest.TestCase):
    """A batch reserves what it runs, and runs no more than it reserves."""

    def test_the_large_suites_never_join_a_batch(self) -> None:
        for key in generator.LARGE_TEST_RUNS:
            with self.subTest(key=key):
                self.assertFalse(generator.batchable_run(*key.split("/")))
        self.assertTrue(generator.batchable_run("no-such-package", "no_such_crate"))

    def test_an_unmeasured_batch_reserves_its_two_largest_members(self) -> None:
        self.assertEqual(generator.BATCH_JOBS, 2)
        requests = [
            {"cpu_count": 1, "memory_kb": 1048576},
            {"cpu_count": 3, "memory_kb": 1048576},
            {"cpu_count": 2, "memory_kb": 2097152},
        ]
        self.assertEqual(
            generator.batch_budget("no-such-package", "//no/such:test_batch", requests),
            {"cpu_count": 5, "memory_kb": 3145728},
        )

    def test_a_measured_batch_reserves_its_row_regardless_of_members(self) -> None:
        # The member sum used to let one unmeasured member inflate a batch the
        # pool had already priced; the measured row now wins outright.
        label = "//crates/lash-core:test_batch"
        measured = generator.TEST_RUN_SIZES[label]
        for requests in (
            [{"cpu_count": 1, "memory_kb": 1048576}] * 3,
            [{"cpu_count": 8, "memory_kb": 4194304}] * 3,
        ):
            with self.subTest(requests=requests):
                self.assertEqual(
                    generator.batch_budget("lash-internal-core", label, requests),
                    {
                        "cpu_count": measured["cpu_count"],
                        "memory_kb": measured["memory_kb"],
                    },
                )

    def test_the_contention_floor_counts_once_per_batch(self) -> None:
        # lash-sim's batch measured at one core: the floor lifts the batch to
        # four, not two floored members to eight.
        label = "//crates/lash-perf:test_batch"
        measured = generator.TEST_RUN_SIZES[label]
        self.assertLess(measured["cpu_count"], generator.CONTENTION_FLOOR["cpu_count"])
        self.assertEqual(
            generator.batch_budget("lash-perf", label, []),
            {
                "cpu_count": generator.CONTENTION_FLOOR["cpu_count"],
                "memory_kb": measured["memory_kb"],
            },
        )
        # The unfloored member requests the callers pass keep the floor out of
        # the member sum of an unmeasured batch, too.
        members = [{"cpu_count": 1, "memory_kb": 1048576}] * 2
        self.assertEqual(
            generator.batch_budget("lash-sim", "//no/such:test_batch", members),
            {"cpu_count": 4, "memory_kb": 2097152},
        )

    def test_a_pinned_batch_reserves_its_pin(self) -> None:
        for package, label in (
            ("lash-internal-restate-test", "//crates/lash-restate-test:test_batch"),
            ("lash-internal-typescript", "//crates/lash-typescript:test_batch"),
        ):
            with self.subTest(label=label):
                pin = generator.PINNED_TEST_RUNS[label]
                members = [{"cpu_count": 2, "memory_kb": 1048576}] * 4
                self.assertEqual(generator.batch_budget(package, label, members), dict(pin))

    def test_every_generated_batch_reserves_its_budget(self) -> None:
        seen = 0
        for path, block in generated_blocks():
            if not block.startswith(("lash_batch_test(", 'load("//tools/bazel:test_batch.bzl"')):
                continue
            if "lash_batch_test(\n" not in block:
                continue
            seen += 1
            with self.subTest(path=str(path)):
                self.assertIn(f"    jobs = {generator.BATCH_JOBS},\n", block)
                cpu = int(re.search(r"    cpu_count = (\d+),", block).group(1))
                memory_kb = int(re.search(r"    memory_kb = (\d+),", block).group(1))
                package = path.parent.relative_to(ROOT).as_posix()
                label = f"//{package}:test_batch"
                row = generator.TEST_RUN_SIZES.get(label) or generator.PINNED_TEST_RUNS.get(label)
                if row is not None:
                    # A priced batch reserves its row or pin, lifted only by
                    # the contention floor.
                    self.assertGreaterEqual(cpu, row["cpu_count"])
                    self.assertEqual(memory_kb, row["memory_kb"])
                else:
                    # An unpriced batch still sums two members at once.
                    self.assertGreaterEqual(cpu, generator.BATCH_JOBS)
                    self.assertGreaterEqual(memory_kb, generator.BATCH_JOBS * 1048576)
        self.assertGreater(seen, 0)

    def test_the_rule_reserves_what_it_is_given_and_runs_jobs_at_once(self) -> None:
        bzl = (ROOT / "tools/bazel/test_batch.bzl").read_text(encoding="utf-8")
        self.assertIn('"test.cpu_count": str(cpu_count)', bzl)
        self.assertIn('"test.memory_kb": str(memory_kb)', bzl)
        self.assertIn("jobs = jobs", bzl)
        self.assertIn("export LASH_BATCH_JOBS={jobs}", bzl)
        runner = (ROOT / "tools/bazel/test_batch_runner.sh").read_text(encoding="utf-8")
        self.assertIn("jobs_cap=${LASH_BATCH_JOBS:?", runner)
        self.assertNotIn("nproc", runner)


class TableValidationTest(unittest.TestCase):
    def test_a_stale_row_fails_generation(self) -> None:
        metadata = {
            "workspace_members": ["id"],
            "packages": [
                {"id": "id", "name": "lash-sim", "targets": [{"name": "lash_sim", "kind": ["lib"]}]}
            ],
        }
        saved = dict(generator.ACTION_SIZES)
        saved_large = dict(generator.LARGE_TEST_RUNS)
        try:
            generator.ACTION_SIZES.clear()
            generator.LARGE_TEST_RUNS.clear()
            generator.ACTION_SIZES["lash-sim/lash_sim"] = {"cpu_count": 2}
            generator.validate_action_sizes(metadata)
            generator.ACTION_SIZES["gone/gone"] = {"cpu_count": 2}
            with self.assertRaises(SystemExit):
                generator.validate_action_sizes(metadata)
        finally:
            generator.ACTION_SIZES.clear()
            generator.ACTION_SIZES.update(saved)
            generator.LARGE_TEST_RUNS.clear()
            generator.LARGE_TEST_RUNS.update(saved_large)

    def test_a_measured_run_no_test_is_generated_for_fails_generation(self) -> None:
        saved = set(generator.EMITTED_TEST_LABELS)
        try:
            generator.EMITTED_TEST_LABELS.clear()
            generator.EMITTED_TEST_LABELS.update(
                set(generator.TEST_RUN_SIZES) | set(generator.PINNED_TEST_RUNS)
            )
            generator.validate_test_run_sizes()
            generator.EMITTED_TEST_LABELS.discard(next(iter(generator.TEST_RUN_SIZES)))
            with self.assertRaises(SystemExit):
                generator.validate_test_run_sizes()
        finally:
            generator.EMITTED_TEST_LABELS.clear()
            generator.EMITTED_TEST_LABELS.update(saved)


class DefaultsAgreeTest(unittest.TestCase):
    """The two defaults are written down in four places; they must match.

    `.bazelrc` is what the pool is actually asked for, the two tools decide
    which rows are worth keeping, and the generated `pool_sizes.bzl` is what
    the pool platform hands an aspect action that names no measured bucket.
    """

    def test_bazelrc_and_the_tools_agree(self) -> None:
        bazelrc = (ROOT / ".bazelrc").read_text(encoding="utf-8")
        for name, value in (
            ("cpu_count", sizes.DEFAULT_CPU_COUNT),
            ("memory_kb", sizes.DEFAULT_MEMORY_KB),
        ):
            self.assertIn(f"build --remote_default_exec_properties={name}={value}\n", bazelrc)
        self.assertEqual(generator.DEFAULT_CPU_COUNT, sizes.DEFAULT_CPU_COUNT)
        self.assertEqual(generator.DEFAULT_MEMORY_KB, sizes.DEFAULT_MEMORY_KB)

    def test_the_pool_platform_carries_the_same_unscoped_defaults(self) -> None:
        pool = (ROOT / "tools/bazel/pool_sizes.bzl").read_text(encoding="utf-8")
        self.assertIn(f'"cpu_count": "{sizes.DEFAULT_CPU_COUNT}"', pool)
        self.assertIn(f'"memory_kb": "{sizes.DEFAULT_MEMORY_KB}"', pool)

    def test_ci_inherits_the_same_defaults(self) -> None:
        action = (ROOT / ".github/actions/bazel-shared-cache/action.yml").read_text()
        for name in ("cpu_count", "memory_kb"):
            self.assertNotIn(f"--remote_default_exec_properties={name}=", action)


if __name__ == "__main__":
    unittest.main()
