//! The two-opener differential oracle (FIG-3429, ADR 0099 §3).
//!
//! A durable effect-group child's replay key is its *identity*; the retained
//! request is its *authority*. A successor process may legitimately recover
//! the group — but only the retained request may run, and only through
//! runners the recovering host resolved for that request.
//!
//! This oracle stands two opener deployments up that differ on every
//! dispatch-context axis [`REBIND_FIELDS`] rules — generated by an exhaustive
//! match over the checklist, no catch-all — registers both as live opener
//! contexts in real [`ToolChildHost`]s, and drives the retained children
//! through the production path: `open_effect_group` → the group-open
//! selector → `ToolChildRunner` → `rebind_child_dispatch` → the leaf bodies.
//! Every observable a child can produce — which provider ran its body, which
//! completion client it billed, whose ledger the settlement carries, whose
//! process registry its intents landed in, whose cooperative token stopped
//! it, and whose completion authority its deferred wait was issued under —
//! is asserted to be A's, the opener that admitted it.
//!
//! The negative control does not fake a resolver: it flips the group-open
//! selector itself to its `KeyOnly` strategy (a `cfg(testing)` knob inside
//! `groups.rs`) and stages executors bound to B's live context, so the same
//! retained envelopes run under B's deployment — and every A-assertion
//! fails, which is the proof the oracle names the leak.

use std::collections::HashMap;
use std::path::Path;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use lash_core::facade_support::{
    DirectCompletion, DirectCompletionClient, DirectRequest, InMemoryTriggerStore, LeaseTimings,
    PluginFactory, PluginHost, SessionAttachmentStore, SystemClock, TriggerRouter,
};
use lash_core::runtime::effect::RuntimeEffectControllerHandle;
use lash_core::runtime::effect::effect_replay_driver::{OfferedChildSelection, StoreReplayAdapter};
use lash_core::runtime::effect::{
    LiveOpenerContext, LiveOpenerGuard, ToolChildAdmission, ToolChildCompletionRouting,
    ToolChildHost, ToolChildRequest, ToolChildScope,
};
use lash_core::test_support::{AttachmentSourcePolicy, OpenAttachmentSourcePolicy};
use lash_core::testing::{
    MockSessionManager, TestClock, effect_backed_process_service, process_engine_fixture,
    process_engine_plugin_fixture, process_work_wiring_for_registry,
    publish_process_execution_env_for_testing, test_code_protocol_factories,
};
use lash_core::tool_dispatch::{
    CheckpointMessageBuffer, REBIND_FIELDS, RebindDisposition, RebindField,
    ToolAttemptEffectIdentity, ToolDispatchContext, ToolTriggerOutcomeBuffer,
};
use lash_core::{
    AdmittedScope, ArtifactOwner, AttemptOutcome, AttemptRecord, AttemptUsageDisposition,
    AwaitEventKey, AwaitEventResolver, CancellationToken, ChildDrainOutcome, EffectAddress,
    EffectHost, EffectOpener, EmitProcessEventIntent, ExecutionScope, FrameNodeId,
    GroupDrainReport, GroupExecutors, GroupWakePolicy, InMemoryProcessDefinitionRegistry,
    InMemoryProcessExecutionEnvStore, LlmCallId, LlmCallRecord, LoserPolicy, OnParentEnd,
    ParentScope, PendingCompletion, PluginOptions, PreparedToolCall, ProcessEngineRegistry,
    ProcessEventType, ProcessExecutionEnvRef, ProcessExecutionEnvSpec, ProcessId,
    ProcessIncarnation, ProcessInput, ProcessLifecyclePolicy, ProcessOriginator, ProcessRef,
    ProcessRegistrar, ProcessRegistration, ProcessRegistry, ProcessService,
    ProcessStartDeclaration, ProtocolPosition, RecoveryContract, Resolution, RuntimeAttribution,
    RuntimeEffectCommand, RuntimeEffectEnvelope, RuntimeEffectGroup, RuntimeEffectInvocation,
    RuntimeEffectLocalExecutor, RuntimeEffectOutcome, RuntimeInvocation, ScopedEffectController,
    SessionId, SessionPolicy, StartProcessIntent, StoreEffectGroupDrain, TestLocalProcessRegistry,
    ToolAttemptOutcome, ToolCatalog, ToolContract, ToolDefinition, ToolExecutionGrant, ToolFailure,
    ToolFailureClass, ToolId, ToolIntent, ToolIntents, ToolManifest, ToolOutcome, ToolOutcomeDone,
    ToolProvider, ToolRegistry, ToolRetryPolicy, TurnBudget, TurnContext, TurnControlBindingId,
};
use lash_sansio::sync::MutexExt as _;
use lash_sqlite_store::{SqliteEffectHost, SqliteEffectReplayOptions};
use tokio::sync::Notify;

const LEASE: Duration = Duration::from_millis(900);
const POLL: Duration = Duration::from_millis(25);
const SETTLE_BUDGET: Duration = Duration::from_secs(30);
const ABSENCE_BUDGET: Duration = Duration::from_secs(2);
const RUN: LoserPolicy = LoserPolicy::RunToCompletion;

/// The leaf tools the admitting opener's children call. A deferred leaf
/// parks on a completion key, a spend leaf bills a managed call and declares
/// intents, a gate leaf waits on the cooperative token, and an observe leaf
/// carries a grant — one observable lane of the lent deployment each.
const TOOL_OBSERVE: &str = "tool:a_observe";
const TOOL_SPEND: &str = "tool:a_spend";
const TOOL_DEFER: &str = "tool:a_defer";
const TOOL_GATE: &str = "tool:a_gate";
/// The only tool B's own deployment serves honestly: its offered children
/// never run, so this exists only to keep B's registry non-empty.
const TOOL_B_PROBE: &str = "tool:b_probe";

const INTENT_EVENT_TYPE: &str = "differential.intent";

/// The number of children in the group: one per leaf lane.
const ARITY: usize = 4;

// =============================================================================
// Observation
// =============================================================================

/// What one leaf execution reported back.
#[derive(Clone, Debug)]
struct LeafExecution {
    /// The tool name the leaf was invoked under.
    tool: String,
    /// The session the attempt context was bound to — the child's recorded
    /// session when the driver honoured the retained request.
    session_id: String,
    /// The one-based attempt number.
    attempt: u32,
    /// The execution binding the attempt carried — the grant's, for the
    /// granted leaf.
    execution_binding: serde_json::Value,
    /// The enclosing process the attempt's context reported.
    enclosing_process: Option<String>,
}

/// The shared observation surface between a provider and the oracle.
#[derive(Default)]
struct Observation {
    /// Executions in the order the runtime produced them.
    executions: Mutex<Vec<LeafExecution>>,
    /// The completion key each deferrable leaf took, keyed by call id.
    parked_keys: Mutex<HashMap<String, AwaitEventKey>>,
    /// Signalled whenever `parked_keys` gains an entry.
    parked: Notify,
    /// How many gate leaves have entered and parked on their token.
    gate_entered: AtomicUsize,
}

impl Observation {
    fn record(&self, call: &lash_core::ToolCall<'_>) {
        let context = call.context;
        self.executions.lock_recover().push(LeafExecution {
            tool: call.name().to_string(),
            session_id: context.session_id().to_string(),
            attempt: context.attempt_number(),
            execution_binding: context.tool_execution_binding().clone(),
            enclosing_process: context.enclosing_process().map(str::to_string),
        });
    }

    fn executions(&self) -> Vec<LeafExecution> {
        self.executions.lock_recover().clone()
    }

    fn park(&self, call_id: &str, key: AwaitEventKey) {
        self.parked_keys
            .lock_recover()
            .insert(call_id.to_string(), key);
        self.parked.notify_waiters();
    }

    /// Waits until the leaf under `call_id` has parked, and answers its key.
    async fn parked_key(&self, call_id: &str) -> AwaitEventKey {
        tokio::time::timeout(SETTLE_BUDGET, async {
            loop {
                if let Some(key) = self.parked_keys.lock_recover().get(call_id).cloned() {
                    return key;
                }
                self.parked.notified().await;
            }
        })
        .await
        .unwrap_or_else(|_| {
            panic!("the deferred leaf under `{call_id}` never parked on a completion key")
        })
    }
}

// =============================================================================
// The opener deployments — every checklist field, per side
// =============================================================================

/// One opener's live deployment: the real value it supplies for every
/// [`RebindField`], plus the request-side facts the retained authority is
/// built from.
///
/// `axis_value` is the checklist's exhaustive conscience — one arm per field,
/// no catch-all, so a field added to `REBIND_FIELDS` fails compilation until
/// a human decides what each opener supplies for it. This struct holds what
/// those arms describe and `build_dispatch` wires them into a real
/// `ToolDispatchContext`.
struct OpenerDeployment {
    /// `RebindField::Plugins` — the factories the plugin session is built from.
    plugin_factories: Vec<Arc<dyn PluginFactory>>,
    /// Recorded so the axis can name the composition without introspection.
    plugin_ids: &'static str,
    /// `RebindField::Tools` — the leaf provider.
    provider: Arc<ProfileProvider>,
    /// `RebindField::ToolRegistry` — the registry the dispatch consults.
    tool_registry: Arc<ToolRegistry>,
    /// `RebindField::ToolCatalog` — the catalog definitions the context holds
    /// (rebound per child from the recorded admission at run time; the lent
    /// half still differs so a leak would be visible in routing).
    catalog_definitions: Vec<ToolDefinition>,
    /// `RebindField::{Sessions, SessionLifecycle, SessionGraph}` — the side's
    /// own session host object.
    session_host: Arc<MockSessionManager>,
    /// `RebindField::Processes` — the process service over the side's own
    /// registry.
    processes: Arc<dyn ProcessService>,
    /// The registry `processes` serves, kept so intent realization can be
    /// observed on A's and proven absent on B's.
    process_registry: Arc<TestLocalProcessRegistry>,
    /// `RebindField::TriggerRouter` — A none, B a real router over its own
    /// trigger store.
    trigger_router: Option<TriggerRouter>,
    /// `RebindField::ProcessDefinitions` — A none, B a real empty registry.
    process_definitions: Option<Arc<dyn lash_core::ProcessDefinitionRegistry>>,
    /// `RebindField::ProcessEngines` — A empty, B the fixture engine.
    process_engines: ProcessEngineRegistry,
    /// `RebindField::DirectCompletions` — the log this side's client bills
    /// into, and the canned completion it answers with.
    completion_log: Arc<Mutex<Vec<String>>>,
    completion_canned: DirectCompletion,
    /// `RebindField::ParentInvocation` — the dispatch's installed parent.
    parent_invocation: RuntimeInvocation,
    /// `RebindField::ExecutionEnvSpec` — the side's own environment.
    env_spec: ProcessExecutionEnvSpec,
    env_ref: ProcessExecutionEnvRef,
    /// `RebindField::SessionId` / `AgentFrameId` — the rebound pair, also
    /// carried by the request.
    session_id: SessionId,
    agent_frame_id: FrameNodeId,
    /// `RebindField::AttachmentStore` / `AttachmentSourcePolicy` — the side's
    /// own instances.
    attachment_store: Arc<SessionAttachmentStore>,
    attachment_source_policy: Arc<dyn AttachmentSourcePolicy>,
    /// `RebindField::TurnContext` — the side's own turn context.
    turn_context: TurnContext,
    /// `RebindField::Clock` — A the system clock, B a test clock.
    clock: Arc<dyn lash_core::Clock>,
    /// The request-side facts: the opener arm, the admitted scope pair, the
    /// recorded cancellation authority, the enclosing process, the completion
    /// routing.
    opener: EffectOpener,
    admitted_scope: AdmittedScope,
    routing: ToolChildCompletionRouting,
    enclosing_process: Option<ProcessRef>,
    /// A label for assertions: "a" or "b".
    tag: &'static str,
}

impl OpenerDeployment {
    /// Builds the dispatch context this opener lends its children — a real
    /// `ToolDispatchContext`, field by field. `provider` overrides
    /// `self.provider` for the `tools` field, so the crash world can lend
    /// A's deployment with leaf bodies that park instead of serving. The
    /// literal and `axis_value`'s match fail to compile together the day the
    /// checklist grows.
    #[expect(
        clippy::expect_used,
        reason = "test support: a plugin session builds over these factories; a refusal panics the harness with its case name by design"
    )]
    fn build_dispatch(
        &self,
        provider: Arc<dyn ToolProvider>,
        controller: ScopedEffectController<'static>,
    ) -> Arc<ToolDispatchContext<'static>> {
        let plugins = PluginHost::new(self.plugin_factories.clone())
            .build_session(&self.session_id)
            .expect("the side's plugin session builds");
        let (event_tx, _event_rx) = tokio::sync::mpsc::channel(1);
        let completion_log = Arc::clone(&self.completion_log);
        let canned = self.completion_canned.clone();
        Arc::new(ToolDispatchContext {
            plugins,
            tools: provider,
            tool_registry: Some(Arc::clone(&self.tool_registry)),
            tool_catalog: Arc::new(ToolCatalog::from_tool_definitions(
                self.catalog_definitions.clone(),
            )),
            sessions: self.session_host.clone(),
            session_lifecycle: self.session_host.clone(),
            session_graph: self.session_host.clone(),
            processes: Arc::clone(&self.processes),
            trigger_router: self.trigger_router.clone(),
            process_definitions: self.process_definitions.clone(),
            process_engines: self.process_engines.clone(),
            effect_controller: RuntimeEffectControllerHandle::borrowed(controller),
            direct_completions: DirectCompletionClient::from_fn(move |request, source| {
                completion_log
                    .lock_recover()
                    .push(format!("{source}:{}", request.model));
                Ok(canned.clone())
            }),
            parent_invocation: Some(self.parent_invocation.clone()),
            execution_env_spec: self.env_spec.clone(),
            session_id: self.session_id.clone(),
            agent_frame_id: self.agent_frame_id.clone(),
            event_tx,
            checkpoint_messages: CheckpointMessageBuffer::default(),
            trigger_outcomes: ToolTriggerOutcomeBuffer::default(),
            attachment_store: Arc::clone(&self.attachment_store),
            attachment_source_policy: Arc::clone(&self.attachment_source_policy),
            turn_context: self.turn_context.clone(),
            clock: Arc::clone(&self.clock),
        })
    }

    /// Registers this opener's context as live in `installed`'s registry,
    /// returning the registration guard — the registration's whole lifetime.
    /// `provider` is what the lent dispatch serves as `tools`.
    #[expect(
        clippy::expect_used,
        reason = "test support: the dispatch context is 'static and the scope binds; a refusal panics the harness with its case name by design"
    )]
    fn register_opener(
        &self,
        host: &Arc<SqliteEffectHost>,
        installed: &Arc<ToolChildHost>,
        provider: Arc<dyn ToolProvider>,
        cooperative: &CancellationToken,
    ) -> (LiveOpenerGuard, LiveOpenerContext) {
        let controller = host
            .scoped_static(self.admitted_scope.clone())
            .expect("the host lends a scoped controller")
            .expect("this host hands out owned scoped controllers");
        let dispatch = self.build_dispatch(provider, controller);
        let lent_controller = host
            .scoped_static(self.admitted_scope.clone())
            .expect("the host lends a scoped controller")
            .expect("this host hands out owned scoped controllers");
        let (event_tx, mut event_rx) = tokio::sync::mpsc::channel(64);
        let context = LiveOpenerContext::capture_with_event_sender(
            &dispatch,
            lent_controller,
            event_tx,
            cooperative.clone(),
        );
        let (guard, ended) = installed
            .openers()
            .register(self.opener.clone(), context.clone());
        // The registration owns the sender's lifetime: the forwarder ends
        // when the entry leaves the registry, exactly as the turn path's does.
        tokio::spawn(async move {
            tokio::select! {
                _ = ended.cancelled() => {}
                _ = async { while event_rx.recv().await.is_some() {} } => {}
            }
        });
        (guard, context)
    }
}

/// The fixture-visible value one side supplies for `field`, as a string a
/// failing assert can name.
///
/// **One arm per checklist line, no catch-all.** A `RebindField` added to
/// [`REBIND_FIELDS`] is a compile error here until a human decides what each
/// opener supplies for it — the exhaustive match is the fixture contract the
/// review requires, not a convenience. `Rebound` fields read their value out
/// of the retained request, because the request is the authority the child
/// runs under; `Lent` fields read the deployment object itself; `Fresh`
/// fields carry no recorded fact and answer a constant.
#[expect(
    clippy::expect_used,
    reason = "test support: every request and deployment value serializes; a refusal panics the harness with its case name by design"
)]
fn axis_value(
    deployment: &OpenerDeployment,
    request: &ToolChildRequest,
    field: RebindField,
) -> String {
    match field {
        // --- Lent: the live deployment wiring the child borrows. ---
        RebindField::Plugins => deployment.plugin_ids.to_string(),
        RebindField::Tools => deployment.provider.tag.to_string(),
        RebindField::ToolRegistry => format!("{:p}", Arc::as_ptr(&deployment.tool_registry)),
        RebindField::Sessions => format!("{:p}", Arc::as_ptr(&deployment.session_host)),
        RebindField::SessionLifecycle => {
            format!("lifecycle:{:p}", Arc::as_ptr(&deployment.session_host))
        }
        RebindField::SessionGraph => {
            format!("graph:{:p}", Arc::as_ptr(&deployment.session_host))
        }
        RebindField::Processes => format!("{:p}", Arc::as_ptr(&deployment.process_registry)),
        RebindField::TriggerRouter => format!("router:{}", deployment.trigger_router.is_some()),
        RebindField::ProcessDefinitions => {
            format!("definitions:{}", deployment.process_definitions.is_some())
        }
        RebindField::ProcessEngines => format!("engines:{}", deployment.tag),
        RebindField::EventTx => format!("event-tx:{}", deployment.tag),
        RebindField::AttachmentStore => {
            format!("{:p}", Arc::as_ptr(&deployment.attachment_store))
        }
        RebindField::AttachmentSourcePolicy => {
            format!("{:p}", Arc::as_ptr(&deployment.attachment_source_policy))
        }
        RebindField::TurnContext => format!("turn-context:{}", deployment.tag),
        RebindField::Clock => format!("{:p}", Arc::as_ptr(&deployment.clock)),
        // --- Rebound: the recorded request is the authority. ---
        RebindField::ToolCatalog => {
            serde_json::to_string(&request.admission).expect("the admission serializes")
        }
        RebindField::EffectController => format!("{:?}", request.scope.admitted_scope),
        RebindField::DirectCompletions => serde_json::to_string(&request.completion_routing)
            .expect("the completion routing serializes"),
        RebindField::ParentInvocation => serde_json::to_string(&request.attempt_identity)
            .expect("the attempt identity serializes"),
        RebindField::ExecutionEnvSpec => request.execution_env.as_str().to_string(),
        RebindField::SessionId => request.scope.session_id.to_string(),
        RebindField::AgentFrameId => request.scope.agent_frame_id.to_string(),
        // --- Fresh: the child mints its own buffers; nothing to differ. ---
        RebindField::CheckpointMessages => "fresh".to_string(),
        RebindField::TriggerOutcomes => "fresh".to_string(),
    }
}

// =============================================================================
// The leaf provider
// =============================================================================

/// One opener's tool provider. In `serve` mode it runs the four leaf lanes
/// and records every execution; in `park` mode a body reports it started and
/// then never returns — the crash world's in-flight children. In `impostor`
/// mode (B's deployment under the leak) it answers any tool id with a
/// B-tagged output, so a retained A request executed under B's context is
/// observable as B's impl running A's work.
struct ProfileProvider {
    tag: &'static str,
    park: bool,
    impostor: bool,
    observation: Arc<Observation>,
    /// The session the intents leaf declares on (the side's own).
    session_id: SessionId,
    /// The process the intents leaf emits to, registered on the side's own
    /// registry.
    intent_target: ProcessId,
}

/// One definition per A-side leaf lane, plus the retry policy the spend leaf
/// needs: two billed attempts inside one journaled retry.
fn leaf_definitions() -> Vec<ToolDefinition> {
    [TOOL_OBSERVE, TOOL_SPEND, TOOL_DEFER, TOOL_GATE]
        .into_iter()
        .map(|id| {
            let name = id.trim_start_matches("tool:");
            let mut definition = ToolDefinition::raw(
                id,
                name,
                format!("differential leaf {name}"),
                ToolDefinition::default_input_schema(),
                serde_json::json!({ "type": "object", "additionalProperties": true }),
            );
            if id == TOOL_SPEND {
                definition = definition.with_retry_policy(ToolRetryPolicy::safe(3, 0, 0));
            }
            definition
        })
        .collect()
}

/// B's catalog: its own probe tool — B's deployment never serves A's leaves
/// through the catalog, which is what makes a leaked execution legible.
fn b_catalog_definitions() -> Vec<ToolDefinition> {
    vec![ToolDefinition::raw(
        TOOL_B_PROBE,
        TOOL_B_PROBE.trim_start_matches("tool:"),
        "differential impostor probe",
        ToolDefinition::default_input_schema(),
        serde_json::json!({ "type": "object", "additionalProperties": true }),
    )]
}

#[async_trait::async_trait]
impl ToolProvider for ProfileProvider {
    fn tool_manifests(&self) -> Vec<ToolManifest> {
        let mut definitions = leaf_definitions();
        definitions.extend(b_catalog_definitions());
        definitions
            .iter()
            .map(|definition| definition.manifest())
            .collect()
    }

    fn resolve_contract(&self, name: &str) -> Option<Arc<ToolContract>> {
        leaf_definitions()
            .into_iter()
            .chain(b_catalog_definitions())
            .find(|definition| definition.manifest().name == name)
            .map(|definition| Arc::new(definition.contract()))
    }

    fn attempt_may_defer(&self, tool_id: &ToolId) -> bool {
        *tool_id == ToolId::from(TOOL_DEFER)
    }

    async fn execute(&self, call: lash_core::ToolCall<'_>) -> ToolAttemptOutcome {
        let name = call.name().to_string();
        self.observation.record(&call);
        if self.park {
            // The crash world's children: in flight forever.
            std::future::pending::<()>().await;
            unreachable!("a parked leaf body is never polled to completion");
        }
        if self.impostor {
            // B's deployment under the leak: any retained request is served by
            // B's impl, observably tagged.
            return ToolAttemptOutcome::done_without_intents(ToolOutcomeDone::ok(
                serde_json::json!({ "impostor": self.tag, "tool": name }),
            ));
        }
        let context = call.context;
        match name.as_str() {
            "a_observe" => ToolAttemptOutcome::done_without_intents(ToolOutcomeDone::ok(
                serde_json::json!({ "impl": "a", "leaf": "observe" }),
            )),
            "a_spend" => {
                // The managed-LLM spend is billed through the lent completion
                // client on *every* attempt — the failed first attempt's spend
                // is a fact the ledger must carry (FIG-3429 item 7's class).
                if let Err(error) = context
                    .direct_completions()
                    .complete(
                        DirectRequest::text("model-a", "the spend the ledger must carry"),
                        "a-spend",
                    )
                    .await
                {
                    return ToolOutcome::err_fmt(format!(
                        "the spend leaf's direct completion failed: {error}"
                    ))
                    .into();
                }
                if context.attempt_number() == 1 {
                    ToolOutcome::failure(ToolFailure::safe_retry(
                        ToolFailureClass::Internal,
                        "a_spend_first_attempt",
                        "the first attempt is journaled as a retryable failure",
                        Some(0),
                    ))
                    .into()
                } else {
                    ToolAttemptOutcome::done(
                        ToolOutcomeDone::ok(serde_json::json!({ "impl": "a", "leaf": "spend" })),
                        ToolIntents::v3(vec![
                            ToolIntent::StartProcess(Box::new(StartProcessIntent {
                                session_id: self.session_id.clone(),
                                declaration: ProcessStartDeclaration::external(
                                    ProcessOriginator::host(),
                                    serde_json::json!({ "impl": "a", "leaf": "spend" }),
                                    ProcessLifecyclePolicy::new(
                                        ParentScope::Host,
                                        OnParentEnd::Abandon,
                                    ),
                                ),
                            })),
                            ToolIntent::EmitProcessEvent(EmitProcessEventIntent {
                                session_id: self.session_id.clone(),
                                process_id: self.intent_target.clone(),
                                event_type: INTENT_EVENT_TYPE.to_string(),
                                payload: serde_json::json!({ "impl": "a", "leaf": "spend" }),
                            }),
                        ]),
                    )
                }
            }
            "a_defer" => match context.completion_key() {
                Ok(key) => {
                    let call_id = context
                        .tool_call_id()
                        .unwrap_or("missing-call-id")
                        .to_string();
                    self.observation.park(&call_id, key);
                    ToolAttemptOutcome::pending(PendingCompletion::new())
                }
                Err(error) => ToolOutcome::err_fmt(format!(
                    "the deferred leaf could not take a completion key: {error}"
                ))
                .into(),
            },
            "a_gate" => match context.cancellation_token() {
                Some(token) => {
                    self.observation.gate_entered.fetch_add(1, Ordering::SeqCst);
                    token.cancelled().await;
                    ToolOutcome::cancelled("the opener's cooperative gate stopped this attempt")
                        .into()
                }
                None => {
                    ToolOutcome::err_fmt("the gate leaf found no cooperative cancellation token")
                        .into()
                }
            },
            other => {
                ToolOutcome::err_fmt(format!("the differential has no A-side leaf named {other}"))
                    .into()
            }
        }
    }
}

/// The canned managed-LLM completion each side's client answers with. The
/// token counts differ per side so the settlement's ledger says *whose*
/// client was billed, not just that billing happened.
fn canned_completion(tag: &'static str, input: i64, output: i64) -> DirectCompletion {
    DirectCompletion {
        text: format!("{tag} direct completion"),
        usage: lash_core::TokenUsage {
            input_tokens: input,
            output_tokens: output,
            ..lash_core::TokenUsage::default()
        },
        llm_call: LlmCallRecord {
            call_id: LlmCallId(format!("{tag}-direct-call")),
            label: None,
            replay_drops: Vec::new(),
            attempts: vec![AttemptRecord {
                ordinal: 1,
                started_at: 0,
                duration: Duration::ZERO,
                outcome: AttemptOutcome::Completed,
                protocol_position: ProtocolPosition::ResponseObserved,
                retry_budget_consumed: false,
                retry_decision: None,
                error: None,
                evidence: None,
                generation_disposition: None,
                usage: Some(lash_core::llm::types::LlmUsage {
                    input_tokens: input,
                    output_tokens: output,
                    cache_read_input_tokens: 0,
                    cache_write_input_tokens: 0,
                    reasoning_output_tokens: 0,
                }),
                usage_disposition: AttemptUsageDisposition::default(),
            }],
        },
    }
}

// =============================================================================
// Requests and groups
// =============================================================================

/// The request one retained child carries — the whole of the authority it
/// was admitted under.
fn request(
    side: &OpenerDeployment,
    call_id: &str,
    tool_id: &str,
    admission: ToolChildAdmission,
    cancellation: Option<TurnControlBindingId>,
) -> ToolChildRequest {
    let tool_name = tool_id.trim_start_matches("tool:");
    let call = PreparedToolCall::from_parts(
        call_id,
        ToolId::from(tool_id),
        tool_name,
        serde_json::json!({ "side": side.tag }),
        None,
        serde_json::Value::Null,
    );
    let mut request = ToolChildRequest::new(
        call,
        admission,
        ToolAttemptEffectIdentity::Scalar {
            parent: Some(side.parent_invocation.clone()),
        },
        ToolChildScope {
            opener: side.opener.clone(),
            admitted_scope: side.admitted_scope.clone(),
            session_id: side.session_id.clone(),
            agent_frame_id: side.agent_frame_id.clone(),
        },
        side.env_ref.clone(),
        side.routing.clone(),
    );
    if let Some(binding) = cancellation {
        request = request.with_cancellation_authority(binding);
    }
    if let Some(process) = &side.enclosing_process {
        request = request.with_enclosing_process(process.clone());
    }
    request
}

/// A's four retained children: one leaf lane each.
fn requests_a(
    side: &OpenerDeployment,
    group_key: &str,
    cancellation: Option<TurnControlBindingId>,
) -> Vec<ToolChildRequest> {
    let definitions = leaf_definitions();
    [TOOL_OBSERVE, TOOL_SPEND, TOOL_DEFER, TOOL_GATE]
        .into_iter()
        .map(|tool_id| {
            let admission = if tool_id == TOOL_OBSERVE {
                // A grant: authority the live catalog never saw, recorded in
                // the request alone.
                let definition = definitions
                    .iter()
                    .find(|definition| definition.manifest().id == ToolId::from(TOOL_OBSERVE))
                    .unwrap_or_else(|| unreachable!("the observe leaf has a definition"));
                ToolChildAdmission::Granted {
                    grant: Box::new(
                        ToolExecutionGrant::from_definition(definition.clone())
                            .with_source_id("source-a")
                            .with_execution_binding(serde_json::json!({ "opener": "a" })),
                    ),
                }
            } else {
                let manifest = definitions
                    .iter()
                    .find(|definition| definition.manifest().id == ToolId::from(tool_id))
                    .unwrap_or_else(|| unreachable!("every leaf has a definition"))
                    .manifest();
                ToolChildAdmission::Catalog {
                    manifest: Box::new(manifest),
                }
            };
            request(
                side,
                &format!("{group_key}-call-{}", position_of(tool_id)),
                tool_id,
                admission,
                cancellation.clone(),
            )
        })
        .collect()
}

/// B's offered children: same replay-key positions, B's own requests.
fn requests_b(
    side: &OpenerDeployment,
    group_key: &str,
    cancellation: Option<TurnControlBindingId>,
) -> Vec<ToolChildRequest> {
    let manifest = b_catalog_definitions()
        .first()
        .unwrap_or_else(|| unreachable!("the probe tool has a definition"))
        .manifest();
    (0..ARITY)
        .map(|position| {
            request(
                side,
                &format!("{group_key}-bcall-{position}"),
                TOOL_B_PROBE,
                ToolChildAdmission::Catalog {
                    manifest: Box::new(manifest.clone()),
                },
                cancellation.clone(),
            )
        })
        .collect()
}

fn position_of(tool_id: &str) -> usize {
    [TOOL_OBSERVE, TOOL_SPEND, TOOL_DEFER, TOOL_GATE]
        .iter()
        .position(|id| *id == tool_id)
        .unwrap_or_else(|| unreachable!("a leaf tool id"))
}

fn child_key(group_key: &str, position: usize) -> String {
    format!("{group_key}:child:{position}")
}

#[expect(
    clippy::expect_used,
    reason = "test support: the fixture's addresses are valid by construction; a refusal panics the harness with its case name by design"
)]
fn child_envelope(
    scope: &ExecutionScope,
    group_key: &str,
    position: usize,
    request: &ToolChildRequest,
) -> RuntimeEffectEnvelope {
    RuntimeEffectEnvelope::new(
        RuntimeEffectInvocation::new(
            EffectAddress::new(scope.clone(), child_key(group_key, position))
                .expect("valid group-child address"),
            RuntimeAttribution::none(),
            "effect",
        ),
        RuntimeEffectCommand::ToolInvocation {
            request: Box::new(request.clone()),
        },
    )
}

/// The group over per-position requests — replay keys identical whichever
/// side's requests built them.
#[expect(
    clippy::expect_used,
    reason = "test support: the fixture's addresses are valid by construction; a refusal panics the harness with its case name by design"
)]
fn group(scope: &ExecutionScope, key: &str, requests: &[ToolChildRequest]) -> RuntimeEffectGroup {
    RuntimeEffectGroup::try_new(
        RuntimeEffectInvocation::new(
            EffectAddress::new(scope.clone(), format!("{key}:group")).expect("valid group address"),
            RuntimeAttribution::none(),
            "group",
        ),
        key,
        requests
            .iter()
            .enumerate()
            .map(|(position, request)| child_envelope(scope, key, position, request))
            .collect(),
        GroupWakePolicy::All,
        RUN,
    )
    .expect("a group with at least one child assembles")
}

// =============================================================================
// Worlds
// =============================================================================

/// One host over the shared journal.
#[expect(
    clippy::expect_used,
    reason = "test support: a fresh temp journal opens; a refusal panics the harness with its case name by design"
)]
async fn world(path: &Path) -> Arc<SqliteEffectHost> {
    Arc::new(
        SqliteEffectHost::open_with_options(
            path,
            SqliteEffectReplayOptions {
                lease_timings: LeaseTimings::new(LEASE, LEASE / 3)
                    .expect("a lease at least three renew intervals wide"),
                drain_budget: Default::default(),
            },
        )
        .await
        .expect("the SQLite effect host opens"),
    )
}

/// Installs the tool-child host on `host`, returning the installed resolver.
#[expect(
    clippy::expect_used,
    reason = "test support: a tier that routes tool children installs the child host; a refusal panics the harness with its case name by design"
)]
fn install_child_host(
    host: &Arc<SqliteEffectHost>,
    process_env_store: &Arc<dyn lash_core::ProcessExecutionEnvStore>,
) -> Arc<ToolChildHost> {
    let dyn_host: Arc<dyn EffectHost> = Arc::clone(host) as Arc<dyn EffectHost>;
    host.install_tool_child_host(ToolChildHost::new(&dyn_host, Arc::clone(process_env_store)))
        .expect("a host that routes tool children installs the child host")
}

/// The cancellation authority the opener records on a child at group
/// formation: what this host derives for the child's admitted scope — or
/// `None` where the controller participates locally.
#[expect(
    clippy::expect_used,
    reason = "test support: a durable participant's binding derives; a refusal panics the harness with its case name by design"
)]
async fn recorded_cancellation_authority(
    host: &Arc<SqliteEffectHost>,
    admitted: &AdmittedScope,
) -> Option<TurnControlBindingId> {
    let scoped = host.scoped(admitted.clone()).expect("the scope binds");
    if scoped
        .controller()
        .turn_control_participation()
        .await
        .expect("participation resolves")
        != lash_core::runtime::effect::TurnControlParticipation::DurableJournaled
    {
        return None;
    }
    let binding = host
        .turn_control_binding(&scoped)
        .await
        .expect("a durable participant's binding derives");
    Some(
        TurnControlBindingId::new(binding.binding_id().to_string())
            .expect("the host's binding id is valid"),
    )
}

/// The crash: open the group under A's live opener with leaf bodies that
/// park, wait until every child is in flight, and destroy the runtime — the
/// shape a killed worker leaves: claimed, journaled children owned by
/// nobody.
#[expect(
    clippy::expect_used,
    reason = "test support: the crashing phase's thread, runtime and group open are fixture facts; a refusal panics the harness with its case name by design"
)]
fn crash_opening(
    path: &Path,
    group: RuntimeEffectGroup,
    admitted: AdmittedScope,
    side_a: &OpenerDeployment,
    park_provider: Arc<ProfileProvider>,
    process_env_store: Arc<dyn lash_core::ProcessExecutionEnvStore>,
    entered: Arc<Observation>,
) {
    let path = path.to_path_buf();
    // A scoped thread borrows `side_a` — the crashing process's registration
    // is a fact of this test's deployment, not a second fixture. The runtime
    // built inside dies with the thread, which is what makes the crash real:
    // the parked leaf bodies are aborted mid-poll.
    std::thread::scope(|s| {
        s.spawn(move || {
            let runtime = tokio::runtime::Builder::new_multi_thread()
                .worker_threads(2)
                .enable_all()
                .build()
                .expect("the crashing process gets a runtime of its own");
            runtime.block_on(async move {
                let world = world(&path).await;
                let installed = install_child_host(&world, &process_env_store);
                let _guard = side_a.register_opener(
                    &world,
                    &installed,
                    park_provider,
                    &CancellationToken::new(),
                );
                let scoped = world.scoped(admitted).expect("the group scope binds");
                let _handle = scoped
                    .controller()
                    .open_effect_group(group)
                    .await
                    .expect("the group opens under the live opener");
                let deadline = std::time::Instant::now() + SETTLE_BUDGET;
                while entered.executions().len() < ARITY {
                    assert!(
                        std::time::Instant::now() < deadline,
                        "the crash world's children never entered their leaf bodies"
                    );
                    tokio::time::sleep(POLL).await;
                }
            });
            drop(runtime);
        })
        .join()
        .expect("the crashing process runs its phase before dying");
    });
}

/// Waits until the crashed process's claims have lapsed, without running
/// anything: a probe whose child host has no openers answers `NoExecutor`,
/// which writes nothing.
async fn until_leases_lapse(
    path: &Path,
    group_key: &str,
    process_env_store: &Arc<dyn lash_core::ProcessExecutionEnvStore>,
) {
    let probe = world(path).await;
    install_child_host(&probe, process_env_store);
    let drain = probe.group_drain();
    drain_until_no_live_lease(&drain, group_key).await;
}

/// Drains until a pass finds nothing left under a live lease, and returns
/// that pass.
#[expect(
    clippy::expect_used,
    reason = "test support: a drain pass over a journaled group runs and the dead process's claims lapse; a refusal panics the harness with its case name by design"
)]
async fn drain_until_no_live_lease(
    drain: &Arc<dyn StoreEffectGroupDrain>,
    group_key: &str,
) -> GroupDrainReport {
    tokio::time::timeout(SETTLE_BUDGET, async {
        loop {
            let report = drain
                .drain_group(group_key, &CancellationToken::new())
                .await
                .expect("a drain pass over the group runs");
            if report
                .children
                .iter()
                .all(|child| !matches!(child.outcome, ChildDrainOutcome::LeaseLive { .. }))
            {
                return report;
            }
            tokio::time::sleep(POLL).await;
        }
    })
    .await
    .expect("the dead process's claims lapse")
}

/// The resolver the reoffering world registers: staged offered executors for
/// its own children, and the real [`ToolChildHost`] for everything else —
/// the routing question about a retained child is answered by production
/// routing, instrumented.
struct DifferentialResolvers {
    /// Executors bound to B's live context, staged under the offered
    /// children's replay keys.
    staged: Mutex<HashMap<String, RuntimeEffectLocalExecutor<'static>>>,
    /// The real child host the retained-children asks fall through to.
    retained: Arc<ToolChildHost>,
    /// The replay keys the driver re-resolved after the staged runners were
    /// discarded — the asks that prove the selector consulted the journal's
    /// retained membership.
    asked: Mutex<Vec<String>>,
}

impl GroupExecutors for DifferentialResolvers {
    fn executor_for(
        &self,
        envelope: &RuntimeEffectEnvelope,
    ) -> Option<RuntimeEffectLocalExecutor<'static>> {
        let replay_key = envelope.invocation.replay_key().to_string();
        if let Some(executor) = self.staged.lock_recover().remove(&replay_key) {
            return Some(executor);
        }
        self.asked.lock_recover().push(replay_key);
        self.retained.executor_for(envelope)
    }
}

// =============================================================================
// The fixture contract
// =============================================================================

/// The two deployments must differ on every axis the checklist rules — a
/// differential that agrees anywhere asserts nothing about that field — and
/// on the request-native axes the checklist does not name.
#[tokio::test]
async fn the_profiles_differ_on_every_axis_and_the_checklist_covers_them() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("fixture.db");
    let (a, b, requests_a, requests_b, _env_store) = fixture(&path, "fixture").await;

    for (position, (request_a, request_b)) in requests_a.iter().zip(requests_b.iter()).enumerate() {
        for field in REBIND_FIELDS {
            let value_a = axis_value(&a, request_a, *field);
            let value_b = axis_value(&b, request_b, *field);
            match field.disposition() {
                // A fresh field is minted empty per child — nothing recorded,
                // nothing to differ on.
                RebindDisposition::Fresh => assert_eq!(
                    value_a, value_b,
                    "a Fresh field carries no axis to differ on: {field:?}"
                ),
                RebindDisposition::Rebound | RebindDisposition::Lent => assert_ne!(
                    value_a, value_b,
                    "child {position}: opener deployments must differ on axis \
                     {field:?}: a differential that agrees asserts nothing"
                ),
            }
        }
        // The request-native axes the checklist does not name: the call, the
        // opener arm, the cancellation authority, the enclosing incarnation.
        assert_ne!(
            serde_json::to_string(&request_a.call).expect("the call serializes"),
            serde_json::to_string(&request_b.call).expect("the call serializes"),
            "child {position}: the calls must differ"
        );
        assert_ne!(
            serde_json::to_string(&request_a.scope.opener).expect("the opener serializes"),
            serde_json::to_string(&request_b.scope.opener).expect("the opener serializes"),
            "child {position}: the opener arms must differ"
        );
        // The cancellation authority is host-derived: on one journal every
        // admitted scope derives the same binding, so both requests record
        // it. What must differ — and the gate assertion proves it does — is
        // which opener's live cancellation source the binding resolves to.
        assert_eq!(
            serde_json::to_string(&request_a.cancellation_authority)
                .expect("the authority serializes"),
            serde_json::to_string(&request_b.cancellation_authority)
                .expect("the authority serializes"),
            "child {position}: the cancellation binding is the host's \
             derivation, shared by construction"
        );
        assert_ne!(
            serde_json::to_string(&request_a.enclosing_process)
                .expect("the enclosing process serializes"),
            serde_json::to_string(&request_b.enclosing_process)
                .expect("the enclosing process serializes"),
            "child {position}: the enclosing incarnations must differ"
        );
    }
}

// =============================================================================
// The deployments
// =============================================================================

/// Builds both opener deployments and their requests over one journal path.
///
/// Returns `(a, b, requests_a, requests_b)` with the recorded cancellation
/// authorities this journal's hosts will re-derive.
#[expect(
    clippy::expect_used,
    reason = "test support: the fixture's ids, envs and registrations are valid by construction; a refusal panics the harness with its case name by design"
)]
async fn fixture(
    path: &Path,
    prefix: &str,
) -> (
    OpenerDeployment,
    OpenerDeployment,
    Vec<ToolChildRequest>,
    Vec<ToolChildRequest>,
    Arc<dyn lash_core::ProcessExecutionEnvStore>,
) {
    let group_key = format!("{prefix}-group");
    // One shared environment store carrying both sides' specs: the retained
    // references differ and both resolve on every host.
    let env_store: Arc<dyn lash_core::ProcessExecutionEnvStore> =
        Arc::new(InMemoryProcessExecutionEnvStore::new());
    let owner = ArtifactOwner::host(format!("{prefix}-env"));
    let env_spec_a = ProcessExecutionEnvSpec::new(
        PluginOptions::default(),
        SessionPolicy::new(TurnBudget::Unbounded),
    );
    let env_spec_b = ProcessExecutionEnvSpec::new(
        PluginOptions::default(),
        SessionPolicy::new(TurnBudget::bounded(5)),
    );
    let env_ref_a =
        publish_process_execution_env_for_testing(env_store.as_ref(), &owner, &env_spec_a)
            .await
            .expect("env-a publishes");
    let env_ref_b =
        publish_process_execution_env_for_testing(env_store.as_ref(), &owner, &env_spec_b)
            .await
            .expect("env-b publishes");

    // The recorded cancellation authority is the host's derivation for the
    // admitted scope — identical across hosts over this journal path, so the
    // probe derives what every later host re-derives.
    let probe = world(path).await;
    let admitted_a = AdmittedScope::turn("session-a", "turn-a");
    let admitted_b = AdmittedScope::turn("session-b", "turn-b");
    let binding_a = recorded_cancellation_authority(&probe, &admitted_a).await;
    let binding_b = recorded_cancellation_authority(&probe, &admitted_b).await;
    drop(probe);

    let registry_a = Arc::new(TestLocalProcessRegistry::default());
    let intent_target_a = ProcessId::from(format!("{prefix}-intent-target-a"));
    registry_a
        .register_process_with_observers(
            ProcessRegistration::new(
                intent_target_a.clone(),
                ProcessInput::External {
                    metadata: serde_json::Value::Null,
                },
                RecoveryContract::ExternallyOwned,
                lash_core::ProcessProvenance::host(),
                ProcessLifecyclePolicy::new(ParentScope::Host, OnParentEnd::Abandon),
            )
            .with_extra_event_types(vec![ProcessEventType {
                name: INTENT_EVENT_TYPE.to_string(),
                payload_schema: lash_core::LashSchema::any(),
                semantics: lash_core::ProcessEventSemanticsSpec::default(),
            }]),
            std::slice::from_ref(&SessionId::from("session-a")),
        )
        .await
        .expect("register the intent target on A's registry");
    let registry_b = Arc::new(TestLocalProcessRegistry::default());

    let process_b = ProcessRef::new(
        "process-b",
        ProcessIncarnation::from_registration_sequence(7),
    );
    let scope_a = ExecutionScope::turn("session-a", "turn-a");
    let scope_b = ExecutionScope::turn("session-b", "turn-b");

    let provider_a = Arc::new(ProfileProvider {
        tag: "provider-a",
        park: false,
        impostor: false,
        observation: Arc::new(Observation::default()),
        session_id: SessionId::from("session-a"),
        intent_target: intent_target_a,
    });
    let provider_b = Arc::new(ProfileProvider {
        tag: "provider-b",
        park: false,
        impostor: true,
        observation: Arc::new(Observation::default()),
        session_id: SessionId::from("session-b"),
        intent_target: ProcessId::from("unused-intent-b"),
    });

    let mut turn_context_b = TurnContext::default();
    turn_context_b.insert_plugin_input("differential", "b-turn-context");

    let a = OpenerDeployment {
        plugin_factories: test_code_protocol_factories(),
        plugin_ids: "a:code-protocol",
        provider: Arc::clone(&provider_a),
        tool_registry: Arc::new(
            ToolRegistry::from_tool_provider(Arc::clone(&provider_a) as Arc<dyn ToolProvider>)
                .expect("A's provider registers"),
        ),
        catalog_definitions: leaf_definitions(),
        session_host: Arc::new(MockSessionManager::default()),
        processes: effect_backed_process_service(
            Arc::clone(&registry_a) as Arc<dyn ProcessRegistry>
        ),
        process_registry: registry_a,
        trigger_router: None,
        process_definitions: None,
        process_engines: ProcessEngineRegistry::default(),
        completion_log: Arc::default(),
        completion_canned: canned_completion("a", 41, 7),
        parent_invocation: RuntimeInvocation::effect(
            EffectAddress::new(scope_a.clone(), "parent-a").expect("a valid parent address"),
            RuntimeAttribution::none(),
            "parent-a",
        ),
        env_spec: env_spec_a,
        env_ref: env_ref_a,
        session_id: SessionId::from("session-a"),
        agent_frame_id: FrameNodeId::new("frame-a").expect("a valid frame id"),
        attachment_store: Arc::new(SessionAttachmentStore::in_memory()),
        attachment_source_policy: Arc::new(OpenAttachmentSourcePolicy),
        turn_context: TurnContext::default(),
        clock: Arc::new(SystemClock),
        opener: EffectOpener::for_scope(&admitted_a).expect("a turn scope derives an opener"),
        admitted_scope: admitted_a,
        routing: ToolChildCompletionRouting::Durable,
        enclosing_process: None,
        tag: "a",
    };
    let b = OpenerDeployment {
        plugin_factories: {
            let mut factories = test_code_protocol_factories();
            factories.push(process_engine_plugin_fixture());
            factories
        },
        plugin_ids: "b:code-protocol+fixture-engine",
        provider: Arc::clone(&provider_b),
        tool_registry: Arc::new(
            ToolRegistry::from_tool_provider(Arc::clone(&provider_b) as Arc<dyn ToolProvider>)
                .expect("B's provider registers"),
        ),
        catalog_definitions: b_catalog_definitions(),
        session_host: Arc::new(MockSessionManager::default()),
        processes: effect_backed_process_service(
            Arc::clone(&registry_b) as Arc<dyn ProcessRegistry>
        ),
        process_registry: registry_b,
        trigger_router: Some(TriggerRouter::new(
            Arc::new(InMemoryTriggerStore::default()),
            process_work_wiring_for_registry(
                Arc::new(TestLocalProcessRegistry::default()) as Arc<dyn ProcessRegistry>
            ),
        )),
        process_definitions: Some(Arc::new(InMemoryProcessDefinitionRegistry::default())
            as Arc<dyn lash_core::ProcessDefinitionRegistry>),
        process_engines: process_engine_fixture(),
        completion_log: Arc::default(),
        completion_canned: canned_completion("b", 13, 3),
        parent_invocation: RuntimeInvocation::effect(
            EffectAddress::new(scope_b.clone(), "parent-b").expect("a valid parent address"),
            RuntimeAttribution::none(),
            "parent-b",
        ),
        env_spec: env_spec_b,
        env_ref: env_ref_b,
        session_id: SessionId::from("session-b"),
        agent_frame_id: FrameNodeId::new("frame-b").expect("a valid frame id"),
        attachment_store: Arc::new(SessionAttachmentStore::in_memory()),
        attachment_source_policy: Arc::new(OpenAttachmentSourcePolicy),
        turn_context: turn_context_b,
        clock: Arc::new(TestClock::new(1_700_000_000_000)),
        opener: EffectOpener::process(process_b.clone()),
        admitted_scope: admitted_b,
        routing: ToolChildCompletionRouting::ProcessLifetime {
            issuer: TurnControlBindingId::new("binding-b-issuer").expect("a valid binding id"),
        },
        enclosing_process: Some(process_b),
        tag: "b",
    };

    let requests_a = requests_a(&a, &group_key, binding_a);
    let requests_b = requests_b(&b, &group_key, binding_b);
    (a, b, requests_a, requests_b, env_store)
}

/// The differential itself.
///
/// Phase 1 claims the four retained children under A's live opener on a host
/// that is then destroyed — claimed, journaled, owned by nobody. Phase 2
/// reopens under B's live opener offering the same replay keys under B's own
/// requests, staged with executors bound to B's live context; the honest
/// selector discards them on the envelope check, and with A's opener absent
/// the retained children run nowhere. Phase 3 registers *both* opener
/// contexts live on one recovering host and asserts every observable a
/// retained child can produce belongs to A.
#[tokio::test]
async fn a_child_runs_under_the_opener_that_admitted_it_not_the_one_reoffering_its_key() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("two-opener.db");
    let prefix = format!("two-opener-{:x}", fastrand::u64(..));
    let admitted = AdmittedScope::runtime_operation(format!("{prefix}-scope"));
    let scope = admitted.scope().clone();
    let key = format!("{prefix}-group");
    let (a, b, requests_a, requests_b, env_store) = fixture(&path, &prefix).await;

    // Phase 1: A's children are claimed and in flight when the process dies.
    let observation_crash = Arc::new(Observation::default());
    let park_provider = Arc::new(ProfileProvider {
        tag: "provider-a",
        park: true,
        impostor: false,
        observation: Arc::clone(&observation_crash),
        session_id: a.session_id.clone(),
        intent_target: a.provider.intent_target.clone(),
    });
    crash_opening(
        &path,
        group(&scope, &key, &requests_a),
        admitted.clone(),
        &a,
        park_provider,
        Arc::clone(&env_store),
        observation_crash,
    );
    until_leases_lapse(&path, &key, &env_store).await;

    // Phase 2: B's world. The composite stages executors bound to B's live
    // context for the offered keys; the honest selector discards them
    // because the offered envelopes differ from the retained bytes, and the
    // retained asks fall through to the real child host — where A's opener
    // is absent — and answer `None`.
    let world_b = world(&path).await;
    let dyn_b: Arc<dyn EffectHost> = Arc::clone(&world_b) as Arc<dyn EffectHost>;
    let child_host_b = Arc::new(ToolChildHost::new(&dyn_b, Arc::clone(&env_store)));
    let resolvers = Arc::new(DifferentialResolvers {
        staged: Mutex::new(HashMap::new()),
        retained: Arc::clone(&child_host_b),
        asked: Mutex::new(Vec::new()),
    });
    world_b
        .register_group_executors(Arc::clone(&resolvers) as Arc<dyn GroupExecutors>)
        .expect("a freshly opened host has no resolver yet");
    let coop_b_phase2 = CancellationToken::new();
    let (_guard_b2, context_b) = b.register_opener(
        &world_b,
        &child_host_b,
        Arc::clone(&b.provider) as Arc<dyn ToolProvider>,
        &coop_b_phase2,
    );
    let group_b = group(&scope, &key, &requests_b);
    for child in group_b.children() {
        resolvers.staged.lock_recover().insert(
            child.invocation.replay_key().to_string(),
            child_host_b.executor_bound_to(context_b.clone()),
        );
    }
    let scoped_b = world_b
        .scoped(admitted.clone())
        .expect("the group scope binds");
    let mut handle_b = scoped_b
        .controller()
        .open_effect_group(group_b)
        .await
        .expect("a reopen tolerates a child this host cannot run");

    assert!(
        tokio::time::timeout(
            ABSENCE_BUDGET,
            scoped_b
                .controller()
                .await_next_settlement(&mut handle_b, CancellationToken::new()),
        )
        .await
        .is_err(),
        "no settlement arrives: nothing B resolved may run a retained child"
    );
    assert!(
        b.provider.observation.executions().is_empty(),
        "B's provider ran nothing: {:?}",
        b.provider.observation.executions()
    );
    let mut asked = resolvers.asked.lock_recover().clone();
    asked.sort();
    let mut expected_asks = (0..ARITY)
        .map(|position| child_key(&key, position))
        .collect::<Vec<_>>();
    expected_asks.sort();
    assert_eq!(
        asked, expected_asks,
        "the routing question the reopen asks is about the retained \
         children, once each — matching on the key alone would ask nothing"
    );
    scoped_b
        .controller()
        .close_effect_group(handle_b, RUN)
        .await
        .expect("the observing handle closes");
    drop(_guard_b2);
    drop(scoped_b);

    // Phase 3: an honest recovery. Both opener contexts are live in the same
    // real ToolChildHost — A's serving provider and B's impostor provider —
    // so which context a retained child binds is decided by its recorded
    // opener alone. Every observable must be A's.
    let world_c = world(&path).await;
    let installed_c = install_child_host(&world_c, &env_store);
    let coop_a = CancellationToken::new();
    let coop_b = CancellationToken::new();
    let _guard_a = a
        .register_opener(
            &world_c,
            &installed_c,
            Arc::clone(&a.provider) as Arc<dyn ToolProvider>,
            &coop_a,
        )
        .0;
    let _guard_b = b
        .register_opener(
            &world_c,
            &installed_c,
            Arc::clone(&b.provider) as Arc<dyn ToolProvider>,
            &coop_b,
        )
        .0;

    let scoped_c = world_c
        .scoped(admitted.clone())
        .expect("the group scope binds");
    let mut handle = scoped_c
        .controller()
        .open_effect_group(group(&scope, &key, &requests_a))
        .await
        .expect("an honest reopen runs the retained children");

    // The deferred child parks on a completion key minted under A's recorded
    // routing; the issuer's scope is A's admitted scope.
    let defer_call = format!("{key}-call-{}", position_of(TOOL_DEFER));
    let parked = a.provider.observation.parked_key(&defer_call).await;
    assert_eq!(
        parked.scope,
        ExecutionScope::turn("session-a", "turn-a"),
        "the deferred child's completion key is issued under A's scope"
    );
    world_c
        .resolve_await_event(
            &parked,
            Resolution::Ok(serde_json::json!({ "resolved": "by-a" })),
        )
        .await
        .expect("the parked child's key resolves");

    // The gate child parks on the resolved opener's cooperative token.
    tokio::time::timeout(SETTLE_BUDGET, async {
        while a.provider.observation.gate_entered.load(Ordering::SeqCst) == 0 {
            tokio::time::sleep(POLL).await;
        }
    })
    .await
    .expect("the gate child entered its body");

    // Settle ranks 0–2 while the gate child waits on A's gate.
    let mut settlements = Vec::new();
    for rank in 0..ARITY - 1 {
        let settlement = tokio::time::timeout(
            SETTLE_BUDGET,
            scoped_c
                .controller()
                .await_next_settlement(&mut handle, CancellationToken::new()),
        )
        .await
        .unwrap_or_else(|_| panic!("settlement for rank {rank} never arrived"))
        .unwrap_or_else(|error| panic!("settlement for rank {rank} failed to be served: {error}"));
        settlements.push(settlement);
    }

    // B's gate does not stop A's child; A's does.
    coop_b.cancel();
    assert!(
        tokio::time::timeout(
            ABSENCE_BUDGET,
            scoped_c
                .controller()
                .await_next_settlement(&mut handle, CancellationToken::new()),
        )
        .await
        .is_err(),
        "cancelling B's cooperative token does not stop a child admitted under A"
    );
    coop_a.cancel();
    let gate_settlement = tokio::time::timeout(
        SETTLE_BUDGET,
        scoped_c
            .controller()
            .await_next_settlement(&mut handle, CancellationToken::new()),
    )
    .await
    .expect("cancelling A's cooperative token settles the gate child")
    .expect("the gate settlement is served");
    settlements.push(gate_settlement);
    // Settlements are served in settle order, not rank order — index by the
    // position each reports, the way the journal names it.
    settlements.sort_by_key(|settlement| settlement.position);

    // ---- Every observable is A's ----
    let executions = a.provider.observation.executions();
    assert_eq!(
        executions.len(),
        ARITY + 1,
        "A's provider ran every retained leaf body exactly once, plus the \
         spend leaf's retried attempt: {executions:?}"
    );
    assert!(
        executions
            .iter()
            .all(|execution| execution.session_id == "session-a"),
        "every execution was attributed to A's session: {executions:?}"
    );
    let observe = executions
        .iter()
        .find(|execution| execution.tool == "a_observe")
        .unwrap_or_else(|| panic!("the observe leaf ran: {executions:?}"));
    assert_eq!(
        observe.execution_binding,
        serde_json::json!({ "opener": "a" }),
        "the granted leaf executed under the recorded grant's binding"
    );
    assert!(
        executions
            .iter()
            .all(|execution| execution.enclosing_process.is_none()),
        "every attempt context was built from the retained request — A's \
         children record no enclosing process: {executions:?}"
    );
    let mut spend_attempts = executions
        .iter()
        .filter(|execution| execution.tool == "a_spend")
        .map(|execution| execution.attempt)
        .collect::<Vec<_>>();
    spend_attempts.sort_unstable();
    assert_eq!(
        spend_attempts,
        vec![1, 2],
        "the spend leaf ran its failed attempt and its retry: {executions:?}"
    );
    assert!(
        b.provider.observation.executions().is_empty(),
        "B's provider never ran: {:?}",
        b.provider.observation.executions()
    );

    // Billing: only A's completion client was billed, and the ledger on the
    // spend settlement carries A's canned usage — twice, once per attempt.
    assert_eq!(
        a.completion_log.lock_recover().len(),
        2,
        "A's completion client billed once per spend attempt: {:?}",
        a.completion_log.lock_recover()
    );
    assert!(
        b.completion_log.lock_recover().is_empty(),
        "B's completion client was never billed"
    );
    let spend = &settlements[position_of(TOOL_SPEND)];
    let Ok(RuntimeEffectOutcome::ToolInvocation {
        settlement,
        outcome,
    }) = &spend.outcome
    else {
        panic!("the spend child settles a tool invocation: {spend:?}")
    };
    assert!(
        matches!(
            outcome.record.output.outcome,
            lash_core::ToolCallOutcome::Success(_)
        ),
        "the spend child settled successfully: {outcome:?}"
    );
    let billed: i64 = settlement
        .usage
        .iter()
        .map(|delta| delta.usage.input_tokens)
        .sum();
    assert_eq!(
        billed, 82,
        "the ledger carries A's canned usage across both attempts"
    );
    assert!(
        settlement
            .usage
            .iter()
            .all(|delta| delta.llm_call_id == LlmCallId("a-direct-call".to_string())),
        "every billed delta names A's call: {:?}",
        settlement.usage
    );
    let mut attempts = settlement
        .usage
        .iter()
        .map(|delta| delta.attempt)
        .collect::<Vec<_>>();
    attempts.sort_unstable();
    assert_eq!(
        attempts,
        vec![1, 2],
        "the failed first attempt's spend is journaled beside the second's"
    );

    // Possession and fact buffers: the intents realized on A's registry, and
    // the settlement carries the started process plus the event outcome.
    assert_eq!(
        settlement.possession.len(),
        1,
        "the started process rides the settlement's possession"
    );
    let a_events = a.process_registry.raw_state_for_testing().await.events;
    assert!(
        a_events
            .iter()
            .any(|(_, event)| event.event_type == INTENT_EVENT_TYPE),
        "the declared process event landed on A's registry: {a_events:?}"
    );
    let b_events = b.process_registry.raw_state_for_testing().await.events;
    assert!(
        b_events.is_empty(),
        "B's registry received no intent realization: {b_events:?}"
    );

    // The gate settlement carries A's cancel: the cooperative token that
    // stopped the child was the resolved opener's.
    let gate = &settlements[position_of(TOOL_GATE)];
    let Ok(RuntimeEffectOutcome::ToolInvocation {
        outcome: gate_outcome,
        ..
    }) = &gate.outcome
    else {
        panic!("the gate child settles a tool invocation: {gate:?}")
    };
    assert!(
        format!("{:?}", gate_outcome.record.output).contains("cooperative gate"),
        "the gate child settled as cancelled under A's token: {gate_outcome:?}"
    );

    // The deferred settlement carries the out-of-band resolution issued
    // under A's completion authority.
    let deferred = &settlements[position_of(TOOL_DEFER)];
    let Ok(RuntimeEffectOutcome::ToolInvocation {
        outcome: deferred_outcome,
        ..
    }) = &deferred.outcome
    else {
        panic!("the deferred child settles a tool invocation: {deferred:?}")
    };
    assert!(
        format!("{:?}", deferred_outcome.record.output).contains("by-a"),
        "the deferred child settled with the resolution issued under A's \
         completion routing: {deferred_outcome:?}"
    );

    scoped_c
        .controller()
        .close_effect_group(handle, RUN)
        .await
        .expect("the caller closes");
}

/// The oracle is only worth trusting if it goes red against the leak it
/// names. The leak is injected at the production selector: this host's
/// offered-child selection is flipped to `KeyOnly`, so the executors staged
/// for B's offered children — real runners bound to B's live context — are
/// reused for the retained children on a replay-key match alone. The
/// resolver stays honest; the leak is in the selector, exactly where the
/// fix holds it closed.
#[tokio::test]
async fn the_oracle_goes_red_when_offered_executors_match_by_key_alone() {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("two-opener-mutant.db");
    let prefix = format!("two-opener-mutant-{:x}", fastrand::u64(..));
    let admitted = AdmittedScope::runtime_operation(format!("{prefix}-scope"));
    let scope = admitted.scope().clone();
    let key = format!("{prefix}-group");
    let (a, b, requests_a, requests_b, env_store) = fixture(&path, &prefix).await;

    let observation_crash = Arc::new(Observation::default());
    let park_provider = Arc::new(ProfileProvider {
        tag: "provider-a",
        park: true,
        impostor: false,
        observation: Arc::clone(&observation_crash),
        session_id: a.session_id.clone(),
        intent_target: a.provider.intent_target.clone(),
    });
    crash_opening(
        &path,
        group(&scope, &key, &requests_a),
        admitted.clone(),
        &a,
        park_provider,
        Arc::clone(&env_store),
        observation_crash,
    );
    until_leases_lapse(&path, &key, &env_store).await;

    // B's world, poisoned at the selector: the staged B-bound executors are
    // reused for the retained children on a replay-key match alone.
    let world_b = world(&path).await;
    world_b
        .replay_driver()
        .set_offered_child_selection(OfferedChildSelection::KeyOnly);
    let dyn_b: Arc<dyn EffectHost> = Arc::clone(&world_b) as Arc<dyn EffectHost>;
    let child_host_b = Arc::new(ToolChildHost::new(&dyn_b, Arc::clone(&env_store)));
    let resolvers = Arc::new(DifferentialResolvers {
        staged: Mutex::new(HashMap::new()),
        retained: Arc::clone(&child_host_b),
        asked: Mutex::new(Vec::new()),
    });
    world_b
        .register_group_executors(Arc::clone(&resolvers) as Arc<dyn GroupExecutors>)
        .expect("a freshly opened host has no resolver yet");
    let coop_b = CancellationToken::new();
    let (_guard_b, context_b) = b.register_opener(
        &world_b,
        &child_host_b,
        Arc::clone(&b.provider) as Arc<dyn ToolProvider>,
        &coop_b,
    );
    let group_b = group(&scope, &key, &requests_b);
    for child in group_b.children() {
        resolvers.staged.lock_recover().insert(
            child.invocation.replay_key().to_string(),
            child_host_b.executor_bound_to(context_b.clone()),
        );
    }
    let scoped_b = world_b
        .scoped(admitted.clone())
        .expect("the group scope binds");
    let mut handle = scoped_b
        .controller()
        .open_effect_group(group_b)
        .await
        .expect("the poisoned reopen runs");

    // Every green-path assertion inverts: B's impostor provider executes the
    // retained children under B's context, and settlements arrive.
    tokio::time::timeout(SETTLE_BUDGET, async {
        while b.provider.observation.executions().is_empty() {
            tokio::time::sleep(POLL).await;
        }
    })
    .await
    .expect(
        "under the key-only selector B's provider runs the retained children — \
         the oracle's `B's provider ran nothing` assertion fails here",
    );
    let settlement = tokio::time::timeout(
        SETTLE_BUDGET,
        scoped_b
            .controller()
            .await_next_settlement(&mut handle, CancellationToken::new()),
    )
    .await;
    assert!(
        settlement.is_ok(),
        "under the key-only selector a retained child settles — the oracle's \
         `no settlement arrives` assertion fails here"
    );
    assert!(
        b.provider
            .observation
            .executions()
            .iter()
            .all(|execution| execution.tool.starts_with("a_")),
        "B's impostor impl served A's retained leaf calls: {:?}",
        b.provider.observation.executions()
    );
    assert!(
        a.provider.observation.executions().is_empty(),
        "A's provider never ran — the work happened under B's context"
    );

    drop(_guard_b);
    scoped_b
        .controller()
        .close_effect_group(handle, RUN)
        .await
        .expect("the caller closes");
}
